### ISSUE TITLE
Memoria

### ISSUE THREAD

**Issue by romhackingvn** [Albeoris/Memoria#1]
I am using Visual Studio 2013, I have some error when build project:
http://i730.photobucket.com/albums/ww301/quoc_pro/error_zpsqnt7fmxz.png
I follow instruction:
Install Unity 5.13f1, maybe my version not compatible. Could you share me builded program? Thanks!

**Comment by Albeoris** [comment]
Use Visual Studio 2015. :)
You cannot use C# syntax in the VS2013... usaly.

**Comment by romhackingvn** [comment]
Thanks!
