### ISSUE TITLE
Giving you the output.log to what i wrote in steam.

### ISSUE THREAD

**Issue by uzoko1** [Albeoris/Memoria#10]
[output_log.txt](https://github.com/Albeoris/Memoria/files/306126/output_log.txt)

There you go. thats the HP thing going wack during first theatre fight with leo and two goons. constant damage when they first hit like 11= a million of 11's and hp stays at 9999 which idk why its at 9999 since i didnt set it.

**Comment by Albeoris** [comment]
Thank you!
