### ISSUE TITLE
Can't get the Steam overlay to work 

### ISSUE THREAD

**Issue by polt13** [Albeoris/Memoria#102]
Hi, 

I've already seen this issue opened up here a while ago: #59  but even though I tried to apply the solution, it doesn't really seem to fix it:

I tried deleting the FF9_Launcher.exe, then renaming FF9_Launcher.bak to FF9_Launcher.exe but soon as I launch it I get the stock launcher back, until I run the Memoria patcher again. Is there a way around it as of now?

Thanks a lot.

**Comment by Albeoris** [comment]
That's right. Unfortunately, this is the only solution.

I took apart the original launcher, and I don’t understand what the difference between them is. Steam may be verifying the digital signature, but then I don’t understand why this is not happening at all.

Anyway, at the moment this is the only way to solve the problem.
Play with the original launcher. :(

**Comment by polt13** [comment]
I see. Thank you, it's not a big deal but it'd be nice if there was some way to get it to work with memoria.

Keep up the awesome work!

**Comment by Albeoris** [comment]
Perhaps there is some kind of problem starting as administrator or UAC.

**Comment by polt13** [comment]
the x64 executable doesn't work if I exec as admin with UAC turned to the lowest possible for me, neither does the launcher itself. So you may be right, not sure how to fix this though.

**Comment by Albeoris** [comment]
@polt13 , can you try this release?
https://github.com/Albeoris/Memoria/releases/tag/v2020.05.17.4

**Comment by polt13** [comment]
It works! @Albeoris

**Comment by Albeoris** [comment]
Nice! :)
