### ISSUE TITLE
[BUG] Non-english place names are scrambled in 64 resolution

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#103]
I did all the tests and I can definitely say the problem is with Memoria.
I tested all possible configurations, the problem only appears when TileSize = 64 and you select a language other than English.

-Fresh install 32 tilesize: all languages OK
-Fresh install 64 tilesize: all languages OK
-Fresh install 32 tilesize + memoria: all languages OK
-Fresh install 64 tilesize + memoria: English OK, other languages look like this:

![2020-05-17 11_41_03-FINAL FANTASY IX - Map_ 100, Loc_ 33 Name_ Cabine_Prima Vista](https://user-images.githubusercontent.com/9964576/82141015-54b31d00-9833-11ea-9106-4cdc71c475bc.jpg)

![2020-05-17 11_11_32-FINAL FANTASY IX - Map_ 908, Loc_ 70 Name_ Porte Tréno_Porte Sud](https://user-images.githubusercontent.com/9964576/82141023-698fb080-9833-11ea-903b-9cb39afb25f1.jpg)

Note: I had screens that looked this like in the past when some fileds were missing languages in the textures, but my texture files are complete (I even exported atlas.png for Alexandria to check)

**Comment by snouz** [comment]
p0data11 (with beginning of the game in 64 tilesize)
https://mega.nz/file/HG5gRIab#hxkuJ2nmLySFvcyCYjURJPliQ7F2S1UmfTWjvOQLtr8

to reproduce it: replace p0data11, set 64 in tilesize, set the game in another language in the menu, launch a new game until the alexandria intro

**Comment by Albeoris** [comment]
![](https://i.imgur.com/XT01sOw.png)

**Comment by Albeoris** [comment]
![](https://i.imgur.com/52XXs9r.jpg)
Fixed
