### ISSUE TITLE
[BUG] Some fonts work in memoria.ini, others don't

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#104]
I've tested a number of fonts in memoria.ini
[Font]
Enabled = 1
Names = "Times Bold"
Size = 24

On those that are NOK, it reverts back to arial.
"Times Bold" NOK
"Alexandria Regular" NOK (although the name of the font is just Alexandria)
"Bitter Regular" NOK
"Terminal" NOK
"Terminal Regular" NOK
"Rockwell Regular" NOK

Those that worked
"Impact" OK
"Rockwell" OK
"Lucida Handwriting" OK
"Montserrat" OK

It doesn't depend on TrueType or OpenType.
I thought it had something to do with numerically signed fonts, but Montserrat is unsigned and works.

**Comment by snouz** [comment]
Ultimately, this is the font I'm trying to make work
https://mega.nz/file/uXp3WazA#ONzxLpQGiG119VZfpHyfK9kcisIxGAYpFqD5bhGb9aE

**Comment by snouz** [comment]
"Blackadder ITC" OK

I tried putting my font (Alexandria.ttf) in fontforge, changing the parameters to be the same as Rockwell for example.
![2020-05-17 18_54_58-Infos fonte pour Alexandria](https://user-images.githubusercontent.com/9964576/82154921-6e735500-9871-11ea-923a-9c04f6aa02ab.jpg)

This did not work.

**Comment by Albeoris** [comment]
The font is incorrect or incorrectly installed, the method [Font.GetOSInstalledFontNames](https://docs.unity3d.com/ScriptReference/Font.GetOSInstalledFontNames.html) does not return it.

**Comment by Albeoris** [comment]
I checked in 2018.4.21f1 - the same behavior, this font is not in the list of available ones. I do not know why. I propose to ask a question on the Unity forum.

**Comment by snouz** [comment]
I figured out you need to install the font "for all user" using admin privilege.
