### ISSUE TITLE
[BUG] some scenes NOT excluded from widescreen, despite being in the list

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#106]
These scenes are not widescreen deactivated in some parts of the game, despite being in this list:
https://github.com/Albeoris/Memoria/compare/v2020.05.12...v2020.05.17
1210 in CD1
1213 in CD3
1214 in CD1 & CD3
1215 in CD1 (CD3, widescreen is active but there's bug #105 )
1226 in CD1 & CD3

I have tested all the scenes in the Garnet rescue in CD2, and they all work correctly.

From my test, it only appears in this section of the fields (Alexandria Castle)

BTW 1212 should be added to the list

**Comment by Albeoris** [comment]
II think the problem here is that the wrong numbers are used.
Can you get the right map numbers?

**Comment by snouz** [comment]
Here's a revision to the exclusion list:

**ADD:**
153
154
162
167
1212 
1301
1303
1308
1314
1464
1803
1806
1813
1814
1816
1817
1820
1822
1857
1858
2010
2101
2103
2108
2150
2151
2157
2159
2400
3052
3054
3056
3058


**REMOVE:**
2172
