### ISSUE TITLE
Defender thinks the new Patcher is a 'trojan'

### ISSUE THREAD

**Issue by polt13** [Albeoris/Memoria#109]
Any idea which change might be causing it? The moment I install it it picks it up and deletes it.

**Comment by snouz** [comment]
Do you have the latest windows update, the May update? My computer is making me install it tonight.

Every version I tested recently had a warning for untrusted source, but not outright quarantining. Defender here too.

**Comment by polt13** [comment]
I've not got it yet, is it out? If so I will install it today. However even a VirusTotal checker picks it up for some reason (its the only one though)

**Comment by snouz** [comment]
![2020-05-20 16_19_56-VirusTotal](https://user-images.githubusercontent.com/9964576/82457490-c7cbc600-9ab5-11ea-8086-9d22cbba8c72.png)

**Comment by Albeoris** [comment]
False-positive

**Comment by Albeoris** [comment]
I wrote a message to the authors.

**Comment by polt13** [comment]
You mean endgame antivirus developers? If so, great! Not that I don't trust the mod but it grabbed my attention because defender just quarantined it instantly.

**Comment by Albeoris** [comment]
Nice! :)

**Comment by polt13** [comment]
By the way, @Albeoris the same company from Virustotal still seem to be picking it up as a virus, I don't know why.
