### ISSUE TITLE
Two Request

### ISSUE THREAD

**Issue by uzoko1** [Albeoris/Memoria#11]
The first one is silly and may be impossible, but is it possible to choose who you run around with? like instead of Vivi, Zidane, Garnet, or Steiner, you can use the others? That is probably impossible but you know more than I do.

2nd one is one you may have remembered me asking and that was main battles. Making it possible to use the party you edited in to fight the story battles...not get to Waltz no. 1 or 2 and have lvl 1 Zidane vivi and steiner try and fight it when my main party is others... haha thanks for taking your time though.

**Comment by uzoko1** [comment]
Awesome thanks!

**Comment by uzoko1** [comment]
Just asking is the self assign and everything mean you are working on the 2nd request? the mian battle one? That one is the most important to me xD

**Comment by uzoko1** [comment]
Hey so in the Memoria.csproj I found this in FF9 play. Would this be where you can edit the minor characters perm in there during the main events battles?
![capture](https://cloud.githubusercontent.com/assets/19294936/15993667/d7d4d26a-30b2-11e6-8425-290e1fed4de5.PNG)

**Comment by uzoko1** [comment]
This also, can you actually increase the max party when you use the Alt+F2  command, there would be room for the other 3? also everything else i circled lol..
![capture](https://cloud.githubusercontent.com/assets/19294936/15993709/f5cbbac6-30b3-11e6-8fc1-0161395e1fa9.PNG)

**Comment by Albeoris** [comment]
> Hey so in the Memoria.csproj I found this in FF9 play. Would this be where you can edit the minor characters perm in there during the main events battles?
Nope. Look at EventEngine. ;)

FF9PARTY_PLAYER_MAX it's count of free slots in the right panel. There is no easy way to increase it.
https://i.imgur.com/B3VR8O7.png

**Comment by uzoko1** [comment]
![capture](https://cloud.githubusercontent.com/assets/19294936/16221506/c836a2be-3758-11e6-8332-65cef04e2d04.PNG)

**Comment by Albeoris** [comment]
Build

    Use Visual Studio 2015
    Install Unity: https://unity3d.com/
    Set a correct path to the Unity library folder in the Memoria.csproj (Notepad) C:\Program Files\Unity\Editor\Data\Mono\lib\mono\unity</FrameworkPathOverride>
    Create the "\References" folder in the root solution directory.
    Copy "Assembly-CSharp.dll", "UnityEngine.dll" and "XInputDotNetPure.dll" from "\FINAL FANTASY IX\x64\FF9_Data\Managed" to "\References"
    Download "Mono.Cecil" package manualy or enable automaticaly package downloads.

**Comment by Albeoris** [comment]
![It will not be easy.](https://i.imgur.com/quqhxJp.png)

**Comment by Albeoris** [comment]
Unfortunately, standard assets are not enough to implement this. For example, animations.
