### ISSUE TITLE
Tetra Master opponents decks issue

### ISSUE THREAD

**Issue by kadyr** [Albeoris/Memoria#111]
At the beginning of each Tetra Master game, cards used by opponent randomly generates from the deck containing 16 cards. List of decks can be found here:

https://finalfantasy.fandom.com/wiki/Final_Fantasy_IX_opponents%27_Tetra_Master_decks

However, due to bug in Steam version, rarest card (16th in the deck) never appears. Possible explanation of the bug in post №5:

https://gamefaqs.gamespot.com/boards/197338-final-fantasy-ix/74382891

**Comment by Albeoris** [comment]
Fixed. Thank you!
