### ISSUE TITLE
[Improvement] Ways to have widescreen on more fields

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#115]
I had to add a number of WS compatible maps to the list of exclusion despite being theorically able to be displayed wide.

We could unlock a lot of screens for widescreen if we figure out:

1) how to restrict field width to a certain number of pixels (and the rest would behave like narrow, but with more game pixels - I can provide a dictionary in C# form with a width for each map)
2) how to switch between widescreen & narrow in 2 screens of the same field

Examples of problematic fields:
**case 1:** size is simply between widescreen and narrow
![2020-05-12 00_37_52-FINAL FANTASY IX - Map_ 1303, Loc_ 485 Name_ Lindblum_Main Street](https://user-images.githubusercontent.com/9964576/82665739-ba891580-9c34-11ea-8310-93c14a3e35dd.jpg)
Solution: setting a middle ground between narrow and wide (with a width value for each map), we could display these in their entirety without seeing characters on black borders.

**case 2:** scrolling layer
![2020-05-12 00_17_45-FINAL FANTASY IX - Map_ 1058, Loc_ 44 Name_ Cleyra_Observation Poi](https://user-images.githubusercontent.com/9964576/82666349-06888a00-9c36-11ea-9ad5-f9fd3f18b535.jpg)
Solution: Restricting the camera to the actual ground width, without having it pan out of it (the width here is extended by the scrolling layer)

**case 3:** map width is larger than what the field suggests
In some cases, for no reason, if we allow widescreen, the camera is restricted to a limit that is outside of the map
![2020-05-12 17_50_42-FINAL FANTASY IX - Map_ 2053, Loc_ 91 Name_ Alexandria_Square](https://user-images.githubusercontent.com/9964576/82666868-0b9a0900-9c37-11ea-82b8-ef378febf20b.jpg)
Solution: maybe the position of the camera is restricted like this: "center of camera can't go (320px / 2) from the border", which should be converted to something like "center of camera can't go (PsxFieldWidth / 2) from the border" ; I suppose

**case 4:** one script in one scene is making the outside of the screen visible
For example: This one when you go to Dali for the first time, camera is forced there:
![2020-05-12 17_22_12-FINAL FANTASY IX - Map_ 351, Loc_ 47 Name_ Dali____](https://user-images.githubusercontent.com/9964576/82667865-f9b96580-9c38-11ea-9a7c-6cfb45ecd121.jpg)
Solution: This movement is presumably guided by the game script in p0data7, so I might be able to fix it there. For this one in particular, it's the line if ( General_FieldEntrance == 16 ) { MoveCamera( 160, 140, 1, 8 )

**case 5:** 1 field, 2 screens of different size
If we can transition between narrow and WS when switching between screens of the same field, a number of fields would be unlocked.
![2020-05-11 22_42_37-FINAL FANTASY IX - Map_ 153, Loc_ 3 Name_ A  Castle_Public Seats](https://user-images.githubusercontent.com/9964576/82669532-e78cf680-9c3b-11ea-92af-780a4a881e53.jpg)

**Comment by snouz** [comment]
I'm pretty sure case 2 and 3 could be solved in the calculation that happens in \Field\Map\FieldMap.cs

**Comment by snouz** [comment]
Case 4 seemed to have been solved by a past update. Field 351 can be removed from the list

From case 3, we can remove 2716 & 355

**Comment by snouz** [comment]
767 needs to be added to the list.

**Comment by snouz** [comment]
I managed to compile memoria and create a fix to solve case 5 (switch of camera), confirmed to work!

**Comment by snouz** [comment]
case 2 & 3 should be solved soon! There's only case 1 now that could be improved.

**Comment by snouz** [comment]
Ok case 5 fix is completely broken, it does a 39 shift to the left every time, working on it.

In the meantime, I found the value/script to modify to fix case 1, which means screens between (orig) 328 -> 390 width should be soon displayed in full width.

**Comment by Skyyblaze** [comment]
Is this issue also the reason why some screens like the Dali Inn are widescreen when the game is paused and 4:3 when not?

**Comment by snouz** [comment]
Not exactly, but that's another issue. I'll open a ticket for that.
