### ISSUE TITLE
Switch A/B (X/O) buttons by default

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#116]
Puzzlingly, the default layout contradicts all gaming conventions (in the west at least?) that A (or X on playstation) is for action/confirm and B (or O on playstation) is for cancel/return. Instead A is cancel and B is confirm. Even if you go through the hassle of changing it in your game options, it's still inverted in the start menu.

Could this be changed by default in memoria, or with an option in Memoria.ini ?
The original game (at least the PAL version) had the classic / normal layout, and I believe the A=cancel B=confirm comes from the Japanese version only.

(note: if you manage to switch the mapping of the button, don't forget to switch the sprite displayed in the options too. Another problem is that current saves might be inverted if you do that)

**Comment by Caledor** [comment]
@snouz Also, during the duel scene with Blank, A and B are swapped in the tutorial dialogue.

I found in the vanilla assembly c sharp some code related to japanese/western button config, but i couldn't go further. No matter what i did i couldn't manage to switch them.

**Comment by IFireflyl** [comment]
> 
> 
> @snouz Also, during the duel scene with Blank, A and B are swapped in the tutorial dialogue.
> 
> I found in the vanilla assembly c sharp some code related to japanese/western button config, as well as the sprite linking, but i couldn't go further. No matter what i did i couldn't manage to switch them.

I'm pretty sure this is due to Steam using controller settings in the game. My friend was using a PS4 controller and had this occurring. He switched to my Xbox One controller and it's not an issue any longer.

**Comment by faospark** [comment]
was this implemented? it is also mentioned in Moguri that it is emplented but  it seem to be not. Is there a setting to turn this on ?

**Comment by snouz** [comment]
Implemented in Memoria, but there hasn't been a new Moguri update yet (since August of last year)
