### ISSUE TITLE
Leaving to main menu leaves confirm box visible when returning to options

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#117]
I left using return to main menu in CONFIG and reloaded another save, returned to the game, went to CONFIG again, the confirm box was still there

![2020-05-22 23_13_56-FINAL FANTASY IX - Map_ 611, Loc_ 22 Name_ L  Castle_Hallway](https://user-images.githubusercontent.com/9964576/82730516-a3aff500-9d00-11ea-942c-96e57b41008c.png)

**Comment by Albeoris** [comment]
I cannot to reproduce this bug. :(

**Comment by tbartel** [comment]
Can confirm that I'm also seeing this bug and can reliably reproduce it. Would it help if I enabled debugging and supplied a log? I'm not sure what's captured in there, so perhaps something additional is needed.

**Comment by snouz** [comment]
Can't reproduce anymore. Closing.
