### ISSUE TITLE
[BUG] Movie gallery plays 30fps FMVs at half the speed of before

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#118]
User reported FMVs played correctly in the game, but through the movie gallery in the main menu (don't have that gallery in my version I think?) it's playing at half the speed of the previous time:
https://www.youtube.com/watch?v=nnCjr_cUo5Y&feature=youtu.be

So it plays 30fps, then 15fps, then 7.5... (apparently)

**Comment by Caledor** [comment]
Suggestion:
In MovieMaterial

Changing
this.playSpeed = (float)(this.playSpeed * 15.0 / this.currentFPS);
To
this.playSpeed = (float)(15.0 / this.currentFPS);

worked for me.
