### ISSUE TITLE
[Suggestion] Add steal cheat to main mod with .ini configuration option

### ISSUE THREAD

**Issue by DoomOyster** [Albeoris/Memoria#123]
edit: oops, I was using an outdated version of the compiler. but now I am wondering if compiling in the steal cheat will break tehMighty's menus.

**Comment by Albeoris** [comment]
Hi. Explain what kind of problem are you talking about?
Also share output_log.txt and Memoria.log

**Comment by DoomOyster** [comment]
Regarding #131, I think this merged into main branch to always steal? Can this be an optional cheat? Also, this is kind of nice, to steal in order of rarity starting with rarest first:

if (enemy.StealableItems[3] != Byte.MaxValue)
StealItem(enemy, 3);
else if (enemy.StealableItems[2] != Byte.MaxValue)
StealItem(enemy, 2);
else if (enemy.StealableItems[1] != Byte.MaxValue)
StealItem(enemy, 1);
else
StealItem(enemy, 0);

**Comment by snouz** [comment]
I implemented it and included 2 options: 2 is to never fail at all (it activates bandit all the time)
