### ISSUE TITLE
 custom theme problem with a tick

### ISSUE THREAD

**Issue by shikulja** [Albeoris/Memoria#126]
should be like that:
![Скриншот 27-05-2020 115257](https://user-images.githubusercontent.com/3386359/83002215-753e5c80-a015-11ea-82d6-8542852b7481.png)
![Скриншот 27-05-2020 115101](https://user-images.githubusercontent.com/3386359/83002217-766f8980-a015-11ea-8d6b-f184b610f9ff.png)
![Скриншот 27-05-2020 114957](https://user-images.githubusercontent.com/3386359/83002219-766f8980-a015-11ea-9222-b8351c5ca9a6.png)

in fact, like this:
![Аннотация 2020-05-27 114726](https://user-images.githubusercontent.com/3386359/83002290-8be4b380-a015-11ea-8ffb-89102eb3a8b7.png)

**Comment by snouz** [comment]
I don't understand the problem

**Comment by shikulja** [comment]
@snouz 
"ticks" are not visible when a non-standard theme is installed
they are very bright in the launcher.
but in other applications everything is fine
