### ISSUE TITLE
Ending FMV ends at half when 30fps, with logo "the end" and frozen frame

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#127]
![2020-05-27 14_57_35-FMV End Too Early - Michael Cunnane png - Google Drive](https://user-images.githubusercontent.com/9964576/83021550-77f77c80-a02a-11ea-9277-add3836a348e.png)

**Comment by snouz** [comment]
Well I don't know if it's "at half", but prematurely

**Comment by Caledor** [comment]
FMV059 ends a few seconds earlier, FMV060 about a minute earlier. Replacing them with vanilla versions fixes the issue.

**Comment by Kidel** [comment]
On FMV059 I may have added a second while editing to fix some issues with the interpolator (DAIN) failing on some frames. Having a feature to get video duration to avoid cuts would solve the issue and allow more editing freedom in the future.

**Comment by Kidel** [comment]
Have no idea about 060 tho. That one is just interpolated with no editing, has the same duration and works fine in the player. 

Probably there is a script that counts after how many frames the text should appear (similar to the one for character movement during MBG videos). @snouz

**Comment by snouz** [comment]
I'll just force rename these two files if mod is detected.
