### ISSUE TITLE
Scaling Font Size

### ISSUE THREAD

**Issue by Caledor** [Albeoris/Memoria#129]
The Font "Size" parameter in the ini doesn't work as anyone would expect.
Looking at the code, it's simply used as a parameter for the font importer, to determine the reference font size. It doesn't affect how big the text looks in game.

Now for the suggestion part: since most custom fonts will be noticeably smaller than the original one, what about adding a setting that actually increases the size of the in-game font when a custom one is loaded?

**Comment by RealUn2ken** [comment]
aside from scaling. instructions should include to use font installed for all users.  it is required for the mod work. 
One more thing . the mod fails to recognize "Regular", "Medium", "Light" version of fonts if is part of the namespace of the font variant. Bold it does but for the former it seems not.
