### ISSUE TITLE
Bug in abilities.

### ISSUE THREAD

**Issue by uzoko1** [Albeoris/Memoria#13]
So when I put in the abilities for marcus cinnna and blank, in battle they have learned all of them already....any way to fix that?

**Comment by Albeoris** [comment]
Do you set AP for them?
Default: 0

**Comment by uzoko1** [comment]
Where do I change the AP values?

**Comment by Albeoris** [comment]
https://i.imgur.com/lkxBUWd.png

**Comment by uzoko1** [comment]
When getting to Evil Forest and you put Blank, Cinna, marcus, and beatrix in your party, It will still show Blank as the knight of pluto(which doesn't bother me), Marcus and Cinna will act like they still have the stage effects and all the new abilities I gave them, Are learned automatically again....So when i get into battle he has all of Zidanes skills learned, and Cinna has all of the blu mag learned already. anyway to fix this? The AP values are correct.

**Comment by uzoko1** [comment]
https://imgur.com/a/tLg4M

**Comment by Albeoris** [comment]
Will see. Thank you.
