### ISSUE TITLE
Pausing Disables Widescreen

### ISSUE THREAD

**Issue by IFireflyl** [Albeoris/Memoria#136]
When I have Widescreen enabled and then pause and unpause the game the Widescreen goes away. I then have to hit Alt+Spacebar to re-enable Widescreen. I'm currently playing at a resolution of 1920x1080 if that makes a difference.

It also appears that Widescreen goes away when moving to a screen that doesn't support Widescreen. When you move back to a screen that supports you then have to manually re-enable Widescreen with Alt+Spacebar.

**Comment by snouz** [comment]
Does it happen every time? What screen were you at when it happened?

**Comment by IFireflyl** [comment]
I'm currently in Lindblum, (the first time) and it does happen every time. I also edited my initial post.

**Comment by snouz** [comment]
You mean it was disabled in the throne room and then back up in the next scene? (that's normal, the throne room is excluded)

If you don't manually activate it, does it come back to normal in the following scenes?

**Comment by IFireflyl** [comment]
Ah. Well, when you first go into the throne room (you know, when you find out what Cid looks like) you can hit Alt+Spacebar to set it to fullscreen there. And it actually works until you pause. Now when the scene changes to a different angle of the throne room it doesn't have any fullscreen support. I had opened this as a potential issue because of the fact that this occurs as soon as you enter the throne room for the first time where it appears to have fullscreen support.

**Comment by snouz** [comment]
Ok I'll explain. some scenes have 2 or more cameras, like this one. The width of each camera background is not the same on each. On one, it's e.g. 460 in original pixels, and the other is 320. I can't (tried to implement it this week, but couldn't) switch between the two on camera change. So it stays 320 for both.

On some screens, in my last pull request, what I did is keeping the largest width of the two, but I can't do better for now.
