### ISSUE TITLE
Random Black Screen During Battle Start (STEAM BUG)

### ISSUE THREAD

**Issue by IFireflyl** [Albeoris/Memoria#137]
As the title says, you randomly encounter a black screen when you get into a battle. This causes you to have to force close FFIX. Here is the last section of the Memoria.log file that captures an error:

```
13.06.2020 12:49:15 |W| [SoundLib] FF9SOUND_SNDEFFECTRES_RESTORE: slot: 1 is null!

13.06.2020 12:49:18 |W| [SoundLib] FF9SOUND_SNDEFFECTRES_RESTORE: slot: 1 is null!

13.06.2020 12:49:27 |W| [SoundLib] Music Id: 136 has Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

13.06.2020 12:49:27 |W|   at System.Collections.Generic.Dictionary"??"2[System.Int32,System.String].get_Item (Int32 key) [0x00000] in <filename unknown>:0 

13.06.2020 12:49:27 |W|   at SoundMetaData.GetSoundProfile (Int32 soundIndex, SoundProfileType type) [0x00000] in <filename unknown>:0 

13.06.2020 12:49:27 |W|   at AllSoundDispatchPlayer.CreateSoundProfileIfNotExist (Int32 soundIndex, SoundProfileType type, .OnCreateFinish onFinishDelegate) [0x00000] in <filename unknown>:0 

13.06.2020 12:49:27 |W|   at AllSoundDispatchPlayer.FF9SOUND_SONG_PLAY (Int32 ObjNo, Int32 vol) [0x00000] in <filename unknown>:0 

13.06.2020 12:49:27 |W|   at FF9Snd.FF9AllSoundDispatch (Int32 ParmType, Int32 ObjNo, Int32 Arg1, Int32 Arg2, Int32 Arg3) [0x00000] in <filename unknown>:0 

13.06.2020 12:50:16 |M| InitializeBattleText

13.06.2020 12:50:18 |E| [SoundData] Sound not found: 101

13.06.2020 12:50:19 |E| [SoundData] Sound not found: 101

13.06.2020 12:50:36 |E| Failed to load next scene.

13.06.2020 12:50:36 |E| System.ArgumentException: nextScene

13.06.2020 12:50:36 |E|   at Assets.Scripts.Common.SceneDirector.LoadNextScene () [0x00000] in <filename unknown>:0 
```

The only mod I have installed is the Moguri Mod (8.0.1).

EDIT: There is a section in the above log that has the same symbol as the Github code symbol. I edited that, and if you look in the above log for ""??" that part needs to be replaced with `.

**Comment by Tirlititi** [comment]
Without any mod, you can also have that bug. Someone on the Steam forum posted a the same kind of log (I remember the "Failed to load next scene [0x00000]" stuff) so it is the same bug with and without mod.

I don't know why invalid datas are sometimes loaded though.

**Comment by IFireflyl** [comment]
So it's a developer issue, not a mod issue. Do you think this is something that Memoria could fix in the future, or is it an absolute unknown as to how this issue occurs, and/or something that only the developer would be able to troubleshoot/correct?

**Comment by snouz** [comment]
There was an attempt to fix it there:
https://github.com/Albeoris/Memoria/pull/93/files
Diddn't fix it or not completely, apparently.

**Comment by IFireflyl** [comment]
It's literally the most annoying part of the game. If this isn't something that anyone wants to work towards then this can be closed, but if someone that has the know-how to dig into this I know a LOT of people would love to see a real fix for this. I wonder if something changed with that patch in April that might have messed with the previous fix attempt.

**Comment by Tirlititi** [comment]
Yes, that's definitely something we want to fix; Silicon Studio or Square Enix will likely never fix it themselves and Memoria already does several bug fixes.
Also, the speedrun community found that lowering the frame rate when entering battles seems to definitely fix the problem ([https://www.speedrun.com/ff9/thread/su1l8](https://www.speedrun.com/ff9/thread/su1l8)).

**Comment by snouz** [comment]
Interesting. So putting an fps cap during swirl/loading could fix it.

I checked a bit the above exception. Apparently, the variable SceneDirector.NextScene is an empty string when it arrives at LoadNextScene(). Maybe if we check that it's not empty and try to fill that variable again, or reload a previous function?

**Comment by IFireflyl** [comment]
For now I've tried setting the BattleSwirlFrames to 1, and in my in-game config I set the Skip Battle Camera setting to On. This results in a pretty quick load time still, and I'll see if that affects the black screen issue. It's so sporadic, though, so I'm not sure how much my test will help unless I get that random screen super quickly (in which case we would know for sure that what I changed did not make a notable difference).

**Comment by IFireflyl** [comment]
It looks like simply setting the BattleSwirlFrames to 1 was not enough to resolve whatever this issue is.

`14.06.2020 02:14:41 |W| [SoundLib] FF9SOUND_SNDEFFECTRES_RESTORE: slot: 1 is null!

14.06.2020 02:14:43 |W| [SoundLib] FF9SOUND_SNDEFFECTRES_RESTORE: slot: 1 is null!

14.06.2020 02:14:45 |W| [SoundLib] FF9SOUND_SNDEFFECTRES_SUSPEND: slot: 1 is null!

14.06.2020 02:14:45 |E| Failed to load next scene.

14.06.2020 02:14:45 |E| System.ArgumentException: nextScene

14.06.2020 02:14:45 |E|   at Assets.Scripts.Common.SceneDirector.LoadNextScene () [0x00000] in <filename unknown>:0 `

**Comment by LoveIsDarkness** [comment]
After fixing the black screen, I went through the floor of the game and did not catch a single black screen
[Graphics]
Enabled = 1
BattleFPS = 15
BattleSwirlFrames = 115

**Comment by snouz** [comment]
I got a bug report that it also sometimes crash AFTER a battle? Can other people confirm that?
