### ISSUE TITLE
Madain Sari Peeing Scene Bug

### ISSUE THREAD

**Issue by IFireflyl** [Albeoris/Memoria#138]
There is a scene in Madain Sari where Zidane and Vivi pee off a cliff. They're supposed to be facing the same direction, but instead it just shows them both looking at each other. A friend of mine was also able to replicate this bug. I'm not sure if it's a bug in the main game, or with Memoria, or with Moguri 8.0.1.

**Comment by snouz** [comment]
I tested it before my commit. The thing is in the original game, they are outside view, the camera is on eiko listening to them.

If I want to fix it, it means that this entire background will need to be narrow screen all the time.

Another way to fix it would be to program the script in p0data6 to change the positions/animations of characters, but I have no experience with that.
