### ISSUE TITLE
AMD cards: Widescreen disables "3D models" on open world

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#139]
"I assume that the WideScreen feature makes 3D models invisible on open world
if I set window ratio to 16:9 and WidescreenSupport = 1, 3D model is gone on open world
----------- DAYS LATER

I guess the 3D model disappearing issue might be caused by AMD card / driver or something.

I did nothing but just switched my graphic card from an AMD RX 580 to GTX 1080, 3D model appeared on open world"

**Comment by Minty123** [comment]
Same issue here. Graphic card is AMD R9 270x. Oddly enough the issue disappears for me when the resolution is set to 720p. Anything above + widescreen results in the models disappearing on the world map. If you need specific info/logs just let me know.

**Comment by snouz** [comment]
I have no idea if this is still happening. Since then there were a lot of patches, and AMD released new drivers.
