### ISSUE TITLE
Ending scene, the text just after eiko/cid in the elevator, screen is not black

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#144]
It should look like this:
https://youtu.be/g_5L-blpd5A?t=12063

Instead, you have the scene with a yellow tint, then a fadeout, then the screen light up again, without yellow tint.
![2020-06-28 16_57_02-FINAL FANTASY IX - Map_ 3006, Loc_ 187 Name_ KM_Fin du jeu](https://user-images.githubusercontent.com/9964576/86268056-eb5f5180-bbc7-11ea-9915-1ef8f2eb7739.png)

This should be on a black screen.

**Comment by LoveIsDarkness** [comment]
I have the same bug. Always present.
