### ISSUE TITLE
the launcher prevents certain options: Battle Speed : 1 and Hide Icons

### ISSUE THREAD

**Issue by RealUn2ken** [Albeoris/Memoria#149]
It seems that the new launcher defaults to either Battle Speed 2 which is turn based or 0 which completely disables the feature. 
setting the Battle Speed to 1 will be changed to 2 when the game is launched. 
[Battle]
Speed = 2 <- set to 2 or 0 only
I normally dont use the hide icons feature so i set it to 0 however even disabling  the features on the launcher the value us will be reset to one 

[TetraMaster]
Enabled = 1 <- cant be set to 0

if these were intended behaviours please close this issue . Thanks

**Comment by snouz** [comment]
Everytime you launch the game it overwrites? I'll correct that, it's my bad.

**Comment by RealUn2ken** [comment]
> Everytime you launch the game it overwrites? I'll correct that, it's my bad.

yup. let say for example if i set the memoria.ini setting to 1 .... when you launch the game its overwritten to 2. the only accepted value is either 0 or 2 at least for the battle speed.
