### ISSUE TITLE
Battle UI. 

### ISSUE THREAD

**Issue by PeanutReaper486** [Albeoris/Memoria#15]
A smaller, proper UI is sorely needed. The smartphone interface isn't efficient in this game's case. 

If changing the command window is troublesome, perhaps merely scaling it down could suffice. The character name list, with HP, MP, ATB, is also too widely spaced. Comparing it to the original PSX version is a stark contrast.

**Comment by GuyInDogSuit** [comment]
Agreed, this is severely needed.

The interface is really clunky.

**Comment by Francisco-Reis** [comment]
They changed it on PS4 new patch, but seems that PC version is forggoten.
In the PS4 version they fixed the missing death sound for monsters too. For PC owners such as me the monsters die in silence...

**Comment by Zer0Ph34r** [comment]
I'm working on making the UI look identical to the original minus the text font, but I am having issues actually building the project, if some one can help me fix the build errors (aka tell me how to get it running correctly) I should be able to fix the UI.

I'm using the work done by GDI in : https://steamcommunity.com/groups/ff-modding/discussions/13/1290690926876650747/
as a springboard.  He has it looking correct, but it has a bunch of bugs and only really works in some battles.  I think I have resolved the issues and improved the logic, but I haven't been able to test it.

**Comment by Zer0Ph34r** [comment]
I created a branch with all current changes to the UI in it under UI_Branch

Currently the UI size has been set to 69% and the enemy/party select panel has been removed. Work still needs to be done on the look of each panel.

There is and odd bug with the scrolling lists at this size that makes them disappear at the bottom as you scroll down, getting progressively worse as you scroll

**Comment by Albeoris** [comment]
Fixed by **TehMighty**
https://www.nexusmods.com/finalfantasy9/mods/11
