### ISSUE TITLE
Epitaph Enemy - Won't select clone

### ISSUE THREAD

**Issue by shanep2300** [Albeoris/Memoria#153]
Have Moguri mod installed so not sure if it's that but I'm in Oeilvert and when the Epitaph enemy creates a clone, I can select the clone in the menu, but the little hand pointer on the actual character doesn't move to the clone. No matter what's selected, all actions go directly to the Epitaph.

Only time the clone is actionable is when the Epitaph dies first.

**Comment by Albeoris** [comment]
![image](https://user-images.githubusercontent.com/4787832/104889676-99bdbf00-597f-11eb-9b49-8cee906100ed.png)

**Comment by Albeoris** [comment]
![image](https://user-images.githubusercontent.com/4787832/104891105-890e4880-5981-11eb-8efe-c23753a015b7.png)

**Comment by Albeoris** [comment]
![image](https://user-images.githubusercontent.com/4787832/104892856-b825b980-5983-11eb-97ed-96b7ae84beeb.png)
Fixed
