### ISSUE TITLE
Playstation Buttons

### ISSUE THREAD

**Issue by F-Lambda** [Albeoris/Memoria#157]
It would be great if there was an option to switch from the default Xbox button display to a Playstation button display.

**Comment by Tirlititi** [comment]
The Steam user gdi made a mod for that [here](https://steamcommunity.com/groups/ff-modding/discussions/13/350533172685612333/). With nowadays's Memoria, you would install it like that:
1) Download the two images: [Icon Atlas](https://imgur.com/oQVRU9w) and [Screen Button Atlas](https://imgur.com/F5CZB1T),
2) Put them in a sub-folder "PSXButtonMod/FF9_Data/EmbeddedAsset/UI/Atlas/" and rename them "Icon Atlas" (removing the ".png" extension of the image's name) and "Screen Button Atlas" respectively. Put that folder "PSXButtonMod" in FF9's directory.
3) Register the mod in "Memoria.ini": in section "[Mod] FolderNames", add "PSXButtonMod".

**Comment by Tirlititi** [comment]
cdb07e9 allows to install gdi's files from the launcher, easying the task.

**Comment by ArhumMK** [comment]
Sorry to reply to such an old post but gdi's mod only changes the face buttons but L/R/1/2, Select and Start are still xbox prompts. you can see it very clearly they're not changed in the Icon atlas file itself.

**Comment by faospark** [comment]
> Sorry to reply to such an old post but gdi's mod only changes the face buttons but L/R/1/2, Select and Start are still xbox prompts. you can see it very clearly they're not changed in the Icon atlas file itself.

there are several complete PS buttons themes  on Mog-addons 
https://www.nexusmods.com/finalfantasy9/mods/31

**Comment by ArhumMK** [comment]
> > Sorry to reply to such an old post but gdi's mod only changes the face buttons but L/R/1/2, Select and Start are still xbox prompts. you can see it very clearly they're not changed in the Icon atlas file itself.
> 
> there are several complete PS buttons themes on Mog-addons https://www.nexusmods.com/finalfantasy9/mods/31

Yes I had found the mog addons' button packs after that post, thanks. It would be better to remove gdi's PSX buttons mod from the Memoria Mod manager as it is obsoleted by now. 

On another side note, I have been attempting to take a crack at extracting the PS4 version of FF9 to rip out the atlas used for controller buttons as it seems the one used by Mog Addons is a recreation. No luck so far and the only images I've been able to rip out are textures for BG and 3D models.
![image](https://github.com/Albeoris/Memoria/assets/70807030/316d9541-5377-4551-80fa-2d3fcefb6cd0)
I've managed to isolate them to these files and using UABE shows they contain bundles but in a different naming format. Either the UI assets are in a different file format entirely or are not in these files. 

For a future version of Memoria, it would be nice to rip the controller atlases out of respective console releases of the game and have an option built into the launcher to select these button prompts.

**Comment by snouz** [comment]
> For a future version of Memoria, it would be nice to rip the controller atlases out of respective console releases of the game and have an option built into the launcher to select these button prompts.

I know there was the question of legality, that was a discussion at one point

Here's a discussion about that:
https://github.com/Albeoris/Memoria/issues/454
