### ISSUE TITLE
Impossible to beat Ozma when turn-based combat is on

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#159]
A user on the FFIX subreddit pointed that out.

https://en.reddit.com/r/FinalFantasyIX/comments/la2tqf/a_note_about_ozma/

"I think this happens because with normal ATB the game registers your turn in between animations, despite the speed stat. So if you click "attack" while Ozma is casting a spell your turn will follow up immediately (unless scripted event occurs, like Curaga). Which means he can't chain multiple commands at once even if he gots higher speed.

With turn based instead is all related to the speed stat. Like in FFX, if your speed is 255 you're basically GOD."

**Comment by Albeoris** [comment]
I think the easiest thing we can do is turn off turn based combat if any enemy has a speed of 255.

**Comment by Albeoris** [comment]
For now, I just added a check of the location. Thus, turn-based mode is disabled in the battle with Ozma.
