### ISSUE TITLE
Cursor Position Fails to Update

### ISSUE THREAD

**Issue by TallgeeseHeaven** [Albeoris/Memoria#16]
The cursor that is supposed to be above your character becomes "stuck" on the coordinates of the first scene exit you take, at least for me.

To be clearer, this includes the "hand" icon, the exclamation icon, and so forth.

If I restore the original Assembly-CSharp.dll the issue disappears.

**Comment by TallgeeseHeaven** [comment]
To clarify further, the cursor is in the correct position when you load the game, and becomes stuck when you do a screen transition. I realized that I never mentioned that.

**Comment by Albeoris** [comment]
Can you share the game log? output_log.txt from FF9_Data folder.

**Comment by TallgeeseHeaven** [comment]
Here you are.
[output_log.txt](https://github.com/Albeoris/Memoria/files/340788/output_log.txt)

**Comment by TallgeeseHeaven** [comment]
Here you go.
[output_log.txt](https://github.com/Albeoris/Memoria/files/340806/output_log.txt)

**Comment by Sefie1999AD** [comment]
I am having this same issue: the "here", "!" and "cards" cursors get stuck when you leave a screen. Screenshot and output_log.txt as attachments.
![cursor-bug](https://cloud.githubusercontent.com/assets/19685113/17650012/cf5a8fe8-624a-11e6-873c-8e77a35f2fef.png)
[output_log.txt](https://github.com/Albeoris/Memoria/files/417077/output_log.txt)

**Comment by Albeoris** [comment]
Will fix soon. Bug at EIcon.cs

**Comment by Albeoris** [comment]
Fixed.
