### ISSUE TITLE
No placeholder for some character names in the export text for language beside English

### ISSUE THREAD

**Issue by gundamftw** [Albeoris/Memoria#163]
In the English export text, the format of the dialog is like this

`"$0002_EVT_STARTUP_RYOTA_1_0051" = "{W105H2}{Baku}
“Here’s the plan!”";`

where `{Baku}` is a name placeholder, but for other languages like Japanese or Italian, the same line has no placeholder for the name:
`"$0002_EVT_STARTUP_RYOTA_1_0051" = "{W121H2}バクー
「今日の作戦の確認だっ!!";`

**Comment by Albeoris** [comment]
It is necessary to generate similar files for other languages:
https://github.com/Albeoris/Memoria/blob/main/Assembly-CSharp/Memoria/Assets/Text/Export/Fields/UsExportFieldCharacterNames.cs

And use it here:
https://github.com/Albeoris/Memoria/blob/main/Assembly-CSharp/Memoria/Assets/Text/Export/Fields/ExportFieldCharacterNames.cs
```
        private static ExportFieldCharacterNames Create(String localizationSymbol)
        {
            if (localizationSymbol == "US")
                return new UsExportFieldCharacterNames();

            return new ExportFieldCharacterNames();
        }
```
