### ISSUE TITLE
Adding a placeholder in the exported text dialogues for space bars at start of the line?

### ISSUE THREAD

**Issue by gundamftw** [Albeoris/Memoria#164]
In the exported text for the English dialogues, if the dialogue span over 2 lines, there will be a space at the start of the line beginning from the second line. Can we also have a placeholder to represent this space so we can modify the length?

**Comment by gundamftw** [comment]
Also, different languages will use different quoting around their dialogues. For example, Japanese will use `「` at the start while English will use `“` and `”` (may not show up correctly here). Can we also turn these into tokens?

**Comment by Albeoris** [comment]
> 
> 
> Also, different languages will use different quoting around their dialogues. For example, Japanese will use `「` at the start while English will use `“` and `”` (may not show up correctly here). Can we also turn these into tokens?

Do you want the export to use language specific quotes, or do you want Placeholder to be used instead?

**Comment by Albeoris** [comment]
> In the exported text for the English dialogues, if the dialogue span over 2 lines, there will be a space at the start of the line beginning from the second line. Can we also have a placeholder to represent this space so we can modify the length?

During export?

**Comment by gundamftw** [comment]
> > Also, different languages will use different quoting around their dialogues. For example, Japanese will use `「` at the start while English will use `“` and `”` (may not show up correctly here). Can we also turn these into tokens?
> 
> Do you want the export to use language specific quotes, or do you want Placeholder to be used instead?

Something like this

US
```
"$0002_EVT_STARTUP_RYOTA_1_0058" = "{W185H3}{UpperRightForce}{Offset 210,-80,0}{Cinna}
{quotestart}Break a leg, Marcus!
 ’Cause you’re playin’ the lead!{quoteend}";
```

JP
```
"$0002_EVT_STARTUP_RYOTA_1_0058" = "{W100H3}{UpperRightForce}{Offset 210,-80,0}シナ
{quotestart}頼むずらよ!
主役のマーカスさん!!{quoteend}";
```
The program will replace `quotestart` and `quoteend` with quotation depending on the language

**Comment by gundamftw** [comment]
> > In the exported text for the English dialogues, if the dialogue span over 2 lines, there will be a space at the start of the line beginning from the second line. Can we also have a placeholder to represent this space so we can modify the length?
> 
> During export?

Yes. I think the original purpose of this to align the lines. I have seen this done very nicely with Dragon Quest XI S PC Japanese version, where every line was perfectly aligned with the Japanese quotation mark in the first line. But in FF9 English, one space is not enough to align them.

**Comment by Albeoris** [comment]
> The program will replace quotestart and quoteend with quotation depending on the language
What is it for? Quotes and indents are part of the text. For the English version they are one, for the Japanese version they are different. Normally, you don't need to transfer text from Japanese to English or vice versa. 

In my opinion, it is more correct to remove quotes and indents from the text altogether, and insert them automatically during import, depending on the language. Then it makes sense.

**Comment by Albeoris** [comment]
> But in FF9 English, one space is not enough to align them.
If you need a quick fix, use Notepad++ to replace it. For example:

Find regex:
`^ ([^ ])` - a single space at the beginning of a line 

Replace to:
`{x4}$1` - 4 white-pixels + rest of the line

**Comment by gundamftw** [comment]
> > The program will replace quotestart and quoteend with quotation depending on the language
> 
> What is it for? Quotes and indents are part of the text. For the English version they are one, for the Japanese version they are different. Normally, you don't need to transfer text from Japanese to English or vice versa.
> 
> In my opinion, it is more correct to remove quotes and indents from the text altogether, and insert them automatically during import, depending on the language. Then it makes sense.

I'm fine with anything that makes the translation workflow easier. It would be better if there's setting to customize the quotation and indents.
