### ISSUE TITLE
game won't start after reinstalling without memoria mod "an error occurred while updating FF IX (missing executable)"

### ISSUE THREAD

**Issue by SmoKeFather** [Albeoris/Memoria#165]
the game won't start after reinstalling it without Memoria mod: "an error occurred while updating FF IX (missing executable)".

what can i do to get it to work?

**Comment by Zer0Ph34r** [comment]
When you uninstall a game, it often leaves behind certain files to make it easier to start the game the next time you install it.  look into "C:\Program Files (x86)\Steam\steamapps\common" and ensure that Final Fantasy IX is completely deleted after uninstalling it.

You can also often find additional files in "C:\Users\"username"\Documents\My Games", and "%USERPROFILE% \AppData\LocalLow\SquareEnix\FINAL FANTASY IX" (Note that AppData is usually a hidden folder, so you need to enter the view settings of File Explorer and click the "Show Hidden" tab)

After uninstalling the game, go to each location and delete everything there.  Once this is done, a fresh install will not have any files it can possible be in conflict with.

**Comment by SmoKeFather** [comment]
ok, deleted all of them. will try it now.

**Comment by SmoKeFather** [comment]
nope, the game still won't start. same error =(

**Comment by SmoKeFather** [comment]
i installed the game on another hard drive and i get the same error message. any suggestions?

**Comment by snouz** [comment]
Did you 'verify integrity of game files' in steam?

**Comment by SmoKeFather** [comment]
yes, of course.

**Comment by SmoKeFather** [comment]
i try to activate the launcher and this error appears:

![error](https://user-images.githubusercontent.com/74319758/114867432-1b917d00-9df5-11eb-9db4-4bf0689f08ef.PNG)

**Comment by snouz** [comment]
That's strange, but I wouldn't link it to Memoria, as 'verify integrity of game files' checks that all the files needed are there, and replaces any that isn't official. Are you launching it from steam itself? Have you tried moving it to drive C:/ ? Have you tried uninstalling and reinstalling ?
Maybe there's someone with a similar problem on the steam forum?

**Comment by SmoKeFather** [comment]
"Are you launching it from steam itself?" - did both. from steam and from the main directory.

"Have you tried moving it to drive C:/ ?" - installed it on C and after this on D. same problem.

" Have you tried uninstalling and reinstalling ?" - yes, many times.

"Maybe there's someone with a similar problem on the steam forum?" - no, that's why i am talking to the ppl whow actually are involved in memoria.

**Comment by Albeoris** [comment]
Just run the **Memoria.SteamFix.exe** as **Administrator** from the game directory.

**Or** delete the registry key manually: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FF9_Launcher.exe

**You were warned:**

> Now we will install a hook into your OS that will launch FF9_Launcher.fix instead of the FF9_Launcher.exe file. In this case, all integrity checks of the Steam file will complete successfully. Thus, this will solve the problem that some users have periodically disabled Steam Overlay functionality, and related features: achievements and controller support.&#13;&#10;&#13;&#10;However, be careful and DO NOT DELETE the game, its folder or the FF9_Launcher.fix file without first rolling back the changes. Otherwise, the hook will remain in your system, and after a new installation of the game, you will not be able to launch it. You can roll back the changes in the launcher or manually by running Memoria.SteamFix.exe in the game folder.&#13;&#10;&#13;&#10;Are you sure you still want to continue?
