### ISSUE TITLE
Turn based combat breaks regen and other time-interval statuses

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#167]
"I'm playing it right now with moguri mod + alternate fantasy. About the turn based and Ozma, is actually a known bug. For my part, I discovered that turn based broke a few things. Right now I remember, for example, regen. The characters will just not refills any HP. I think any "time intervals" statuses were just broken. It took me too much to realize it 😂"

https://en.reddit.com/r/FinalFantasyIX/comments/mxqqqc/has_anyone_played_the_moguri_mod_with_turn_based/gvrbyu0/?context=3

**Comment by Albeoris** [comment]
I definitely remember that regeneration, poison and other periodic status effects worked correctly. Need to check.

**Comment by Albeoris** [comment]
Just checked it out. Everything works correctly in the latest version in turn-based combat mode. 

![image](https://user-images.githubusercontent.com/4787832/125433330-b92b917a-0e98-4a31-94a0-ba0ff309a23f.png)
