### ISSUE TITLE
Oglop Cid in the Desert Palace

### ISSUE THREAD

**Issue by DefenderLinus** [Albeoris/Memoria#174]
I have played this game more times than I care to count.  It is my all-time favorite, and there is very little I would ever want to change...except this.  The mini game in the Desert Palace where you are playing as Oglop Cid and trying to sneak past a Hedgpog Pie is a freaking nightmare and I hate it.  It should be nerfed or even skip-able, it is that bad.

**Comment by snouz** [comment]
When I was working on Moguri, there was one point when I had to beat this moment several times to access the scene just after.

Anyway I agree.
