### ISSUE TITLE
Fix map position like in PSX

### ISSUE THREAD

**Issue by martin-braun** [Albeoris/Memoria#179]
It would be nice to have a way to fix the map and treasure hint position into the right bottom corner how it was back in the days: 

![maxresdefault.jpg](https://i.ytimg.com/vi/1nL1LblgVyI/maxresdefault.jpg)

This is just garbage, blocking the view on the right side too much: 

![ChocographLoc09.jpg](https://static.wikia.nocookie.net/finalfantasy/images/d/d3/ChocographLoc09.jpg/revision/latest?cb=20210320192641)

The card hint is also blocking the view ahead, it was way better in the PSX version. 

Thank you in advance. :)

**Comment by FlameHorizon** [comment]
I'm having hard time understanding how game knows, where to draw a mini map. This is what I have found within the code so far

https://github.com/Albeoris/Memoria/blob/aab9c563398c562a5843dda1a57c6d1b67517865/Assembly-CSharp/Global/World/WorldHUD.cs#L1235

But I have no idea where the value for `miniMapWidget` are coming from. Seems like Panel just _exists_ and _knows_ these values.

https://github.com/Albeoris/Memoria/blob/bb5ae2ce7aef96fa20d2849fbd24518647799304/Assembly-CSharp/Global/World/WorldHUD.cs#L1300

**Comment by Tirlititi** [comment]
These are `MonoBehaviour` classes: parts of the construction and initialization is done through external assets. We can modify/move/scale them in C# code during awakening without touching the (serialized) asset files.

For the position of the minimap and the chocograph caption, I wrote two lines that recenter them more like the PSX version but I commented those lines because surely it would be better to have a complete UI modding system and not tweak things by hand. If you uncomment these [two](https://github.com/Albeoris/Memoria/blob/aab9c563398c562a5843dda1a57c6d1b67517865/Assembly-CSharp/Global/World/WorldHUD.cs#L1273) [lines](https://github.com/Albeoris/Memoria/blob/aab9c563398c562a5843dda1a57c6d1b67517865/Assembly-CSharp/Global/World/WorldHUD.cs#L1274), that will be enough for a hotfix.

**Comment by martin-braun** [comment]
Combining TehMighty's work with this would be exceptionally good, his work aims to bring back the UI experience from PSX already. 

So yes, these panels are placed in the Unity editor and not from within a MonoBehavior, but its local position can be shifted, love to see that. If it takes ages to get a collaboration, exposing those values to Memoria.ini for such panel adjustments would already help. Something like

```ini
chocographAndMapOffsetY = 0
```

**Comment by FlameHorizon** [comment]
@Tirlititi uncommenting these two lines indeed changes the location of chocograph map but not the minimap. See below:

![image](https://user-images.githubusercontent.com/23423558/148284240-0ef14135-a323-45b1-81ce-646d5cbdcd5d.png)

Yet to understand why.

**Comment by martin-braun** [comment]
@FlameHorizon I cannot test right now, but could you try something like: 

```cs
float chocographAndMapOffsetY = 300f;
this.ChocographLocationPanel.transform.localPosition += new Vector3(0f, chocographAndMapOffsetY, 0f);
this.miniMapWidget.transform.parent.localPosition += new Vector3(0f, chocographAndMapOffsetY, 0f);
```

My hope is the values are set before Awake, so it should work to just shift using addition. Fine-tune `chocographAndMapOffsetY`. I also think you could instead get the current resolution and set absolute values instead.

**Comment by FlameHorizon** [comment]
With your code snippet @martin-braun I was able to move chocograph map way up. See top right corner.

![image](https://user-images.githubusercontent.com/23423558/148369405-114c9183-ec4e-4a77-a570-7256e60e3974.png)

With this snippet I was able to move chocograph map a bit closer to the minimap.
`this.ChocographLocationPanel.transform.localPosition += new Vector3(x:0f, y:-100f, z:0f);`
![image](https://user-images.githubusercontent.com/23423558/148369999-c60d01b6-4b55-43e6-9593-193dd843d7a0.png)

But the minimap itself wouldn't budge. Any suggestions why?

**Comment by martin-braun** [comment]
@FlameHorizon Very nice so far. If those values make no sense, I think a parent object is rotated in a specific way, so shifting the local position will happen on a rotated orientation. What you could try is to modify `position` instead of `localPosition`, which will update the transform within the world space and not within the parent transform.

I think this will give better results.

**Comment by FlameHorizon** [comment]
Thanks for your help. Appreciate it. Unfortunately, `position` these values which I really know what they mean. I'm not really familiar with Unity overall...

![image](https://user-images.githubusercontent.com/23423558/148977407-c552a16a-fc4f-4e1f-8f5c-ab7d2516d8d0.png)

I'm going to make a PR with Chocobograph hotfix for now as it seems to an improvment.

**Comment by martin-braun** [comment]
I really appreciate your help, I think it's an improvement, although I would get that far to say that it needs to be configured in the Memoria.ini, perhabs with X and Y for map and chocograph. Anything other is probably not welcome to everyone. It's always best to require opt-in by the user and it would be even better to give some more control to the user.

Thanks a lot.

Regarding the x, y and z, I'm not very sure either. Maybe @Tirlititi can give some advise here?

**Comment by FlameHorizon** [comment]
@martin-braun I understand your point. At the moment, at least us two, struggle to understand how coordinates works in case of chocograph, we also do not know how to move a minimap. IMO, there is nothing which should be exposed to user, by ini file before we understand how these values and minimap works.

**Comment by Albeoris** [comment]
Hey guys! You can press Ctrl+Alt+Shift+F12 in-game to run TCP-server. Than run Memoria.Client.exe and connect.

This is a simple explorer of objects on the game scene, which will allow you to find the desired object and experiment with its coordinates. Any improvements are welcome.

**Comment by Albeoris** [comment]
I found a much cooler thing! 

https://github.com/sinai-dev/UnityExplorer

![image](https://user-images.githubusercontent.com/4787832/150216842-bfa6b5d6-2870-4a44-b970-554bbe3cecf4.png)

**Comment by FlameHorizon** [comment]
Please close this issue as PR #187 is approved.
