### ISSUE TITLE
Rotation / Perspective cheats

### ISSUE THREAD

**Issue by martin-braun** [Albeoris/Memoria#180]
What are those doing, please? I miss a cheat page in the Wiki to learn about those.

**Comment by Tirlititi** [comment]
They surely have no real use. In [CallBoosterButtonFuntion](https://github.com/Albeoris/Memoria/blob/main/Assembly-CSharp/Global/SettingsState.cs#L255), they simulate L2/R2 buttons, which are camera control on the World Map.

**Comment by martin-braun** [comment]
Thanks, then I wonder why they were enabled by default. I suspected they fix something obvious, so it's quite surprising that you say they have no real use. I can disable those, safely you say?

**Comment by Tirlititi** [comment]
They are "enabled" but there is no way to trigger them. They don't have a button like the others neither in ConfigUI nor as key triggers. They are most likely remnants of debugging tools.
