### ISSUE TITLE
Disable stat grow

### ISSUE THREAD

**Issue by martin-braun** [Albeoris/Memoria#181]
We all know that leveling up will modify the stats of the character depending on what he/she is wearing, thus requiring to do the Level 1 challenge to max out stats using the best equipment on the end of the game (which would also cause over-powered characters for the game). I would prefer to have a hack to disable such stat grow altogether ending up with the weakest stats possible on level 99 no matter what I wear while leveling up. This would eliminate the sense of "I could've been stronger/better/different" while introducing a harder end-game challenge, because of reduced overall stats.

The closest thing that I came across was the [No Equipment Bonus Mod](https://www.nexusmods.com/finalfantasy9/mods/24), but this will attempt to modify this behavior by setting the grow-causing stats to 0 on all equipment, leading to the fact that it's almost useless to pick specific equipment, except for side-effects and ability learning.

Instead, I can imagine having a hack in Memoria that can be configured like this: 

```ini
[Hacks]
Enabled=1
NoStatGrow=1
```

This would disable stat grow when leveling up, nothing more, nothing less. Equipment bonus should remain as is.

Can this be implemented please?

**Comment by Tirlititi** [comment]
That is already implemented through ```[Battle] XXXStatFormula```.

```
[Battle]
Enabled=1
SpeedStatFormula = Min(50, SpeedBase + Level / 10) ; removed  "+ (SpeedBonus / 32)"
StrengthStatFormula = Min(99, SpeedBase + Level * 3 / 10) ; removed  "+ (StrengthBonus / 32)"
MagicStatFormula = Min(99, SpeedBase + Level * 3 / 10) ; removed  "+ (MagicBonus / 32)"
SpiritStatFormula = Min(50, SpeedBase + Level * 3 / 20) ; removed  "+ (SpiritBonus / 32)"
```

**Comment by martin-braun** [comment]
@Tirlititi Wow thanks, now it makes sense. So basically, instead of preventing the grow of the bonus, the formula to calculate stats is changed to exclude the bonus that has been grown though level ups. 

Is `SpeedBase` on all rows a typo? Shouldn't it be like so then?

```
[Battle]
Enabled=1
SpeedStatFormula = Min(50, SpeedBase + Level / 10) ; removed  "+ (SpeedBonus / 32)"
StrengthStatFormula = Min(99, StrengthBase + Level * 3 / 10) ; removed  "+ (StrengthBonus / 32)"
MagicStatFormula = Min(99, MagicBase + Level * 3 / 10) ; removed  "+ (MagicBonus / 32)"
SpiritStatFormula = Min(50, SpiritBase + Level * 3 / 20) ; removed  "+ (SpiritBonus / 32)"
```

**Comment by Tirlititi** [comment]
That was a typo yes, thanks. Fixed it for reference.
