### ISSUE TITLE
AutoPotionOverhealLimit will not respect Chemist support ability

### ISSUE THREAD

**Issue by martin-braun** [Albeoris/Memoria#182]
Chemist doubles the effectiveness of Potions, Hi-Potions and Ethers, but `AutoPotionOverhealLimit = 0` will still cause to trigger a Potion when only 150 HP have been depleted. It should take the Chemist support ability into account when it's enabled.

**Comment by FlameHorizon** [comment]
Currently [Auto Potion Ability](https://finalfantasy.fandom.com/wiki/Auto-Potion_(ability)#:~:text=Final%20Fantasy%20IX-,Auto%2DPotion,-is%20a%20support) has its effect when target has less HP than MAX HP - 150. You would like to include a case, where Auto Potion Ability has its effect when target has MAX HP - 300 if character has [Chemist](https://finalfantasy.fandom.com/wiki/Item_Lore#:~:text=Quezacotl%27s%20Card%20Mod.-,Final%20Fantasy%20IX,-The%20support%20ability) enabled. Is that right?

**Comment by martin-braun** [comment]
> Currently [Auto Potion Ability](https://finalfantasy.fandom.com/wiki/Auto-Potion_(ability)#:~:text=Final%20Fantasy%20IX-,Auto%2DPotion,-is%20a%20support) has its effect when target has less HP than MAX HP - 150. You would like to include a case, where Auto Potion Ability has its effect when target has MAX HP - 300 if character has [Chemist](https://finalfantasy.fandom.com/wiki/Item_Lore#:~:text=Quezacotl%27s%20Card%20Mod.-,Final%20Fantasy%20IX,-The%20support%20ability) enabled. Is that right?

Correct. 👍🏻

**Comment by FlameHorizon** [comment]
After looking into code I saw that **Auto Potion** is used whenever character is damaged. Value of that damage does not matter, it can be even 1, **Auto Potion** will be triggered. 

Another edge case to think about is, if character loses 500 HP out of 1000, and only **Hi-Potion** (base heal of 450) is available, then (with new Chemist logic) **Auto Potion** will be triggered only if character loses 900 HP or more which it isn't a situation which should be allowed. In that situation character should use any potion is available regardless of HP loss.
