### ISSUE TITLE
60fps Menus

### ISSUE THREAD

**Issue by hyperspeedgx** [Albeoris/Memoria#19]
Those menus looks bad at 30fps, there is a reason why devs have put the menus at 60fps indepdent of the ingame fps, it looks much better and fun to navegate.

The ps1 ver. runs the menus at 60fps (on inventory menu and battle menu too) so i would love to see it on the PC ver.

**Comment by Albeoris** [comment]
There is no animation. Can you explain the difference?

**Comment by hyperspeedgx** [comment]
Well, can you just change it to 60fps to smooth the menus? I mean put the menus at 60fps while keep normal fps on others parts, like the ps1 ver. does.

Here a sample of 60fps menus and battle menus running the PS1 ver. so you can see what i'm talking about. ;) Do note how smooth the menu is and the battle menu window too.
https://youtu.be/16A4G19Bx8U


This is how the fps works on the ps1 ver.

Main Menu and the game invenotry menu : 60 fps
World Map enviroment : 20 fps 
Running Around Areas [cities, or other places for example evil forest] : 30 fps

Battles:
Start of the battle when the camera is doing a circle around spawning characters and mobs : 15 fps
The actual batlle sequences when i can do actions (aka the battle menu window) : 60 fps
End of a batlle when we can see our winning party "win poses" : 15 fps
Movies [rendered ones not the game engine cutsenes]: 15 fps

**Comment by hyperspeedgx** [comment]
any updates on this?

See how smooth the menus on ps1 is on the video above? That's why I can wait to have this on the PC ver. :)

**Comment by Albeoris** [comment]
Not yet. :)

**Comment by Albeoris** [comment]
We can easy to do that but it's not what you want.

Unlike the PSX-version of the game, another panel is used here when scrolling. Therefore, before we can increase FPS in the menu, we need to change this panel so that it can smoothly scroll rather than jump from one element to another.

**Comment by GuyInDogSuit** [comment]
I see what he means, in the PC version it's a bit jerky.

**Comment by Albeoris** [comment]
It is necessary to completely change the GUI. Not feasible without additional community support.
