### ISSUE TITLE
Automatically pull resources from Atlas or Sprites folder

### ISSUE THREAD

**Issue by LoveIsDarkness** [Albeoris/Memoria#191]
Please enable these resources for automatic loading from the Sprites folder.
Similar to how the "Chocograph Atlas" file is picked up from the FINAL FANTASY IX\StreamingAssets\UI\Atlas folder

resources\embeddedasset\ui\sprites\us\title_world_forgotten_shadow_us
resources\embeddedasset\ui\sprites\us\title_world_forgotten_us
resources\embeddedasset\ui\sprites\us\title_world_lost_shadow_us
resources\embeddedasset\ui\sprites\us\title_world_lost_us
resources\embeddedasset\ui\sprites\us\title_world_outer_shadow_us
resources\embeddedasset\ui\sprites\us\title_world_outer_us
sharedassets2\embeddedasset\ui\sprites\us\title_world_mist_shadow_us
sharedassets2\embeddedasset\ui\sprites\us\title_world_mist_us
sharedassets2\embeddedasset\ui\sprites\gameover

Also, please load textures from Tetra Master, I managed to find only one file from which only a few words cling, the rest cling from somewhere else. All this is necessary for a complete translation of the game.

**Comment by snouz** [comment]
@Tirlititi isn't it something already implemented since then?

**Comment by LoveIsDarkness** [comment]
> @Tirlititi isn't it something already implemented since then?
Yes, the entire files for translating textures are not pulled out, only a few are pulled out. I was able to get the files described above only through Hades. I don’t know how to make them work in Memoria after translation. I tried to create folders following the path to the file, but I couldn’t get them to work in the game.

**Comment by Tirlititi** [comment]
That is implemented. I just double-checked it and custom textures can be used. For example, place a PNG texture using that path:
```{ModFolder}/FF9_Data/EmbeddedAsset/UI/Sprites/US/title_world_outer_us```
Then that texture will be used as the title when entering the Outer Continent for the first time.

Note that:
1) You need to use the same texture path / filename as the asset in the archive, so you must NOT have a ``.png`` extension for your custom texture,
2) That doesn't work with the ``[Import] Graphics`` option, only mod folders. As always, mods should be made using [mod folders](https://github.com/Albeoris/Memoria/wiki/Mod-folders), not Export/Import options. That applies to translation mods as well!

**Comment by LoveIsDarkness** [comment]
> That is implemented. I just double-checked it and custom textures can be used. For example, place a PNG texture using that path: `{ModFolder}/FF9_Data/EmbeddedAsset/UI/Sprites/US/title_world_outer_us` Then that texture will be used as the title when entering the Outer Continent for the first time.
> 
> Note that:
> 
> 1. You need to use the same texture path / filename as the asset in the archive, so you must NOT have a `.png` extension for your custom texture,
> 2. That doesn't work with the `[Import] Graphics` option, only mod folders. As always, mods should be made using [mod folders](https://github.com/Albeoris/Memoria/wiki/Mod-folders), not Export/Import options. That applies to translation mods as well!

Thanks a lot. I tried to put the file without its extension .png, it didn’t work for me, maybe I didn’t specify something correctly in the path. But the Memoria mod itself does not unpack the entire texture files into folders. It unpacks some Atlas files, and the title screen from the UI, gameover files,
I had to get tetra master and continent name files using HadesWorkshop.
Due to the fact that I was getting files through another program, I didn’t know how to get Memoria to pick up these files, I didn’t know exactly where to put them, or what folders to create for this.
With the title screen files, the Chocobo treasure files, and the item file, I was able to get Memoria to hook them. But with the halyards listed above,
Memoria didn't pick them up. And I don’t know where the Tetra Master files are at all, because the game strangely picks them up, there are several identical textures and it picks them up selectively, the game takes something from one picture, and something the game takes from another, similar picture.

**Comment by LoveIsDarkness** [comment]
mod folders,...
I tried to do this a long time ago, over the years you have added a lot of new things to Memoria. If now there is a special mod folder through which you can pick up many files, that would be cool.
