### ISSUE TITLE
Some adjustements about SFX Rework (on Sequence.cs)

### ISSUE THREAD

**Issue by DV666** [Albeoris/Memoria#193]
Hi everyone ! 

I am currently working on a second mod fixing almost all files sounds from the game (I replaced more than 1500 files.. one by one... yeah that's a lot ^^').

And during my few tests, I found some small things to fix in the sequence.cs for the last Memoria build (after that, these are only suggestions of course!).

### Stellar_Circle_5 (ef245) :
```
// Shared sequence of SFX Stellar_Circle_5

PlaySound: Sound=1843
PlaySound: Sound=1843
PlaySound: Sound=1843
Wait: Time=50
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=24
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=8
```
I noticed that the file uses the same sound file 3 times, so I propose the following modification: 

```
// Shared sequence of SFX Stellar_Circle_5

PlaySound: Sound=1843
PlaySound: Sound=1844
PlaySound: Sound=1845
Wait: Time=50
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=24
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=8
```
### Matra_Magic (ef088) :
```
// Shared sequence of SFX Matra_Magic

SetBackgroundIntensity: Intensity=0.5 ; Time=20 ; HoldDuration=82
Wait: Time=14
PlaySound: Sound=1803
PlaySound: Sound=1804
PlaySound: Sound=1805
Wait: Time=44
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=12
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=12
SetBackgroundIntensity: Intensity=1 ; Time=8
```

I suggest to remove the wait time at the begin of the file otherwise the spell starts out of sync with the animation.

```
// Shared sequence of SFX Matra_Magic

SetBackgroundIntensity: Intensity=0.5 ; Time=20 ; HoldDuration=68
PlaySound: Sound=1803
PlaySound: Sound=1804
PlaySound: Sound=1805
Wait: Time=44
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=12
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=12
SetBackgroundIntensity: Intensity=1 ; Time=8
```

PS: Do not forget also to adjust the time for the change of intensity of the background or it will cause problems ^^

### Pyro (ef159) :

```
// Shared sequence of SFX Pyro

PlaySound: Sound=575
Wait: Time=12
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=22
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=33
```

This one is quite strange because according to the specialeffectmetadata.txt, there are 3 sound files:

```
	"159": [
      "Sounds03/SE50/se500118",
	  "Sounds03/SE50/se500117",
      "Sounds03/SE50/se500116"
    ]
```

However, se500118 didn't exist in the game... so i suggest to edit the file like this : 

```
// Shared sequence of SFX Pyro

PlaySound: Sound=584
PlaySound: Sound=575
Wait: Time=12
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=22
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=33

```

### Bahamut__Short (ef405) :
```
// Shared sequence of SFX Bahamut__Short

SetBackgroundIntensity: Intensity=0.5 ; Time=4 ; HoldDuration=19
ShowMesh: Char=AllPlayers ; Enable=False ; IsDisappear=True
Wait: Time=3
PlaySound: Sound=2271
PlaySound: Sound=2272
PlaySound: Sound=2273
PlaySound: Sound=2274
Wait: Time=14
PlaySound: Sound=2277
PlaySound: Sound=2278
PlaySound: Sound=2275
PlaySound: Sound=2276
Wait: Time=2
SetBackgroundIntensity: Intensity=0 ; Time=0 ; HoldDuration=12
Wait: Time=12
SetBackgroundIntensity: Intensity=0.6796875 ; Time=12 ; HoldDuration=81
Wait: Time=47
StopSound: Sound=2273
StopSound: Sound=2274
StopSound: Sound=2277
StopSound: Sound=2278
StopSound: Sound=2275
StopSound: Sound=2276
Wait: Time=5
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=12
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=17
SetBackgroundIntensity: Intensity=1 ; Time=12
ShowMesh: Char=AllPlayers ; Enable=True ; IsDisappear=True
ShowMesh: Char=AllPlayers ; Enable=True ; Time=12
```

In this one, the sound is cut off abruptly by the StopSound function, so I suggest placing them either at the end of the file (or removing them entirely) :

```
// Shared sequence of SFX Bahamut__Short

SetBackgroundIntensity: Intensity=0.5 ; Time=4 ; HoldDuration=19
ShowMesh: Char=AllPlayers ; Enable=False ; IsDisappear=True
Wait: Time=3
PlaySound: Sound=2271
PlaySound: Sound=2272
PlaySound: Sound=2273
PlaySound: Sound=2274
Wait: Time=14
PlaySound: Sound=2277
PlaySound: Sound=2278
PlaySound: Sound=2275
PlaySound: Sound=2276
Wait: Time=2
SetBackgroundIntensity: Intensity=0 ; Time=0 ; HoldDuration=12
Wait: Time=12
SetBackgroundIntensity: Intensity=0.6796875 ; Time=12 ; HoldDuration=81
Wait: Time=52
EffectPoint: Char=AllTargets ; Type=Effect
Wait: Time=12
EffectPoint: Char=Everyone ; Type=Figure
Wait: Time=17
SetBackgroundIntensity: Intensity=1 ; Time=12
ShowMesh: Char=AllPlayers ; Enable=True ; IsDisappear=True
ShowMesh: Char=AllPlayers ; Enable=True ; Time=12
StopSound: Sound=2273
StopSound: Sound=2274
StopSound: Sound=2277
StopSound: Sound=2278
StopSound: Sound=2275
StopSound: Sound=2276
```

### FF9Snd.cs (ff9battleSoundWeaponSndEffect02) 

This one has nothing to do with the SFX Rework and is something originally present in the game: one thing that annoys me a bit is that the sound of Zidane's thief sword uses the same sound file as Marcus and Frank.

```
private static Int16[,] ff9battleSoundWeaponSndEffect02 = new Int16[,]
	{
		{   // Zidane Dagger
			899,
			21
		},
		{   // Zidane Sword Thief
			900,
			63   <=========== The issue is here !
		},
		{   // Vivi
			904,
			22
		},
		{   // Dagga with Rod (long hair)
			904,
			22
		},
		{   // Dagga with Racket (long hair)
			906,
			898
		},
		{   // Dagga with Rod (short hair)
			904,
			22
		},
		{   // Dagga with Racket (short hair)
			906,
			898
		},
		{   // Steiner 1
			902,
			70
		},
		{   // Steiner 2
			902,
			70
		},
		{   // Quina
			901,
			20
		},
		{   // Eiko with Flute
			904,
			22
		},
		{   // Eiko with Racket
			906,
			898
		},
		{   // Freyja
			901,
			20
		},
		{   // Amarant
			905,
			897
		},
		{  // Cinna
			900,
			22
		},
		{  // Markus
			902,
			63
		},
		{  // Blank
			902,
			63
		},
		{  // Blank (Pluto Armor Knight)
			902,
			63
		},
		{  // Beatrix
			900,
			70
		}
	};
```

So I suggest replacing the ID with something else... I was thinking of ID number 9 (Sounds02/SE01/se010002), which doesn't seem to be used (maybe ?).

For my Trance Seek mod, I created an another ID to fix this but I wanted the next Memoria build to have the ID changed to make things easier :)

This way, it would be much easier for me to propose a correction of this sound with my future fix sound mod ^^ I don't know what you think... but anyway, this ID 63 has nothing to do here. (I have looked at the sound files in the SE01 folder but I can't find anything conclusive that could be Zidane's thief sword.)

And... that's it! Well, these are just a few adjustments I wanted to share with you but if I find more, I'll let you know on this post :)

**Comment by Albeoris** [comment]
Hi You did a great job. It would be great to see videos before and after the changes, so that people who are not immersed in SFX understand what has been changed.

**Comment by DV666** [comment]
No problem ! Here you go ^^ : https://www.youtube.com/watch?v=ThrCzEOemoU

You can find each spell I propose to modify (compared in 3 different situations) :
- SFX Rework Classic (without modifications)
- SFX Rework modified (especially on the sequence.cs)
- SFX Rework modified + my fix sound (A gift from me ! :p but it's mostly to explain the last part !)

And in the last part, explanation + suggestion about the thief's sword.

**Comment by Albeoris** [comment]
In my opinion, this is amazing work.

@Tirlititi , @snouz , @FlameHorizon , what are you think?

**Comment by FlameHorizon** [comment]
New SFXs sound better to me.

**Comment by Tirlititi** [comment]
Awesome. I think Bahamut's sound is best fixed without stopping the sound at all. I don't know about Zidane's thief sword.

**Comment by DV666** [comment]
I'm glad you like my little adjustments :D I haven't tested all the spells yet ^^ I'll see if I can find more as I go along with my mod.

> I think Bahamut's sound is best fixed without stopping the sound at all.

Agree ! Besides, it's the only spell that uses the "StopSound" function.

> I don't know about Zidane's thief sword.

That's why we should see which sound file is available for this weapon : I'm almost sure that there is one that is not used... but which one ?

Anyway, it's not normal to use this ID 63 in the ff9battleSoundWeaponSndEffect02 for this weapon, it's a mistake from them as the bug of the Choco's beak imo ^^

**Comment by Albeoris** [comment]
@DV666 , feel free to send pull requests. :)

**Comment by DV666** [comment]
I'm not sure how it works to pull requests but I'll try to do that this afternoon ^^ (because I've found two other things)

**Comment by snouz** [comment]
Closing as it is done in [#194](https://github.com/Albeoris/Memoria/pull/194)
