### ISSUE TITLE
Crash in Movie Gallery watching last 3 cutscenes on last page

### ISSUE THREAD

**Issue by AaronMT** [Albeoris/Memoria#195]
Hello,

I have no idea if this is a known longstanding issue (please close this and reference the issue if so), but going into the Movie Gallery and watching the last few cutscenes causes a crash to desktop. Running [v2021.11.17]. Happy to provide any logs if need be.

If this is a known issue, is there a workaround?

**Comment by snouz** [comment]
Hi, by the way, were you using Moguri at the time?

**Comment by AaronMT** [comment]
Yes. I don't have the install anymore nor logs or anything to help out here if need be unfortunately. Maybe this is fixed now?

**Comment by snouz** [comment]
This is very probably due to this: https://github.com/Albeoris/Memoria/pull/282

Since this is fixed for future version, I'm closing this, thanks for the response : )
