### ISSUE TITLE
Card limit

### ISSUE THREAD

**Issue by Mirolex** [Albeoris/Memoria#2]
Card limit should be raised from 100 to 200 to allow collecting all cards more comfortable. Since game do not allow player to play after max number are reached you are forced to discard it after each round.

If patch uninstalled all ovenumbered cards should be deleted.

**Comment by Albeoris** [comment]
**First look:**
JsonParser
QuadMistDatabase
BattleResultUI
QuadMistGame
QuadMistUI

**Comment by Albeoris** [comment]
I don’t feel like doing it, as this will break the cloud saving.
