### ISSUE TITLE
Voice Acting MOD pitch of OGG files while in-game

### ISSUE THREAD

**Issue by ptrschr** [Albeoris/Memoria#207]
Found in: https://github.com/Albeoris/Memoria/tree/v2022.04.29

How to reproduce?:
Follow instructions given at https://github.com/Albeoris/Memoria/wiki/Voice-acting-system

Description:
OGG files are played like mentioned in the instructions, but Playback in-game seems to be pitched/fast-forwarded, but original file in mod directory sounds as it should.

**Comment by barkermn01** [comment]
I think I know what this is, seem to have lost a commit / fix, I will get it in as soon as I can and submit PR

**Comment by barkermn01** [comment]
@ptrschr would you mind providing me with your `.ogg` and your `.akb.bytes` as a test it might just be that you're running an out-of-date version (or you might need to build the source version) of but I will double-check it, because the pitch (which also speeds up playback) is set to `0.5f` which if i remember correctly is correct but i just want to check with your files

**Comment by barkermn01** [comment]
But also think we need to update the wiki because the Voice Acting system does support in battle audio now so i will get that Sorted out :D

**Comment by ptrschr** [comment]
@barkermn01 sure see my test files attached to this post.
These `.akb.bytes` files are generated using latest Memoria master branch build:

https://github.com/Albeoris/Memoria/tree/v2022.04.29 build

Sure I would be glad if documentation about adding the documentation for battles.

[VoiceMod.StreamingAssets.Assets.Resources.Sounds.Voices.GR.2.zip](https://github.com/Albeoris/Memoria/files/9338479/VoiceMod.StreamingAssets.Assets.Resources.Sounds.Voices.GR.2.zip)

**Comment by barkermn01** [comment]
Documentation updated might need a little clean-up @Tirlititi but everything that should be needed is added in there.

**Comment by barkermn01** [comment]
@ptrschr this seems to be working for me, both the OGG and the in game version seems to be working and matching sounds but they do sound proccessed alot in my audio player is that deliberate or is your exporter messing them up? what software are you using to export to OGG files?

**Comment by ptrschr** [comment]
@barkermn01 fine so far, for them I was using an online converter for quick testing of the mod.

These files do sound like this, as they are created using deep fake AI TTS.

**Comment by barkermn01** [comment]
okies, i think i found an issue that might cause this your ogg exporter is exporting at 32000Hz Mono, they should be exported at 44100Hz mono,

**Comment by ptrschr** [comment]
@barkermn01 Okay thanks for advice! I will check this out later.

**Comment by barkermn01** [comment]
Well if the online system is unable to export at that format you can use Audacity to output at that format, i have personally tested exported OGG's at thoes setting from Audacity and Adobe Audition.

**Comment by barkermn01** [comment]
@ptrschr any update? I.E did that fix the issue and this can be closed?

**Comment by ptrschr** [comment]
@barkermn01 no updates yet I was waiting for the corresponding PR which would solve the issue to test it.

**Comment by barkermn01** [comment]
There is no PR yet wondering if the 441000Hz export fixes it because if the engine stuff is saying a 3200Hz should be run at 44100Hz it's going to be playing the audio ~28% faster than it should/

**Comment by ptrschr** [comment]
Understood, thanks for explanation.
I will test it out later and inform you asap.

**Comment by ptrschr** [comment]
@barkermn01  Thanks for your patience.
With no Memoria updates performed I removed all .bytes files and replaced my OGG files with ones converted to 44100Hz as suggested.

Sadly i got the same result.
See attached files (.bytes, OGG and source WAV) for reference.

[44100Hz.zip](https://github.com/Albeoris/Memoria/files/9365111/44100Hz.zip)

**Comment by barkermn01** [comment]
@ptrschr I'm not entirely sure what you're experiencing, I have just tried testing this by screen capping the game as it plays the audio and comparing them in OBS (hard because the game has background sounds) but for the most part, they line up close enough that there is no noticeable difference, (talking hundredths of a second)

https://user-images.githubusercontent.com/37368/185213390-c4794077-829b-4176-80f1-97c80e883ae9.mp4

 
![image](https://user-images.githubusercontent.com/37368/185214280-6e4b4de6-b561-4730-9f73-6ba86ab563ad.png)

The top one is the off, the second one is the WAV,, and the third is the screen recoded version. any chance you could screencap it happening, so i can hear the problem your having?

**Comment by ptrschr** [comment]
@barkermn01 thanks for sharing this clip. Glad to see that it's working on your side with my shared resources!

Sadly mine sounds like this:

https://user-images.githubusercontent.com/41955309/185230407-a28d9ac5-95d5-49c9-b195-c44cacdac2df.mp4

**Comment by barkermn01** [comment]
yeah your not running the source build of the code there I think you might have the release build, 

Try replacing the files in the following paths x86\FF9_Data\Managed and x64\FF9_Data\Managed

[Build(X86).zip](https://github.com/Albeoris/Memoria/files/9365736/Build.X86.zip)
[Build(x64).zip](https://github.com/Albeoris/Memoria/files/9365739/Build.x64.zip)

**Comment by ptrschr** [comment]
> Found in: https://github.com/Albeoris/Memoria/tree/v2022.04.29
> 
> How to reproduce?: Follow instructions given at https://github.com/Albeoris/Memoria/wiki/Voice-acting-system
> 
> Description: OGG files are played like mentioned in the instructions, but Playback in-game seems to be pitched/fast-forwarded, but original file in mod directory sounds as it should.

Yes I am using latest released version linked here.

Thanks, using source version fixes the issue. Issue is closed by that.
