### ISSUE TITLE
The current MP/HP values are constantly reset to base values 

### ISSUE THREAD

**Issue by rassellek** [Albeoris/Memoria#208]
Hello! ;)

I have a little problem. With maxMP/HP active abilities, the current MP/HP values are constantly reset to base values when changing equipment and activating other SA abilities. 

example
## Permanent (code=MaxHP) MaxHP + MaxHP / 2 (/code) ##

the patch from April 29 is installed.

<iframe src='https://my.mail.ru/video/embed/3747690893717536769' width='626' height='367' frameborder='0' scrolling='no' webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

**Comment by Tirlititi** [comment]
Fixed with 485772b. Thanks for warning!
