### ISSUE TITLE
Be able to display custom battle messages

### ISSUE THREAD

**Issue by wrongstuff** [Albeoris/Memoria#21]
For example, when stealing an item, a battle message is displayed. It would be nice to be able to have this ability in the scripting engine when modifying skills.  Being able to specify the string in the same file would be nice as well, something like:

UiState.SetBattleFollowFormatMessage("Your string here");

**Comment by Albeoris** [comment]
UiState.SetBattleFollowFormatMessage(Byte priority, String formatMessage, params Object[] args)

Well-known priorities:
1 - Default
0 - "$btlmessage0011" = "Can’t escape!";
4 - "$btlmessage0012" = "Annihilated...";
