### ISSUE TITLE
Enhancement Requests

### ISSUE THREAD

**Issue by WarpedEdge** [Albeoris/Memoria#212]
Editing my previous comment to hopefully better portray the request:
1. I want to know if it is possible to allow guest members like Blank, Cinna, or Marcus to have the ability to Trance?

2. Is it possible to have an option togglable in the .ini to remove scripted fights forcing certain teams? Even when using CTRL+ALT+F2 making a 4 man team, once you engage in a scripted battle like the Plant Brain, you are forced to use specific characters. There is a script in these field scenes starting with "Remove Party" and ending with "MP x4" that dictates those. 

4. Can the DictionaryPatch.txt be further expanded on? What I mean is allowing for ease of model swaps? This could be expanded to having certain fun playthroughs looking like monsters or other NPCs. 

Please let me know if any additional information or clarification is required or if any of these options are not possible. Thank you for your time.

**Comment by Tirlititi** [comment]
The commits [7cf3836](https://github.com/Albeoris/Memoria/commit/7cf3836d780b5d80c637902d002d5eaee46f3da4) and [200afc3](https://github.com/Albeoris/Memoria/commit/200afc3b193c6c7feebc2b473a200b24d1bce6af) address these requests. Characters have trance when they are not flagged as "temporary" characters and, for the cases of Cinna/Marcus/Blank, removing that flag doesn't turn them into Quina/Eiko/Amarant anymore, etc...

**Comment by WarpedEdge** [comment]
Thanks as always @Tirlititi. I hope to test this out. I am assuming just run the patcher or get the latest version elsewhere? Usually I start from scratch and I do not see a new version to grab it from releases.

**Comment by Tirlititi** [comment]
It's still not available as a release. I don't make new releases too often, only when there are more new features and when I have tested them a bit to make sure that there are no obvious incapaciting bugs introduced by mistake.

**Comment by WarpedEdge** [comment]
Got it. Since its not available as a release, is there a way for me to try it out now or will I need to wait until that release?

**Comment by Tirlititi** [comment]
You need to install Github and Visual Studio, then install the project on your computer and compile it. See the "Build" instructions on the Readme.

**Comment by WarpedEdge** [comment]
Got it. Thanks!
