### ISSUE TITLE
bumping version number up on featured mods on mod manager can disable mods

### ISSUE THREAD

**Issue by faospark** [Albeoris/Memoria#214]
i ended up reverting back mogaddons to version 2.5 even if its contents are already are on 2.61. 
the mod manager disables the mod if the original submitted version number/ catalog version number does not match  the source url 
ive tested it with other mods too example below the beatrix mod the version number in catalog is 5.2
![Screenshot_1510](https://user-images.githubusercontent.com/11664809/194578388-08c30a63-94d2-4be1-866b-72392f0d29cb.png)
if you bump the version to 5.3 the mod manager disables the mod in the next launch. you have to renable the mod everytime 
![Screenshot_1509](https://user-images.githubusercontent.com/11664809/194578674-109efa57-54e3-4316-88be-619f109ee8de.png)

im just thinking this could become a problem for updating mods and also for beta testing of mods in case a modder changes the version number

**Comment by Tirlititi** [comment]
This bug seems to have been fixed with 3567b31
Thanks for the report.
