### ISSUE TITLE
Is there any way to make ATB work the same as "Wait" but not just in submenu?

### ISSUE THREAD

**Issue by SomeoneIsWorking** [Albeoris/Memoria#218]
Turn based makes it fill instantly which I think changes many things and regular mode makes the game too hard with speed cheat.
Instead another option where ATB stops only when picking an option similar to "Wait" but doesn't lock it to only submenus.

**Comment by snouz** [comment]
I don't know when it happened but there are now 4 ATB modes, so I think this is now fixed. If not, feel free to re-open an issue.
