### ISSUE TITLE
"Heave" enemy attack uses the wrong sound

### ISSUE THREAD

**Issue by Trivial-Man** [Albeoris/Memoria#220]
Battle an Adamantoise and let it use Heave on you. It sounds like a weird metallic "poink" instead of a hefty thud like it should be

**Comment by Tirlititi** [comment]
I noticed that too. It happens with Gizamaluke's Crash and a few more.
So, I've double-checked. I thought that the "Poink" sound was the correct PSX sound used for Baku's "ARGH!" attack (the one where he charges you with his shoulder), but it's not...

So, I see different explanations:
1) This "Poink" sound (or something very similar) was used in the PSX version of the game and somehow its usage in the Steam version is incorrect (maybe it was swapped with the "Heave" normal sound when porting the game to its modern versions),
2) Or this sound is a brand new sound that the Silicon Studio team created to add a funny sound effect to some attack (Baku's or Gizamaluke's ?) but they didn't notice that it was also used by other attacks for which it doesn't fit at all.

If anyone recognizes the sound and can tell us if/where it was used in the PSX version of the game, please let us know.
Here is the sound in question: [se010188.ogg](https://www.dropbox.com/s/4hr2cpk3gwgiwo9/se010188.ogg?dl=0)

**Comment by Trivial-Man** [comment]
It is worth noting that I checked with a fresh install and the heave sound effect sounds correct in an unmodded copy of Steam FF9. It is only after installing Memoria that the sound becomes wrong.

Also, I have no clue how sound effects work behind the hood, but the one you uploaded sounds slowed down compared to how it sounds in my game. It's been years, but I vaguely recall it being some kind of missed attack sound effect. Maybe Quina's or Tonberry's? It seems like a stab. That's my only guess but I really don't know.

**Comment by Tirlititi** [comment]
Fixed in bd440e0
It was indeed a bug I must have introduced when working on the SFX Rework system.

**Comment by Trivial-Man** [comment]
Awesome, thanks. I look forward to a new release to test this out
