### ISSUE TITLE
Fratley, Lani, and Kuja from a newly released Playable Character didn't recover using Moggle Tent, Inn (Rest), or Spring Water

### ISSUE THREAD

**Issue by muhamadariefnugraha** [Albeoris/Memoria#221]
Fratley, Lani, and Kuja from a newly released Playable Character didn't recover their HP and MP using Moogle Tent, Inn (Rest), or Spring Water.

How to Reproduce:
1. Enable all characters and bring Fratley, Lani, or Kuja to your formation 
2. Make sure the character not having their maximum HP or MP (By going to battle and getting hit or performing magic)
3. Call Moogle and tent. Check again their HP and MP, it's not changed. Feel free to go to any town and go to Inn, then rest. Their HP and MP also have not recovered. Also not recovered when drinking water on Vivi/Quan Home near Treno or Water Spring near Chocobo Forest - Lindblum bottom.
4. Use your item or cure magic is the only option to recover 

Ps: Thanks for the great work. I love it.

**Comment by Tirlititi** [comment]
This is fixed with the commit d85742c. It'll be part of the next release's bug fixes.
Thanks.
