### ISSUE TITLE
Control Invincible with right analog stick

### ISSUE THREAD

**Issue by Trivial-Man** [Albeoris/Memoria#224]
I don't recall if any of the other vehicles can be controlled like this, but in the PSX version at least the Invincible could be made to move forwards or backwards just by tilting the right analog stick up or down (left and right do nothing). I don't think the right stick was implemented at all besides this, but it would still be neat to add back support for this specific case for the remake.

**Comment by Tirlititi** [comment]
Added in c5680fa.
Thanks for pinpointing this behaviour of the PSX version that I forgot or never knew of
