### ISSUE TITLE
Another addition to the playable cast request? Mikoto (Mysterious Girl)

### ISSUE THREAD

**Issue by WarpedEdge** [Albeoris/Memoria#227]
I know it is soon after we got Lani and Fratley, but I know some discussions were made on some forums and chats before for Mikoto being added would be pretty cool. Is it possible that she can be added playable as well? Could utilize the same animations as Zidane due to similarities in their model.

**Comment by snouz** [comment]
Nothing against this request, but that character barely has any role and happens very very late game, I think she only exists in a few cutscenes.

@Tirlititi do you think the same?

**Comment by Tirlititi** [comment]
I'm all in for adding new playable characters, even those without significant roles. The idea behind the Playable Character Pack is not actually to add characters relevant to the story; they won't be integrated in cutscenes anyway. I wouldn't even mind to have Maliris as a playable character. Besides, if the PCP mod can provide a pool of playable characters, other mods could be made that rely on it and add these characters to the story or even make spin-offs with them.

Adding more playable characters to the PCP mod is something that is not straightforward and the process is not very well documented, but if anyone wants to work on it, I'm always on for that.

**Comment by WarpedEdge** [comment]
I believe we can close this, if people start adding new characters that would be great, but having it as an additional request doesnt make sense to me anymore. Maybe in the future when someone makes either importing models a normal thing and as well as easily restructuring current characters existing bone models to be easily playable. maybe @DV666 will put out a guide in the future or something if he is adding new units in himself like Baku, because unfortunately the dictionary patch while extremely helpful not user-friendly for others to add in.
