### ISSUE TITLE
Help installing latest Memoria patcher on Steam Deck

### ISSUE THREAD

**Issue by KaliEros** [Albeoris/Memoria#228]
Hello all,

I could really use some help with installing the latest Memoria patcher on my Steam Deck to get the Install Mods option to show up thus allowing me to enjoy Alternate Fantasy and Moguri on the go.

I've downloaded the latest release of the Memoria patcher and tried adding it to Steam as a non-steam game, but when I hit play, it looks like it tries to launch, but gets stuck on the Steam loading screen. Is there a specific compatibility I need to force like Proton GE or is there another way entirely to install the latest Memoria patcher on my Steam Deck?

I would greatly appreciate any help with this. Thank you advance.

**Comment by Tirlititi** [comment]
Hello,
I don't have the Steam Deck and thus I cannot personnally help. We mod the PC version of the game and the compatibility with Steam Deck (or other platforms) has never been a concern so far.

I've seen people writing about how to install mods on Steam Deck for Final Fantasy IX, including Memoria's latest releases. It looks like different people encounter different issues.
[SonicBrawler's tutorial](https://www.reddit.com/r/FinalFantasyIX/comments/xbnume/60_fps_ffix_but_its_on_steam_deck/) (check his message in the discussion below)
Another user advised this:
> For anyone else who wants to do it, you have to do it on your PC then transfer ALL the files over and just overwrite them!

**Comment by ChrisP8Three** [comment]
I found that adding the patcher as a non steam game worked, just go into properties and force compatibility with the latest proton version. obviously only in desktop mode does this work.
When i ran that the very first time it looked like it was attempting to update the patcher like it was a steam game and half hung. but when i tried it again it worked. 
Then i ran the game and the launcher worked.
I did find the check boxes do not work, so you need to manually change the settings in the memoria.ini file in the game folder.
although thats not entirely true, the check boxes sort of worked, using a mouse they very briefly show the check marks and under testing some turned on and once on stayed on, but others didn't make a change (skip intro, speed cheat etc) so its easier and quicker to just alter the ini.

**Comment by snouz** [comment]
Linked to this https://github.com/Albeoris/Memoria/issues/319
