### ISSUE TITLE
Character name/room missmatch when selecting Oeilvert party

### ISSUE THREAD

**Issue by arg-xd** [Albeoris/Memoria#230]
Graphic order does not match the names Kuja is calling out (for example Amarant called out while Dagger's room is shown). I thought it was weird so I looked at some older lets plays with Moguri/Memoria and it works properly, if you pick [Dagger, x, y] or [x, Dagger, y], Zidane always reads it [x, y, Dagger] and Kuja repeats it with graphic following the order.

In my case Zidane reads it in pick order [Dagger, x, y], Kuja repeats him but room shown follows the intended order [x, y, Dagger]. I suspect Dagger is automatically suppresed to last slot in scenes so she can't have any interactions while lacking concentration, but Zidane fails to respect this order.

**Comment by Tirlititi** [comment]
Commit 65ebe65 fixes that bug. Thanks for pinpointing it :)
