### ISSUE TITLE
Request: Remove the 4 man party restriction

### ISSUE THREAD

**Issue by WarpedEdge** [Albeoris/Memoria#235]
Hi,

I have either not seen it mentioned, or surprised it hasn't been mentioned, but I would like to request we remove the party restriction requiring 4 member parties after opening the party adjustment menu. I would like to be able to either do single, duo, or just 3 man party runs, but as it stands right now, it forces you to use 4. 

Bonus Request:
This is just a bonus ask if it seems doable, but if removing this restriction is possible, maybe its possible to either add more than 4 people to a party or do a change out options similar to FFX? Only if possible and if someone already works this.

**Comment by Tirlititi** [comment]
The commit 54ca196 addresses the first request. The second one will be much more complicated to do (although still less complicated than increasing the limits of fighters of 4 party members + 4 enemies, which will be hardly possible even on the long run).

**Comment by WarpedEdge** [comment]
Awesome thanks for the quick turnaround! Which part is more complicated for the 2nd one? The adding a swap feature like in FFX or adding more than 4 at a time, or both? Thanks again! :)

**Comment by Tirlititi** [comment]
Having more than 4 party members in battles is much more complicated. Having a swap feature is not simple either.

**Comment by WarpedEdge** [comment]
Understood. If that is something you do not think is worth the time please let me know, as I can close this. I just thought the idea would allow for some fun gameplay and new strategies :)

**Comment by WarpedEdge** [comment]
Hey Tirlititi, with the newest release allowing us to not be forced to have 4 man parties, which would essentially let us have 1-3 man parties has a bit of a hiccup. Once you have 2-3 members, you cannot take them back out as there are no blank spots in the reserve party area. Anyway around this?

**Comment by WarpedEdge** [comment]
Did you want me to close this particular request and open the other part as a second issue? The restriction has been removed, but we need more blank spots to put the leftover characters in there as it forces you to use 3 people once they are in your party as there is no where to put them. I thought there was a feature to scroll over, but I do not see those extra slots.

**Comment by Tirlititi** [comment]
No no, as you said, the limitation can still be worked further on. I think I'll get back to it eventually (and maybe the "change out option").

**Comment by WarpedEdge** [comment]
Hey just wanted to follow up and see if this is still on track, no longer planned, or completed in its initial phase? I know it was a multi parter, so if the min 4 members restriction was removed so you can choose to have 1-3 units only. This could be closed and if a swapout feature like FFX that was mentioned above is better as a separate request.
