### ISSUE TITLE
Request: Integrate a modification tool for Memoria

### ISSUE THREAD

**Issue by WarpedEdge** [Albeoris/Memoria#236]
I attempted to create a discussion for integrating Hades Workshop into Memoria, allowing people to make additional modifications to their game, but it has received 0 traction for months and people on the Mogs discord seemed to like the idea, but still no discussion.

It would be great if we could do either:
1. Integrate Hades Workshop (HWS) to work with memoria so that when new features are introduced (e.g. Playable Party Pack) that the new changes can be modified further into HWS. Integrating HWS would mean the entire code would need to be re-written from C++ to C# which would be a lot of effort, but definitely feel like it would be worth it.
2.  Create a new tool separate from HWS that can do the same thing in a sense. When launching the game it can have an additional option that could launch a new tool that allows you to modify existing data in the FFIX folder and then can easily save and test afterwards

I also want to mention that I am really good at writing tutorials for how to use items and tools once I am given a run down of everything it can do, and I would love to put effort into doing them for all the capabilities offered so new people both players and modders can have an easy way to dive into it and this will allow the community to grow even more. Please let me know if this request could be done :) Thank you for your time.

**Comment by snouz** [comment]
I think this issue is fully for @Tirlititi to accept or refuse, as he's the sole developer of Hades Workshop, as well as the main developer of Memoria for several years. If he's not planning it, I don't see a way it will happen.

**Comment by WarpedEdge** [comment]
I believe in recent iterations, wasn't this kind of added? he added HWS support to memoria right? I know it doesn't meet the exact requirements, but if only @Tirlititi is able to do this and he doesn't believe he will, we could close this :)
