### ISSUE TITLE
Booster: frequent random encounters

### ISSUE THREAD

**Issue by Sefie1999AD** [Albeoris/Memoria#24]
The game comes up with a booster to disable random encounters, which is nice, but I was actually looking for something completely opposite as well. If you ever want to grind, the random encounter rate is amazingly low on several areas, especially compared to the PSX version. Therefore, I'd like a booster that makes random encounters happen much more frequently. Maybe something similar to Final Fantasy X & X-2 HD Remaster's encounter rate booster.

Some specifics: if you can, make it something that can be changed on the fly, so if you want to enable/disable the encounter rate booster, you can do it in-game with a hotkey or button combo, rather than having to quit the game and manually edit the config file.

**Comment by Albeoris** [comment]
Done. Shift+F4
