### ISSUE TITLE
Problem with new item text

### ISSUE THREAD

**Issue by stir472** [Albeoris/Memoria#242]
Hello tirlititi. first talk is the congrats for your new update! i testing the news and its amazing. I wanted to inform you of something that I think is a mistake. When I add a new weapon I can do it without any problem, except that when the game is going to load the weapon in the inventory or in the store where I am going to buy it, the name does not appear, the symbol of the weapon appears but no text. Is there any way to fix this? (I tried in my native language and in English with the same result) Best regards

**Comment by Tirlititi** [comment]
Where do you add the name for your new weapon?
If you use the ``[Import]`` option, you need to increase the number at the top of the file. Unfortunatly, it also requires contiguous IDs, even though I don't think that's your problem.
Eg.:
```
/*
./StreamingAssets/Text/US/Items.strings
0270
*/
"$item0000" = "Hammer
Cinna’s hammer.
------
 Cinna’s hammer.";
................................................
................................................
"$item0269" = "New item
An item that didn't exist.
------
An item that didn't exist.";
```

**Comment by stir472** [comment]
I add the weapon in the txt files of the path /streamingassets/data/items. i dont have the folder "Text" etc... i dont know why.

**Comment by Tirlititi** [comment]
Ok, you add the *weapon* in ``streamingassets/data/items.csv`` (which is a CSV file by the way, not a TXT file).
But where do you add the *weapon's name*? You can't expect the game to just invent a name for an item that you created.

**Comment by stir472** [comment]
I don't have a text file, I was looking now and found this path FF9_Data/embeddedasset/text i find different language and 3 files with extension .mes

This is the correct file to add the names of weapons?
I use a mod folder. In the original folders of the memory when I install it, the text files are not there either.

**Comment by Tirlititi** [comment]
Ok, then it is normal to have no ``.strings`` files. It is indeed the ``.mes`` files that contain texts, including item names and descriptions.

So then, just add names and descriptions in the files:
```
[ModFolder]/FF9_Data/embeddedasset/text/us/item/itm_name.mes
[ModFolder]/FF9_Data/embeddedasset/text/us/item/itm_help.mes
[ModFolder]/FF9_Data/embeddedasset/text/us/item/itm_btl.mes
```
And the same for other languages.

If your item has a non-contiguous ID, you can use the tag ``[TXID=...]``. For example, if your custom item has ID 500 (instead of just using the IDs 256, 257, etc... following the IDs of the normal items), you can use something like this in your ``.mes`` file:
```
[TXID=500]An item that didn't exist.[ENDN]
```

**Comment by stir472** [comment]
thanks so much know i can add items with 0 problems. thanks too for the fast help!! <3
