### ISSUE TITLE
Little Issue about active skill.

### ISSUE THREAD

**Issue by stir472** [Albeoris/Memoria#245]
Hi Tirlititi I wanted to inform you of a hades workshop error and the latest memory update. It turns out that my character data, specifically in the abilities. Me when exporting the data from hades workshop, the data inside the file does not match exactly. I attach an example.
File with data from hades workshop: 101;40;

Memory streaming assets files: AA:101;40;# Flee

The thing is, I edited a new active skill, and when I edited it in my hades workshop exported file it didn't work, but after exporting the memory skill file to my mod file and editing it it did work. I hope you understand what I'm saying, Greetings.

**Comment by Tirlititi** [comment]
Hades Workshop was updated and should not have this problem anymore (although I don't see why you had a problem with a format like ``101;40;`` to begin with).
