### ISSUE TITLE
PSX Font simply not working 

### ISSUE THREAD

**Issue by AFreeChurro** [Albeoris/Memoria#247]
(i dont use github so sorry if im using this wrong) I installed the latest version of memoria engine and I selected the PSX font and the game goes to the PC default. This also applies to when i got a custom "zidane" which tries to replicate the psx font and it still ends up being the PC default. Other fonts work just fine too. What should I do?

https://imgur.com/ofTckyc
https://imgur.com/DnOzb6L
https://imgur.com/QextNom

**Comment by AFreeChurro** [comment]
I installed it and the

**Comment by AFreeChurro** [comment]
i installed it in my fonts folder and it does show up on the font select menu but it still doesnt apply to the game, i tried the Alexandria and FFIX PSX Font options and nothing

**Comment by Tirlititi** [comment]
Are you sure you installed the font correctly? If you're under Windows, it should be able to install it by double-clicking on the ``.ttf`` and then click ``Install``.

**Comment by AFreeChurro** [comment]
i installed it multiple times in different ways by either dropping it in the folder or going to the one on my desktop and installing it there
first two are me installing it and checking from the fonts folder, 3rd one is me doing it from desktop and it asks me to install but i check the game and i select Alexandria and nothing
 
https://imgur.com/yaJXFKW
https://imgur.com/VoxvC3G
https://imgur.com/CbXuobz

**Comment by DV666** [comment]
Maybe I'm too late, but I advise you to install the font for all users:

Right-click on the .tff file => Install for all users.

I had this problem too and by doing this, the Memoria launcher reads the font correctly :)

**Comment by Takikun** [comment]
> Maybe I'm too late, but I advise you to install the font for all users:
> 
> Right-click on the .tff file => Install for all users.
> 
> I had this problem too and by doing this, the Memoria launcher reads the font correctly :)

It fixed my issue with me trying to add custom font. Maybe it has something to do with Windows 11 if you're on this OS aswell. Anyway, thank you.

**Comment by faospark** [comment]
> > Maybe I'm too late, but I advise you to install the font for all users:
> > Right-click on the .tff file => Install for all users.
> > I had this problem too and by doing this, the Memoria launcher reads the font correctly :)
> 
> It fixed my issue with me trying to add custom font. Maybe it has something to do with Windows 11 if you're on this OS aswell. Anyway, thank you.

not really . system wide fonts are stored in C:\Windows\fonts which i think how memoria loads fonts.  
starting a version windows 8 or probably earlier microsoft introduced font installation only for the online/store and local user account which stores the font in either uwp apps folder or the C: \Users\Username\AppData\Local\Microsoft\Windows\Fonts\ folder. 
It actually a good practice  to install fonts for all users.

**Comment by snouz** [comment]
![image](https://github.com/Albeoris/Memoria/assets/9964576/b93eaf78-b638-4ef8-b96f-78ab79e3509a)

**Comment by snouz** [comment]
I don't understand how zePilot is using a fond without having to install it, I would like to integrate this feature in memoria, as it is one of the last custom things that moguri's launcher has over memoria.

**Comment by snouz** [comment]
I managed to integrate the embedded font in memoria, no need to install the ttf/otf.
