### ISSUE TITLE
Disabling Menu Delay

### ISSUE THREAD

**Issue by TailsGuy** [Albeoris/Memoria#250]
So, there's a menu delay for the FFIX port, similar to FFX/X-2.
Now, I'm not really the biggest fan of this since it's really sluggish and I'm used to the PSX version where you can go at your own speed.

Is there any way to disable this, or will it have to be implemented?

**Comment by TailsGuy** [comment]
The HUD in battle also goes outside of the borders of the screen in 4:3.

**Comment by Tirlititi** [comment]
Have you tried to increase the game's frame rate to 60 FPS? Or at least increase the ``MenuFPS``?

**Comment by TailsGuy** [comment]
> Have you tried to increase the game's frame rate to 60 FPS? Or at least increase the `MenuFPS`?

I can try to do so right now, but if I recall, there's no change whatsoever.

**Comment by TailsGuy** [comment]
Yeah, there's nothing I can do. Pretty much every menu in the game has a delay of a couple frames. You can't menu at all in this version. Now, another thing is is that you can't hold down Cross/A to auto attack either in battle, but that's not nearly as big on as issue as this.

**Comment by TailsGuy** [comment]
Bump

**Comment by Tirlititi** [comment]
Don't bump issues.
