### ISSUE TITLE
Character twitch in analog movement

### ISSUE THREAD

**Issue by Arthandas** [Albeoris/Memoria#257]
Hold up on the analog stick then move it slightly left and the character will instantly turn around 15-20°. If you now slowly return to just holding up he'll jerk back again. If you do the same but turn right instead of left he'll rotate smoothly. For some reason this bug exists only on the left side.

I'm attaching a clip showcasing this issue.
[AnalogMov.zip](https://github.com/Albeoris/Memoria/files/12267869/AnalogMov.zip)

**Comment by Tirlititi** [comment]
The transition tied to angle continuity was indeed badly handled. It should be fixed with the latest commit.
Thanks for the report, the video was also helpful to understand what was the problem.
