### ISSUE TITLE
Life bar for enemies (like FFX)

### ISSUE THREAD

**Issue by stir472** [Albeoris/Memoria#259]
Do you think it would be very difficult to implement a life bar as it happens in final fantasy X? now that it is much easier to break the 64K life limit I think it would be quite useful

**Comment by Tirlititi** [comment]
What do you mean? There is actually no life bar at all in Final Fantasy X.

**Comment by stir472** [comment]
In Final Fantasy X you can see the exact life that the monster has if you have an ability called piercing eye, I mean that bar

**Comment by Tirlititi** [comment]
I see. That would be possible at some point.

**Comment by snouz** [comment]
Duplicate issue as #246
