### ISSUE TITLE
Compatible with compatible with Hades Workshop

### ISSUE THREAD

**Issue by dclem2** [Albeoris/Memoria#26]
tutorial, guidance to replacing fonts, compatible with Hades Workshop.

**Comment by Albeoris** [comment]
**Memoria.ini:**

[Font]
Enabled=1
Names="Arial", "Times Bold"

Compatibility with HW - it's a different long running task. (:

**Comment by Kogekko** [comment]
Hi. I want to translate this game. But I have to draw my special letters to the font, I read your comment here:
https://steamcommunity.com/groups/ff-modding/discussions/13/357284131801032090/
But after I imported the edited tff file to p_fa.mpc.txt.decrypted, how can I encrypt back p_fa.mpc.txt.decrypted to p_fa.mpc.txt? After all I need to replace p_fa.mpc.txt in the resources.assets, right?
Hope you can help, I ll wait for your reply.

**Comment by Kogekko** [comment]
http://i.imgur.com/YGTX1tR.jpg
Here you can see, the font of the game has slots for my letters but they are all empty, I have to draw them there, but please guide me how to encrypt back p_fa.mpc.txt.decrypted to p_fa.mpc.txt.

**Comment by Kogekko** [comment]
About your Memoria tool I think it just can change the style and the size of the font, it cannot draw new letters to the font, right?

**Comment by GuyInDogSuit** [comment]
I like how the fonts look, if you lower the size a bit, it looks cleaner and less cluttered.
I wish we could resize the panels though. The touch-screen interface is ugly.

**Comment by Albeoris** [comment]
Now is compatible. Thank you **Tirlititi**!
http://forums.qhimm.com/index.php?topic=14315.0
