### ISSUE TITLE
Is there a way to increase speed in which character's dialog is displayed?

### ISSUE THREAD

**Issue by FlameHorizon** [Albeoris/Memoria#264]
I would like to understand if there is a way of controlling of fast each text bubble is filled will text. Is there a place where I can start look into for that? Thanks.

EDIT: would be this a good place to start?

https://github.com/Albeoris/Memoria/blob/37c4c7f08def5e210f3f664096f248655bdda9e1/Assembly-CSharp/Global/Dialog/Dialog.cs#L1370C1-L1376C3

**Comment by Tirlititi** [comment]
Have you tried modifying the "Field Message" speed option in the in-game configuration menu? That's exactly what it does.
If there's not enough possibilities or if that's not what you mean, then can you be more precise?
