### ISSUE TITLE
Proper widescreen support

### ISSUE THREAD

**Issue by hyperspeedgx** [Albeoris/Memoria#27]
Could a widescreen mode be added? Like Resident Evil HD does, with the camera following you while you walk on the background, it works like this, the background is zoomed to 16.9 and then it changes to up, down, left or right depending to where you move on it.

Here how it looks on RE1 HD, do note the camera movement while you walk on the scenario, in 4.3 mode this camera movement doesn't happens cause you can see the entire background.

https://youtu.be/2_dn-L9hPLM?t=729

FF9 does this camera movement even in 4.3 mode so it might be possible to otimize it to 16.9 as well.

**Comment by Albeoris** [comment]
https://i.imgur.com/oOXHDRE.jpg
https://i.imgur.com/UggkNfK.jpg
https://i.imgur.com/5xNvPc1.jpg
https://i.imgur.com/Txmjsam.jpg
https://i.imgur.com/bHo2rjU.png

**Comment by Albeoris** [comment]
Resolved in 25978dbb1348aae6fc19516aac1a14eb1774ac6e

https://i.imgur.com/FziaWiV.jpg
https://i.imgur.com/68VdC59.jpg
https://i.imgur.com/9uhVWzW.jpg
https://i.imgur.com/uB9ZYBs.png
https://i.imgur.com/a7v0uIM.jpg

**Comment by hyperspeedgx** [comment]
Thank you so much Albeoris. xD
