### ISSUE TITLE
Request: binding to controller buttons

### ISSUE THREAD

**Issue by Kaje68** [Albeoris/Memoria#271]
Is there already a way to bind to a controller?  I'm using Memoria for FFVI PR and my primary usage is fast forward.  Editing the config file is easy enough to bind to a keyboard, but it would be much better for me if I could binding it to a button on my controller if possible.

**Comment by Tirlititi** [comment]
You should be able to do that using Steam's controller binding (right-click on the game on Steam and check its "Controller configuration").

**Comment by Kaje68** [comment]
> You should be able to do that using Steam's controller binding (right-click on the game on Steam and check its "Controller configuration").

Thanks man, I had no idea this was built into steam.
