### ISSUE TITLE
Audio Export is ignored/not working

### ISSUE THREAD

**Issue by Moonpaw** [Albeoris/Memoria#275]
With the Export enabled=1 and Audio=1 in Memoria.ini no audio export is being done. Latest memoria release as of 22 december 2023.

Memoria.log shows the following
22.12.2023 12:42:35 |M| [SteamSdkWrapper] Initialized: True
22.12.2023 12:42:35 |M| [FontInterceptor] Dynamic font initialization.
22.12.2023 12:42:35 |M| [FontInterceptor] Pass through {Configuration.Font.Enabled = 0}.
22.12.2023 12:42:35 |M| [FontInterceptor] Loading font [Original: TBUDGoStd-Bold (UnityEngine.Font)]
22.12.2023 12:42:36 |M| [GameLoopManager] RaiseStartEvent
22.12.2023 12:42:36 |M| InitializeItemText
22.12.2023 12:42:36 |M| InitializeImportantItemText
22.12.2023 12:42:36 |M| InitializeAbilityText
22.12.2023 12:42:36 |M| InitializeCommandText
22.12.2023 12:42:36 |M| InitializeBattleText
22.12.2023 12:42:36 |M| InitializeLocationText
22.12.2023 12:42:36 |M| InitializeEtcText
22.12.2023 12:42:36 |M| InitializeEtcText
22.12.2023 12:42:36 |M| [TextResourceExporter] Pass through {Configuration.Export.Text = 0}.
22.12.2023 12:42:36 |M| [GraphicResourceExporter] Pass through {Configuration.Export.Graphics = 0}.
22.12.2023 12:42:36 |M| [FieldSceneExporter] Pass through {Configuration.Export.Field = 0}.
22.12.2023 12:42:36 |M| [BattleSceneExporter] Pass through {Configuration.Export.Battle = 0}.
22.12.2023 12:42:36 |M| [ResourceExporter] Application will now quit. Please disable Configuration.Export.Enabled and restart the game.
22.12.2023 12:42:36 |M| [ResourceImporter] Pass through {Configuration.Import.Enabled = 0}.
22.12.2023 12:42:36 |M| [GameLoopManager] RaiseQuitEvent

As you can see AudioExporter isnt even called/checked?

**Comment by barkermn01** [comment]
So i have looked into this but i can't get the debugger injected intime to catch it but i think i know what is going wrong it looks like these are not loading anything.

```cs
        String textAsset = AssetManager.LoadString("EmbeddedAsset/Manifest/Sounds/SoundEffectMetaData.txt");
        String textAsset2 = AssetManager.LoadString("EmbeddedAsset/Manifest/Sounds/SoundEffectExtendedMetaData.txt");
        String textAsset3 = AssetManager.LoadString("EmbeddedAsset/Manifest/Sounds/MusicMetaData.txt");
        String textAsset4 = AssetManager.LoadString("EmbeddedAsset/Manifest/Sounds/MovieAudioMetaData.txt");
        String textAsset5 = AssetManager.LoadString("EmbeddedAsset/Manifest/Sounds/SongMetaData.txt");
        String textAsset6 = AssetManager.LoadString("EmbeddedAsset/Manifest/Sounds/SpecialEffectMetaData.txt");
        String textAsset7 = AssetManager.LoadString("EmbeddedAsset/Manifest/Sounds/ResidentSpecialEffectMetaData.txt");
```
