### ISSUE TITLE
h.254 video support

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#278]
This has been on the back of my mind for ages. The ogg format loses a LOT of video quality while being extremely heavy. If there was an integrated h.254 (wrapped in mp4 for example), this would reduce video size & improve quality with video upscales.

**Comment by barkermn01** [comment]
So after talking, currently this would require adding some form of transcoder into Memoria unfortunately there does not seem to be any .NET Framework 3.5 compatible transcoders that work, so this is going to require us to build a wrapper arround some other lib maybe the FFMPEG libraries or libVLC.

In the meantime though @SamsamTS appear to have a method for stopping the desync which using one of the newish exposed SDLib Methods `SdSoundSystem_SoundCtrl_GetElapsedPlaybackTime` we're going to try in the coming days.
