### ISSUE TITLE
Bug in escaping turn-based battles

### ISSUE THREAD

**Issue by Sefie1999AD** [Albeoris/Memoria#28]
In the turn-based mode (BattleSpeed = 2), pressing L1+R1 doesn't seem to make characters run away from battles. They do the animation that they're trying to run away, but they never succeed in it. Even if you keep holding L1+R1 and do battle actions (attack, defend etc) to advance time, the characters aren't successful in running away. The only way to run away from battles is using Zidane's Flee ability.

**Comment by Albeoris** [comment]
Do you have any idea how to fix this?
What should be the correct behavior?

**Comment by Sefie1999AD** [comment]
According to FF Wiki (http://finalfantasy.wikia.com/wiki/Escape_(command)#Final_Fantasy_IX), the formula for successfully running away is this in the normal game:

Chance = [ PartyLvAvg * (200/MonsterLvAvg)/16 ]
If Rand(0..99) >= Chance, battle continues

"This check is performed once per second for as long as the player holds L1 and R1. Escape is possible only during the idle time when enemy ATBs are filling."

I was thinking of something like this for the turn-based system:
- assume ATBs are in the state **t1** when the player presses L1 and R1
- when the player presses L1 and R1 at state t1, perform the escape check using the above formula
- if Rand(0..99) < Chance, the player successfully flees, and the battle ends immediately
- if Rand(0..99) >= Chance, the battle continues. Set Chance = 0 while the ATB remains at state t1, so that the escape won't work if you try to run again during state t1
- assume the battle continues, and the ATBs reach the next state, **t2**
- at the state t2, the player is free to attempt escape again, and by holding L1 and R1, the escape check is performed again, using the above formula.

Here's an alternative solution that could be even more simple:
If the player presses L1 and R1, transform the ATB system from turn-based to the default one while L1 and R1 are pressed. This should make escaping work normally. When the player stops holding L1 and R1, revert to the turn-based system. Just make sure the ATB doesn't get permanently stuck when you return to the turn-based system (i.e. the ATB should move to the next character/enemy's turn).
