### ISSUE TITLE
Skip intro option merely stops the video from looping, but doesn't skip the intros

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#285]

**Comment by Tirlititi** [comment]
Are you sure about that? I use ``SkipIntros = 3`` and it does skip the intro ("SquareEnix / Silicon Studio / Intro FMV") in a blink.

**Comment by snouz** [comment]
> Are you sure about that? I use `SkipIntros = 3` and it does skip the intro ("SquareEnix / Silicon Studio / Intro FMV") in a blink.

You're right, in fact I had the value 0 overriding the value 3, linked to the problem of duplicate entries in memoria.ini, so this is a consequence of the other bug I opened today. So my bad.
