### ISSUE TITLE
The choice of the monitor and selection of buttons to display in the launcher.

### ISSUE THREAD

**Issue by LoveIsDarkness** [Albeoris/Memoria#29]
Albeoris, please make a choice of the monitor and the buttons (PS or XBox) in the game launcher FF IX. Also, if you can, do this with all launcherone been released (Launcher from FF XIII, VII). Thank you for your efforts!

**Comment by Albeoris** [comment]
I added the ability to select a monitor in the launcher.
Unfortunately, the game does not have PS-icons. Only Keyboard, Xbox, Android and iOS.
You can export an atlas replace icons and import it again.

P.S. Please don't merge two issues into the one.

**Comment by LoveIsDarkness** [comment]
Атлас то могу заменить, но это заменит и русский язык в атласе, если только с фотошопом повырезать русский язык из русского атласа и вставить его в английскую версию с кнопками от PS, я предлагал сделать кнопку, которая будет менять атласы (XBox, PS One).
