### ISSUE TITLE
[Feature Request] 16:10 Widescreen Support

### ISSUE THREAD

**Issue by Rellawing** [Albeoris/Memoria#291]
I got a Legion Go recently and love my gaming experience, and discovering your mod/loader on top of Moguri Mod (which I had long since discovered), it gave me precisely what I needed. Upgrading the clunky, slow 15-30fps experience that Square gave us by default. Now I'm playing at 60fps all around and loving it! There's only one fly in the ointment, so to speak.

The 16:9 support gives me bezels up top and below. I tried everything I could think of to make it stretch at least, but all to no avail. Fullscreen nor Borderless Fullscreen modes offer me a solution.

I sure hope that you are still developing this program and can bring us support for a few more widescreen ratios.

Thanks in advance!

**Comment by snouz** [comment]
I would love to tackle this problem, but it's a pretty big thing to implement, I see more and more people asking for 16/10 because it seems like it's the native resolution of the steam deck.

**Comment by snouz** [comment]
Ok that was not so hard to implement in the end, that will be in the next release!

**Comment by Rellawing** [comment]
Thanks!

**Comment by RickyBO89** [comment]
There are issues with 16:10 and Battle HUD "Small" and "PSX Like": the menu and the hud go partially outside the screen!

**Comment by snouz** [comment]
> There are issues with 16:10 and Battle HUD "Small" and "PSX Like": the menu and the hud go partially outside the screen!

Thanks for reporting, I added a new issue for it https://github.com/Albeoris/Memoria/issues/323
