### ISSUE TITLE
AllCharactersAvailable = 2 not preventing party changes

### ISSUE THREAD

**Issue by Huntyx3** [Albeoris/Memoria#293]
AllCharactersAvailable = 2 does not seem to behave differently from = 1, the party is still changed for specific fights.

**Comment by Tirlititi** [comment]
Yes it does. If you have the Playable Character Pack mod installed, make sure to change the option inside that mod instead (``PlayableCharacterPack/Memoria.ini``). I'd say that's probably the issue you have.

**Comment by Huntyx3** [comment]
That was indeed the issue, thank you. I did not realize the mod had its own Memoria.ini
