### ISSUE TITLE
3D models .fbx format

### ISSUE THREAD

**Issue by dclem2** [Albeoris/Memoria#30]
Albeoris,
Do you now any info about the models in the assets handled with .fbx, and what version it is?

**Comment by Albeoris** [comment]
Not yet. :)

**Comment by dclem2** [comment]
Darn.
Well, I'll keeping working to find out. Memoria can export backgrounds, will it soon be able to import models?

**Comment by Tirlititi** [comment]
Model importer is what I am currently working on and you know that dclem... Unless you want us to waste time by doing the same thing separatly, urging Albeoris about it is not the way to go.

**Comment by Albeoris** [comment]
This functionality is now available in Hades Workshop.
