### ISSUE TITLE
Music volume doesn't affect main menu music

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#301]

**Comment by barkermn01** [comment]
Just had a quick look all though the `MusicPlayer.cs` and `TitleUI.cs` (does not effect volume directly and going though all the music methods it uses does not seem to change volume without using the volume multiplier everything in `MusicPlayer` uses logic like  `SoundProfile.SoundVolume * this.Volume` or when the volume is being updated `SoundProfileSoundVolume * volume`

**Comment by snouz** [comment]
Found the issue in TitleUI.cs
Profile used for intro music was VideoMusic, since it was linked to FMV000
Fixed in patch

**Comment by snouz** [comment]
That was the wrong fix and it removes the track completely, I neglected to test again. Pushed a hotfix.
So this problem is still open.
