### ISSUE TITLE
Several sounds not affected by volume slider

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#303]
When fighting Gizamaluke the sound effect of him "splashing" in the water is too loud. Changing the sound effect to a lower volume doesn't have any effect on it. This seems a vanilla's bug but i decided to report in case this is not the case.

Report by [Felipefpl](https://github.com/Felipefpl) on https://github.com/Albeoris/Memoria/issues/294

**Comment by snouz** [comment]
"One more bug related to water splash - When Quina jumps in the water in Madain Sari the same loud sound effect splash noise heard in gizamaluke's case is heard."

"The roar of the mistodoms when kuja attacks alexandria is too loud."

Felipefpl's settings for sound are Sound - 30, Music - 25 and Cutscenes - 95, this might be a case of some sounds unaffected by volume setting

**Comment by SamsamTS** [comment]
Some sound effects didn't have volume applied to them. **Should** be resolved by https://github.com/Albeoris/Memoria/pull/256

**Comment by snouz** [comment]
Got a confirmation of this problem in an old bug report of moguri
![image](https://github.com/Albeoris/Memoria/assets/9964576/425102a0-215e-4bfb-9d8b-45eaa1a02532)

So it might at least affect: door openings, splash noises, 'whacking sounds'.
On my next test playthrough, i shall use Samsam's new sound engine and play with noises at 0% to see if that's fixed.
