### ISSUE TITLE
Add anti-aliasing option in the launcher

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#304]
Saw this setting in memoria, don't know when it was added, we need this to be in the launcher's options.

**Comment by faospark** [comment]
I requested months ago to tirlititi . he figured it was actually a lot more simpler than he thought it was.

**Comment by snouz** [comment]
I remember doing that years ago by forcing the setting in the invidia panel directly.

**Comment by faospark** [comment]
it indeed possible to use NVidia or even AMD's control panel but such method may affect typography/ type face of the game significantly. i might need to try to build this to try it. now good luck on that for me.
