### ISSUE TITLE
[Voice acting bug] Ambiant VA Multiple comma-separated files not working

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#313]
Hi,
as subject says, multiple comma-separted files in Ambiant VA is not working (at least in my PC).
In my BattleVoiceEffects.txt I have condition that should execute these files audio when triggered:

VoicePath:Battle/Steiner/Damage1,Damage2

This was done following what is stated in:
**https://github.com/Albeoris/Memoria/wiki/Voice-acting-system#user-content-Ambiant_dialogs**

_In case of multiple comma-separated files (eg. VoicePath:Battle/Zidane/Intro, IntroAlternate), a random audio will be played, with the restriction that the same ambient dialog trigger will not pick the same audio twice in a row._ 

My memoria log says:
24.02.2024 12:35:14 |M| [AssetManager] Memoria asset not found: Sounds/Voices/IT/Battle/Steiner/Damage1,Damage2.akb
24.02.2024 12:35:14 |E| [SoundLib] File not found AT path: Sounds/Voices/IT/Battle/Steiner/**Damage1,Damage2.akb**

So it seems like that it is not searching for "Damage1" and "Damage2", but for "Damage1,Damage2".
I tried using different delimiter, like ";" or whatever else, but the Memoria log tell me he can't find **Damage1;Damage2.akb**.
Also, I don't know if it is relevant, but I am using .ogg files.

Thank you

**Comment by SamsamTS** [comment]
This feature isn't available in Jun 11, 2023 release of Memoria as it has been added later as well as some others features related to battle voice system. You will need to either compile from the source code, wait for a new release or use the release available on my github.

**Comment by snouz** [comment]
> This feature isn't available in Jun 11, 2023 release of Memoria as it has been added later as well as some others features related to the battle voice system (See #252). You will need to either compile from the source code, wait for a new release or use the release available on my github.

Since this is fixed in a released commit, but just not yet compiled in a 'release version', I'm closing this ticket.
