### ISSUE TITLE
Hardcoded default names for protagonists

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#322]
Hi everyone,

first of all, I would like to thank you for this great modding tool. I am having so much fun modifying the game to my liking, so thank you, really.

Regarding the topic at hand: I am having a hard time modifying the default names of the main characters.
For example, Zidane's default name is always "Zidane," no matter what I do.

The default name is suggested when a character is to be named and is also automatically set as the character's name when the "DisableNameChoice" option is set to 1 in the memory.ini file. 

I would like to force this name to be a different one without replacing every instance of "[ZDNE]" in the .mes files. Is this possible?

Thank you

**Comment by Tirlititi** [comment]
The default names are stored in 2 different places, and you can change them in both:

1) Hard-coded in the game; Memoria provides a way to change that hard-coded name by using a feature of [Dictionary Patch](https://github.com/Albeoris/Memoria/wiki/Dictionary-Patch#user-content-CharacterDefaultName). Simply create a file ``DictionaryPatch.txt`` and write lines inside like ``CharacterDefaultName 0 US Shinigami``, then place that file in a mod folder (either create your own mod folder that you activate in the Mod Manager, or simply place that file inside the Moguri mod's folder or something like that).

2) Inside the game's dialogs. In multiple instances, the game changes a character's name by using one of the names present in almost all of the text blocks. These can be seen and modified easily with Hades Workshop: simply go to the "Environment -> Texts" panel and you'll see all the dialog blocks there. Search for the text block relevant to the part when the character joins the party and change the text that contains only the character's name there.

I don't remember which of 1) or 2) should be done in the current state of Memoria. Maybe 1) must be done for some characters while 2) must be done for other characters (for example, Vivi gets named "??????" when you first take control of him, so he may be handled differently than the other characters, regarding his default name).

**Comment by Algarad** [comment]
Oh god, I did not notice the option 1 in your wiki... I have tried it, and it works like a charm.

I have tried with the option 2 and managed to change the names of other characters like Marcus or Cinna, but it did not work for the main characters.

Thank you!
