### ISSUE TITLE
Improvement request: a better Trance system

### ISSUE THREAD

**Issue by Sefie1999AD** [Albeoris/Memoria#33]
I was wondering if you can add a feature that lets you save a Trance for later.

This is the system I was thinking of:
* add a switch to Memoria.ini: NoAutoTrance = 0
* if you set NoAutoTrance = 1, the characters won't automatically enter Trance when their Trance bar is full. Instead, it stays full until you activate the Trance
* when giving orders to a character, you can use a command or a button combo to make him/her go into Trance immediately, as long as the character's Trance bar is full.

**Comment by Albeoris** [comment]
- A new button will replace "Change Position"
- A new action will enqueued to the command queue and consume character's atb to balance this feature

**Comment by Albeoris** [comment]
**Memoria.ini**

```
[Battle]
Enabled = 1
NoAutoTrance = 1
```
