### ISSUE TITLE
Some Font choices in launcher not loaded

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#330]
![image](https://github.com/Albeoris/Memoria/assets/9964576/2c6c43d8-7056-4567-996b-b42f5b073cc0)

**Comment by snouz** [comment]
Seems like the list displayed in the launcher is not the one loaded by /Memoria/Assets/EncryptFontManager.cs (UnityEngine.Font.GetOSInstalledFontNames())

I output the list generated by it, I can't find arial black that I have selected in the launcher.
If I select a font that exists in that list, it works.

**Comment by faospark** [comment]
some thing that i noticed is the engine seems to only loads typeface/fonts with "1 word name + Bold"  if you want a bold version of the font. but for fonts that have 2+ more words in the name never really gets loaded like New Rodin PRo DB .

**Comment by SamsamTS** [comment]
To shed a little bit of light on this, turns out fonts need to be installed for all users for them to be recognized by Unity
![image](https://github.com/user-attachments/assets/503dbd09-c330-4fc1-925c-83d4ed16c518)
