### ISSUE TITLE
Daguerreo guy strange behavior

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#332]
![image](https://github.com/Albeoris/Memoria/assets/9964576/6fbeb6cb-56dd-4967-a084-722c3436d86d)

Talk to the guy with the hat walking to the left entrance in Daguerreo before he enters in the left entrance.
Enter any of the entrances there.
Go back to the main hall.
He'll be there walking against "the wall".
Talk to him and a few seconds later he'll disappear.

Reported by [Felipefpl](https://github.com/Felipefpl)

**Comment by DV666** [comment]
Fixed in #569, you can close it @snouz  :)
