### ISSUE TITLE
title_bg and gameover screens are not loadable outside sharedassets2.assets

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#333]
Unlike other textures from the same archive (world_map_full_all for example), it's not possible to include title_bg and gameover to a mod.

![image](https://github.com/Albeoris/Memoria/assets/9964576/60868057-5170-4253-a270-9f23ff2003f2)
![image](https://github.com/Albeoris/Memoria/assets/9964576/77b16b81-cfdf-4a2e-8404-8ca9da892c66)

Having a png or re-imported file with Hades doesn't change anything

**Comment by Algarad** [comment]
I have noticed the same issue, I can work on every other sprites but title_bg it is ignored.

**Comment by snouz** [comment]
> I have noticed the same issue, I can work on every other sprites but title_bg it is ignored.

Don't worry, we fixed it in my next pull request : ) These files, as well as title_logo will be loaded now.
