### ISSUE TITLE
Fraggoso HD Background Mod Compatability Request

### ISSUE THREAD

**Issue by chosenform** [Albeoris/Memoria#34]
Hey Albeoris, A lot of us would love to see these 2 mods in harmony, I know this has been requested on steam but wanted to make it more official. Thanks for working on Memoria!

**Comment by Albeoris** [comment]
https://github.com/Albeoris/Memoria/commit/00581c429a71a3ce3742010dbb0ed66384eee7b5

**Comment by IFireflyl** [comment]
Is there any update on this? I'm wanting to replay the game, and it's not fun choosing between Memoria or upgraded NPCs and backgrounds.

**Comment by lilypure604** [comment]
> Is there any update on this? I'm wanting to replay the game, and it's not fun choosing between Memoria or upgraded NPCs and backgrounds.

Would something like Moguri Mod https://sites.google.com/view/moguri-mod/ interest you? It relies on Memoria.

**Comment by IFireflyl** [comment]
> For anyone interested, Morguri Mod works perfectly. :)

**Comment by Albeoris** [comment]
Let's dwell on the Morguri Mod :)
