### ISSUE TITLE
Battle psx ui out of frame

### ISSUE THREAD

**Issue by dajoma09** [Albeoris/Memoria#340]
So the first one is an ui bug i was ignoring till now, where in battle, the turn bars and commands box are a bit outside the screen, inside the black bars. The only fix i found is using the widescreen option but i don't really like it, so i hope there's a proper fix someone can give me.

> The other one is the one i'm most worried, since Steiner is just infinite spinning on an Evil Forest cutscene: https://imgur.com/a/1pj4nH4 ----> moved to #345 

I tried changing tile size, fps, turning wide screen, but i don't really know much of these things. The only thing i can think of is deleting everything and going past it on vanilla, then installing and configuring the whole mod again. 

For context i'm using both Moguri and Memoria mods, plus High-res Chocographs, Playstation Sounds and Psx buttons (all three available through Memoria) plus Excalibur no time limit mod.

Any help is greatly appreciated!

**Comment by snouz** [comment]
Hi, I've split this into 2 issues, thanks for reporting
https://github.com/Albeoris/Memoria/issues/345

The UI stuff I'm currently working on in my ongoing pull request #331, in the meantime you can control that with values in Memoria.ini, under "[Interface]" you have a number of values for positioning, if you don't want to wait for a fix

**Comment by dajoma09** [comment]
@snouz I changed numbers on the .ini as you suggested and it works nicely! Tysm for the help ^^
