### ISSUE TITLE
Steamdeck - Fix steam overlay

### ISSUE THREAD

**Issue by niight91** [Albeoris/Memoria#342]
Mistakes were made... 

> Now we will install a hook into your OS that will launch FF9_Launcher.fix instead of the FF9_Launcher.exe file. In this case, all integrity checks of the Steam file will complete successfully. Thus, this will solve the problem that some users have periodically disabled Steam Overlay functionality, and related features: achievements and controller support. However, be careful and DO NOT DELETE the game, its folder or the FF9_Launcher.fix file without first rolling back the changes. Otherwise, the hook will remain in your system, and after a new installation of the game, you will not be able to launch it. You can roll back the changes in the launcher or manually by running Memoria.SteamFix.exe in the game folder. Are you sure you still want to continue?

I checked the box and now everything is borked. Launcher doesnt work, i can't use the executable in the gamefolder to do the rollback and ironically the steam overlay is now actually broken.

How do i manually remove the registry key? I have limited experience with Windows and obviously even less with Linux

**Comment by snouz** [comment]
Unfortunately, I don't own a steam deck, didn't participate in this feature and know nothing about registry keys, but maybe someone else can come and help you with that.
Did you try reinstalling the whole thing?
Maybe I should also add a warning on the tooltip of this feature that it only works on windows to avoid that in the future?

**Comment by niight91** [comment]
Thanks for replying to the issue, thats very nice of you!
Yes i ended up resetting the entire deck to factory settings haha, that
solved it.
But yea that would be a sort of easy 'fix' actually, just putting another
line of text in the warning telling ppl that it is not recommended to check
the box if theyre on the steamdeck

Den søn. 31. mar. 2024 kl. 19.15 skrev snouz ***@***.***>:
