### ISSUE TITLE
Cinna/Marcus/Blank not healing with tents/inns or story events

### ISSUE THREAD

**Issue by Rocket-Lawnchair** [Albeoris/Memoria#343]
I know the latest release of Memoria added a feature to make it so new characters (like Lani, Fratley and Kuja) could be healed up using healing spots/inns/tents. However this seems to have broken these features for the Tantalus characters. I've tested it and none of them get healed between their battles in Alexandria or when using tents at a save point. I can only assume inns/springs wouldn't work either. I even tried the character pack and Lani, Fratley and Kuja were all getting healed fine along with everyone.

**Comment by snouz** [comment]
@Tirlititi

**Comment by Tirlititi** [comment]
I think I fixed that issue for good in a commit after the latest release here. It took me several attempts to fix the problem for all the characters.
The fix should be included in your pre-releases, Snouz, and in [Echo-S's release](https://www.tsunamods.com/echo-s-9/), which is for now a bit ahead of the release on this github.

**Comment by Rocket-Lawnchair** [comment]
> I think I fixed that issue for good in a commit after the latest release here. It took me several attempts to fix the problem for all the characters. The fix should be included in your pre-releases, Snouz, and in [Echo-S's release](https://www.tsunamods.com/echo-s-9/), which is for now a bit ahead of the release on this github.

Would downloading the Memoria Patcher from the Echo-S website fix this issue? I don't use Echo-S myself so I don't know if their Memoria version has anything that could mess up a non-Echo-S game.

**Comment by snouz** [comment]
> > I think I fixed that issue for good in a commit after the latest release here. It took me several attempts to fix the problem for all the characters. The fix should be included in your pre-releases, Snouz, and in [Echo-S's release](https://www.tsunamods.com/echo-s-9/), which is for now a bit ahead of the release on this github.
> 
> Would downloading the Memoria Patcher from the Echo-S website fix this issue? I don't use Echo-S myself so I don't know if their Memoria version has anything that could mess up a non-Echo-S game.

I'm almost certain they just use a more recent version of Memoria, not sure which one, but it shouldn't break anything to just use their version.

**Comment by snouz** [comment]
Based on the fact it's fixed in the next release, I'm closing this, but thanks for the report!

**Comment by Rocket-Lawnchair** [comment]
Thank you for the help! Just to confirm, I downloaded the Memoria Patcher.exe from the Echo-S website, updated Memoria with that and the problem is gone. Like you said, it didn't break anything. 👍
