### ISSUE TITLE
Achievements are not unlocked

### ISSUE THREAD

**Issue by HighPingTek** [Albeoris/Memoria#348]
for some reason some achievements are not unlocked

how to kill 100 enemies
or enter trance mode for the first time

**Comment by snouz** [comment]
Hi @HighPingTek could you give me a bit more info:
- Are you on Windows?
- Do you have the steam overlay active ingame?
- Are you able to unlock other achievements?
- Did you try the button "Fix steam overlay" in the launcher?

**Comment by HighPingTek** [comment]
> CIAO@HighPingTekpotresti darmi qualche informazione in più:
> 
> * Sei su Windows?
> * Hai Steam Overlay attivo nel gioco?
> * Riuscirai a sbloccare altri obiettivi?
> * Hai provato il pulsante "Correggi Steam Overlay" nel launcher?

I'm on windows 10
I have steam overlay enabled
other achievements such as 100 rope jumps or making mogu angry have been unlocked
I tried fix steam overlay

**Comment by snouz** [comment]
![image](https://github.com/Albeoris/Memoria/assets/9964576/dd6c46fb-2a9c-4587-9247-c44aa4343c52)

**Comment by snouz** [comment]
@DV666 tested the achievements, and couldn't reproduce the bug (given the steam overlay is active and no permanent vanilla cheat is active), the achievements worked for him.
