### ISSUE TITLE
Widescreen bugs

### ISSUE THREAD

**Issue by dclem2** [Albeoris/Memoria#35]
Widescreen still has some bugs though. (In battles referring to) Spells animations are like shifted to the left of the game screen. And the help info is shifted to the left.
Title screen doesn't appear widescreen. (Black borders still present)

**Comment by snouz** [comment]
I can confirm this is still happening as of v2020.05.12
![2020-05-12 12_45_30-FINAL FANTASY IX - Map_ 2706, Loc_ 344 Name_ Pand _Hall](https://user-images.githubusercontent.com/9964576/81675088-8b152480-944e-11ea-8708-accdf0c6c137.jpg)
![2020-05-12 12_45_50-FINAL FANTASY IX - Map_ 2706, Loc_ 344 Name_ Pand _Hall](https://user-images.githubusercontent.com/9964576/81675094-8cdee800-944e-11ea-9957-fc6d5c365110.jpg)

**Comment by snouz** [comment]
There's this manual fix floating around given to me by Tirlititi:
"
1) Download the tool dnSpy,
2) Open the Assembly-CSharp.dll using that tool,
3) Search for the class "SFXMesh" and its method "End", then right-click -> Edit Method,
4) Replace the 5 first lines of the method by these (the first and last lines being replaced should be the same as the lines replacing them):
Code: [Select]
    this.mesh.Clear();
    int[] array = new int[this.ibOffset];
    Buffer.BlockCopy(this.ibIndex, 0, array, 0, this.ibOffset << 2);
    Vector3[] meshvert = this.vbPos;
    for (int k = 0; k<this.vbOffset; ++k)
        meshvert[k].x = meshvert[k].x + 50f;
    this.mesh.vertices = meshvert;
    this.mesh.colors32 = this.vbCol;
5) "Compile" then "File -> Save Module".

Maybe the SFX will still be shifted a bit in-game. If that's the case, use a different number than "50f" in the code above (use a number higher to shift to the right of the screen and lower to shift to the left).

Note that if the SFX gets fixed with the widescreen mode, it will then bug with the non-widescreen mode.
"

**Comment by snouz** [comment]
The above fix apparently replaces the first paragraph with the second on this screenshot.

![2020-05-17 13_41_53-Window](https://user-images.githubusercontent.com/9964576/82143454-5d601f00-9844-11ea-925e-6879d65756e5.jpg)

Could we detect if widescreen is active and apply the offset in consequence?

I can try to find the correct offset by trying to change the code in the way it's described there.

**Comment by snouz** [comment]
With help from Albeoris, I found the fix:

`	public void End()
	{
		this.mesh.Clear();
		int[] array = new int[this.ibOffset];
		Buffer.BlockCopy(this.ibIndex, 0, array, 0, this.ibOffset << 2);
		Vector3[] meshvert = this.vbPos;
		int offsetValue = (int)((FieldMap.PsxFieldWidth - 320) / 2);
		for (int i = 0; i < this.vbOffset; i++)
		{
			Vector3[] array2 = meshvert;
			int num = i;
			array2[num].x = array2[num].x + (float)offsetValue;
		}
		this.mesh.vertices = meshvert;
		this.mesh.colors32 = this.vbCol;
		if (SFXKey.IsTexture(this.key))
		{
			this.mesh.uv = this.vbTex;
		}
		else
		{
			this.mesh.uv = null;
		}
		if (SFX.isDebugLine)
		{
			this.mesh.SetIndices(array, MeshTopology.Lines, 0);
			return;
		}
		if (SFXKey.isLinePolygon(this.key))
		{
			this.mesh.SetIndices(array, MeshTopology.Lines, 0);
			return;
		}
		this.mesh.triangles = array;
	}`

**Comment by Albeoris** [comment]
```
	private void FixWideScreenOffset()
	{
		Int32 offsetValue = (FieldMap.PsxFieldWidth - 320) / 2;
		for (Int32 i = 0; i < VbOffset; i++)
			VbPos[i].x = VbPos[i].x + offsetValue;
	}
```

![](https://i.imgur.com/YCKQwoy.jpg)

Unfortunately, I had to roll back fix. We did not take into account that not all vertices can be shifted.

**Comment by Albeoris** [comment]
![image](https://user-images.githubusercontent.com/4787832/82500639-6c70f680-9afc-11ea-88db-c5191bbc38ae.png)

```
public unsafe static void Update()
{
SFXRender.commandBuffer.Clear();
if (SFX.SFX_BeginRender())
{
        SFXRender.primCount = 0;
        SFXMeshBase.drOffsetX = (FieldMap.PsxFieldWidth - 320) / 2;
```
