### ISSUE TITLE
Cannot find Location names sprites

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#354]
Hi,

I have managed to find and edit the texts (actually it is an image with text) that show you the name of a continent the first time you reach it (like "Lost continent", "Outer continent" etc), but I cannot find the texts that show you the name of a location (Conde Petie, for example).

I have searched almost everything in the Unity Asset viewer but to no avail. I guess what I am searching for is not a "text image": if I remember correctly, some of these textures are animated (Oeilvert entrance?).

Someone know where to find these files and if they are editable?

Thank you!

**Comment by snouz** [comment]
Hi, they're in the graphics files of each scenes they appear in, so they're in fact contained in /streamingAssets/p0data11-19. The process to edit them is not as easy as continent names, they're stored **in** the image, so like the background itself, is separated into chunks of 32/64 px put one after the other. If you're really determined to edit them, you can contact me on Discord (@ snouz), we can discuss how to do that, as there are not many other people who have the workflow ready to do that.

**Comment by Algarad** [comment]
Hi Snouz,
sorry, I am totally noob with GitHub so I did not even know how to properly reply to a closed post.

I really would like to edit them (in my mod, all the locations names are randomly generated), but I understand that deep understanding of CSharp or C++ are required, and I do not have it. I am only "decent" with Python. Thanks anyway ^^
