### ISSUE TITLE
Volume adjustment for sound FX and music

### ISSUE THREAD

**Issue by GuyInDogSuit** [Albeoris/Memoria#36]
I would love to have a way to adjust the sound via the ini (though an in-game slider would have been better but SS was lazy). The sound effects are WAY louder than the music and FMVs. It'd be great to set them to 80 and have FMV/music at 100, for example.

**Comment by Albeoris** [comment]
I will see what I can to do.

**Comment by GuyInDogSuit** [comment]
Thanks!

**Comment by Albeoris** [comment]
Done. Press **Ctrl+Alt+Shift+M** to show menu.
https://i.imgur.com/cYPncqc.png

Or you can manually set values via **Memoria.ini**
```
[Audio]
MusicVolume = 84
SoundVolume = 54
```
