### ISSUE TITLE
Having hard time reading memoria log for BattleVoiceEffects

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#361]
Hi,

maybe it's me, but I do not understand the logic of memoria logs when it say there is an error somewhere,

for example:
09.04.2024 08:44:40 |E| NCalc.EvaluationException: missing ')' at '/' at line 1:86
09.04.2024 08:44:40 |E| no viable alternative at input '/' at line 1:87
09.04.2024 08:44:40 |E| missing EndOfFile at ')' at line 1:98
09.04.2024 08:44:40 |E|   at NCalc.Expression.Evaluate () [0x00000] in <filename unknown>:0 
09.04.2024 08:44:40 |E|   at Memoria.Data.BattleVoice.TriggerOnBattleAct (.BTL_DATA actingChar, System.String when, .CMD_DATA cmdUsed, Memoria.BattleCalculator calc) [0x00000] in <filename unknown>:0 

The log message is pretty self-explanatory, but how should I interpret "at line 1:86"? There is nothing at "line 1, position 86" in the BattleVoiceEffects file, and there is nothing at line 86 either. Are these logs talking about another file?

Thank you!

**Comment by Tirlititi** [comment]
I think it will always be errors "at line 1" because it's not the whole ``BattleVoiceEffects.txt`` file that is passed to NCalc but only one-line expressions. So these error messages could indeed be improved to add more meaningful informations (like the expression that NCalc tries to parse).

**Comment by Algarad** [comment]
Ok, now is clear.
Yes, I agree that the error message can be definitely improved.
Thanks for your input! Following the previous example, I understand that I should check every row of the file on position 86 with a "/". This should be feasible with a regex.

Thank you again!

**Comment by SamsamTS** [comment]
Good point. Not really easy to give an exact location in the BattleVoiceEffects.txt but we can at least give what expression failed.

**Comment by SamsamTS** [comment]
I just made a pull request.

Here is an example of what will be logged (intentional error):
```
10.04.2024 12:00:37 |E| [VoiceActing] Couldn't evaluate condition: 'error( BattleId == 21 && AbilityId == BattleAbilityId_Steal && ItemSteal == RegularItem_MythrilDagger'
10.04.2024 12:00:37 |E| NCalc.EvaluationException: mismatched input '<EOF>' expecting ')' at line 1:104
10.04.2024 12:00:37 |E|   at NCalc.Expression.Evaluate () [0x00000] in <filename unknown>:0 
10.04.2024 12:00:37 |E|   at Memoria.Data.BattleVoice.TriggerOnBattleAct (.BTL_DATA actingChar, System.String when, .CMD_DATA cmdUsed, Memoria.BattleCalculator calc) [0x00000] in <filename unknown>:0 
```
