### ISSUE TITLE
Text Overlapping Timer UI in Widescreen

### ISSUE THREAD

**Issue by Haxabur** [Albeoris/Memoria#366]
Sorry, seen lots of widescreen issues already, perhaps this already being dealt with. 

minor issue, not a big deal but this happens with widescreen:
![FINAL FANTASY IX_2024 04 10-22 40](https://github.com/Albeoris/Memoria/assets/38482760/38722918-e856-4f72-a04c-b8de65289197)

without widescreen:
![FINAL FANTASY IX_2024 04 10-22 46](https://github.com/Albeoris/Memoria/assets/38482760/de8892ad-f4a5-46cd-aed6-d8a84be80318)

**Comment by Tirlititi** [comment]
Issue fixed with the commit [2c7071c](https://github.com/Albeoris/Memoria/commit/2c7071c045661c686eb6d05a84ff221941fa5950). We'll surely need to come back at it for 10:16 or other widescreen ratios.
Thanks for reporting the problem
