### ISSUE TITLE
Invalid using of float.TryParse

### ISSUE THREAD

**Issue by Albeoris** [Albeoris/Memoria#369]
@snouz , looks like you are missing my comment to your PR:
https://github.com/Albeoris/Memoria/pull/356/

Because of this bug, `float.TryParse` methods will return 0 in situations where the system uses a decimal separator that is different from what is passed in that method.

[ToFix] Always use `InvariantCulture` when read or write text as float/double/decimal.
```csharp
bgOverlay.orgX = Single.Parse(arguments[0], CultureInfo.InvariantCulture);
- or -
Single.TryParse(arguments[0], NumberStyles.Any, CultureInfo.InvariantCulture, out bgOverlay.orgX)
```

When parsing floating-point numbers in a programming environment, specifying `CultureInfo` is crucial because it determines the interpretation of decimal separators and group separators, which can vary widely between cultures. For example, in many English-speaking countries, the period (.) is used as the decimal separator, while in many European countries, the comma (,) serves this role. If `CultureInfo` is not specified, the parsing method will default to the current culture of the system, which might not align with the format of the input string. This discrepancy can lead to parsing errors or incorrect data interpretation.

Using `CultureInfo.InvariantCulture` ensures that the parsing process uses a consistent and predictable format, specifically a period for the decimal separator, regardless of the system's locale settings. This practice is particularly important when handling data that originates from or is meant to be compatible with multiple locales, or when dealing with standardized data formats in software applications that must operate reliably across different cultural settings. By explicitly specifying `CultureInfo`, developers can avoid subtle bugs and ensure that their applications behave consistently in diverse environments.

**Comment by snouz** [comment]
Hi Al ! Long time no see! How are you?

Thanks for you input, I don't see any comment on my pr though. I'll check tomorrow to fix that, I'm exhausted. Seems easy enough.
