### ISSUE TITLE
Some sounds are distorted at 48kHz

### ISSUE THREAD

**Issue by GuyInDogSuit** [Albeoris/Memoria#37]
Freya's Jump/Spear, some spells, etc, distort when the sound is patched to 48000 Hz.

**Comment by dclem2** [comment]
You can use the patched sdlib.dll from the "Audio Quality" thread on steam FFIX.
It won't do full justice, but the vanilla sound mod fixes it. That distorted Jump/Spear sounds like that internally.
Memoria already has features to set custom sampling rate of Sdlib.dll but it won't do the full justice.
Thanks to Memoria the vanilla sound mod comes with the patched Sdlib and all psx sfxs in the game. But it's been taking more time than usually for me.
Did all that sink in?

**Comment by Albeoris** [comment]
> Memoria already has features to set custom sampling rate of Sdlib.dll but it won't do the full justice.
Hm whar do you talking about? Sdlib.dll from "Audio Quality" and Sdlib.dll after you change sampling rate in the launcher is identical.

**Comment by Albeoris** [comment]
> Freya's Jump/Spear, some spells, etc, distort when the sound is patched to 48000 Hz.

Yes, because it 44100 Hz. You need to change it first before uprate to 48000 Hz.

**Comment by GuyInDogSuit** [comment]
Change it?

**Comment by Albeoris** [comment]
Replace original audio resources by your own.

**Comment by dclem2** [comment]
Sorry confuse Albeoris. I mean, that horrid distorted jump/spear noise sounds like that from actual sfx file. No sound like that from ps1.

> Replace original audio resources by your own.

**Comment by dclem2** [comment]
Sorry confuse Albeoris. I mean, that horrid distorted jump/spear noise sounds like that from actual sfx file. No sound like that from ps1.

> Replace original audio resources by your own.

Exactly. Okay I put up finished vanilla sound mod link on steam soon.
