### ISSUE TITLE
Speed booster doesn't speed up ATB gauges

### ISSUE THREAD

**Issue by Sefie1999AD** [Albeoris/Memoria#38]
The F1 speed booster only makes character animations faster, but the ATB gauges don't charge any faster. The booster is supposed to speed up all the actions during battles, including the ATB gauges.

This bug needs to be fixed for the following settings:

[Battle]
**Speed = 0** and **Speed = 1**
(fixing the ATB gauge progression speed isn't as important for Speed = 2, since the ATB gauges are almost always paused in the turn-based battle system)

**Comment by Albeoris** [comment]
Fixed.

https://github.com/Albeoris/Memoria/commit/4196475145dc968863e92451e55584915f4971d7
