### ISSUE TITLE
the game crashes during the last cutscenes

### ISSUE THREAD

**Issue by HighPingTek** [Albeoris/Memoria#384]
the game crashes during the last cutscenes the game crashes during the last cutscenes, I noticed that the last videos work at 15 fps and not 30 using moguri mod

[Memoria.log](https://github.com/Albeoris/Memoria/files/15049923/Memoria.log)

**Comment by snouz** [comment]
Hi, is this just after Zidane walks away from the ship in the sunset?

![image](https://github.com/Albeoris/Memoria/assets/9964576/23f9f76d-fabb-46f1-bb92-1736226451d6)

If so, this is fixed in the next version.

**Comment by HighPingTek** [comment]
yes

**Comment by snouz** [comment]
If you still get the problem (if you haven't played to the end yet), you can delete this file: 

FinalFantasyIX/MoguriFiles/StreamingAssets/ma/mbg116.bytes

But if that's just for improving the mod, thanks you, the fix is already in the next (very very soon) version : )
