### ISSUE TITLE
Animated battle background textures size is hardcoded

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#389]
Forgot add this issue when I was working on this 3y ago:

I could upscale battle textures without much trouble, and even edited their material to make make them textures more efficient. But When I upscaled any animated texture, their position would be absolute instead of relative to the size. So I did not manage to upscale them.
You can see it for example on the final boss walls.

**Comment by Tirlititi** [comment]
I think it must be a shader-related issue. It might be simpler than the [issue](352) about background transparency though.
