### ISSUE TITLE
Disable backgrounds enlargement blury filter

### ISSUE THREAD

**Issue by Aavock** [Albeoris/Memoria#39]
Hi,

Along with Tirlititi I've recently started replacing all steam backgrounds by the untouched PSX ones using the original steam resolution (32) (so I have to upscale the background x2 using nearest-neighbor interpolation).

This is the result:
- [ ] https://i.imgur.com/O0xXcIt.jpg

As we can see the background is not as sharp as the PSX version:
- [ ] https://i.imgur.com/XV7NdaK.png

Also you can see some artifacts between layers edges due to the backgrounds enlargement using some kind of filter instead of a nearest-neighbor interpolation (like FF7 and FF8).

In order to confirmed that issue I tried the 16 resolution (original x1 PSX size) and you can definitely see that the blurriness is even worse:
- [ ] https://i.imgur.com/pwuoVTl.jpg

Tirlititi suggested that this filter is probaly in the XInputInterface or UnityEngine.UI.

Is it possible to add a "raw" background enlargement option (disabling that filter) in Memoria?

**Comment by Albeoris** [comment]
I know about artifacts between layers, we fixing this issue right now.
About a blury filter... we will try to find and remove it.

**Comment by Aavock** [comment]
Awesome, thank you!

**Comment by Dotty** [comment]
Any chance for a mod, or instructions on how to do this? PS1 backgrounds look so much cleaner than the official default ones. Seeing that I really do want it.
How do you extract and replace textures?
What do you mean by 1 extra pixel? Like of solid color, surrounding color, black, transparency, or what?

**Comment by Albeoris** [comment]
Resolved in the Moguri mod:
https://sites.google.com/view/moguri-mod/
