### ISSUE TITLE
Mod Manager: unzip downloaded packages

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#396]
For the next version of Moguri, I found that compressed archives are about 3x lighter. Thus, it would save everyone enormous bandwidth if we had a way to download compressed archives, automatically unzip them.

I guess you already have access to the drive in writing since you're downloading stuff already.

@Tirlititi would it be hard to have?

**Comment by snouz** [comment]
I now realize it's already included, at least for zips, as for example AlternateFantasy is already downloaded as zip.

**Comment by Tirlititi** [comment]
Indeed.
It uses the native C# ``System.IO.Compression.ZipFile`` API, so it doesn't rely on an external dependency. On the other hand, it doesn't handle ``.rar`` archives and sometimes even some ZIP compression methods. I think it's DV that created ZIP files at some point that couldn't be unzipped by the launcher but I don't remember how it was made (and he created them again so now it's fine).
I guess it's more or less tied to Windows's native ZIP management.
