### ISSUE TITLE
Justify text of the description of the key items

### ISSUE THREAD

**Issue by Albeoris** [Albeoris/Memoria#4]
It should be automatically justify text of the description of the key items.

![ticketdescription](https://cloud.githubusercontent.com/assets/4787832/14939462/b7d5ba34-0f50-11e6-825d-61142d43077b.png)

**Comment by oxydoreduction** [comment]
Oddly enough, while this bug was occurring the first time I installed your mod, now it doesn't appear any more.

**Comment by Albeoris** [comment]
You just don't change key items text. ^_-

**Comment by Albeoris** [comment]
Now Memoria support new tag: {Justified}
