### ISSUE TITLE
Skip logos when returning to title screen

### ISSUE THREAD

**Issue by Gianluca90** [Albeoris/Memoria#41]
Hi Albeoris, first of all, thanks for the Memoria tool, it's great. 
Second, i noticed a thing: if i enable the hack to skip logos and intro movies, when i start the game i successfully skip them. But when i enter the in-game menu and select "return to title screen" (by the way, is there a way to soft-reset the game in any moment? ) , the logos are still present. 
Could you add a way to skip them even in this istance? Thanks!

PS.  I sound like a noob, but how do you unistall Memoria? Do i have to just rename the "FF9_Launcher.bak" again as "FF9_Launcher.exe" ? Or do i have to delete some file?

**Comment by North101** [comment]
@Gianluca90 In steam to uninstall it you can right-click Final Fantasy IX -> Properties -> Local Files tab -> Verify Integrity of Game Files. This will should restore FF9 back to its official release.

**Comment by Gianluca90** [comment]
@North101 Thanks for your answer! By chance, do you know if Albeoris is still working to his mod?

**Comment by Albeoris** [comment]
Yes. Still working. :D

> by the way, is there a way to soft-reset the game in any moment?

Alt+F9 to invoke the loading scene

> Or do i have to delete some file?

And return back \x64\FF9_Data\Managed\Assembly-CSharp.bak
And return back \x86\FF9_Data\Managed\Assembly-CSharp.bak

> But when i enter the in-game menu and select "return to title screen" the logos are still present. Could you add a way to skip them even in this istance? Thanks!

Are you sure you need it? Now it's by design. Same behaviour if you will wait several minutes at the Title Screen.
