### ISSUE TITLE
Adding custom language

### ISSUE THREAD

**Issue by Szebike** [Albeoris/Memoria#414]
Hy i can't add the mod my costume hungary language mod. It's change back to English everything what i installed.

**Comment by Szebike** [comment]
Unfortunately, they are no longer available. Only the translation of the game.
https://magyaritasok.hu/download/2396/final-fantasy-9

**Comment by snouz** [comment]
> NaH I just a regular player.Unfortunately, devs are no longer available. Only the translation of the game. https://magyaritasok.hu/download/2396/final-fantasy-9

Ah! Unfortunately, this is from 2016 (so I think before Memoria even existed, someone would need to adapt the mod to make it work with Memoria. I would contact the creators of this mod.

I still think we need a basic wiki tutorial for people who want to translate the game. I'll ask fellow modders.
