### ISSUE TITLE
Turn-based mode: wrong action linked to keys

### ISSUE THREAD

**Issue by Tywenn** [Albeoris/Memoria#417]
Hello there !
I found 2 issues with the turn-based mode battle.
When my character's ATB gauge is full and I have access to their action window :
If I press Y (Triangle on PSx controller) or "V" keyboard key, the character do the defense action instead of skip his turn.
If I press LT (L2 on PSx controller) or "F" keyboard key, the time isn't fast-forwarded until the next character gets a turn.

This issues occured after updating the memoria launcher with the v2024.04.28 patch.
I don't know if this has anything to do with it.

**Comment by Tirlititi** [comment]
The first issue is an intended feature (see #258). I guess it makes the status "Heat" almost always lethal in turn-based mode. It could be changed to something like "reset ATB to 0 without doing anything at all" instead, to deal with that status.

I guess we could add to the second issue that many things are not updated in turn-based mode until the next turn (eg. color changes when a status ailment is inflicted...).

**Comment by Albeoris** [comment]
> I was unhappy how turn-based worked, especially not being able to plan and confirm my next command while the current one is being executed. Now the ATB stops only when in a menu, a enemy is executing a command or if a command is already queued.

> Skipping player (menu button) wasn't working at all. This action triggers a defend command (very convenient with PSX-like HUD) unless multiple characters are ready (ie. preemptive attack).

@SamsamTS , oh. It seems like we've broken the foundation of turn-based combat (or I misread your PR description). o.o
> Now the ATB stops only when in a menu

In turn-based mode `(Speed = 2)`, the game should always stop and not continue until the player chooses an action. The mode in which ATB continues to accumulate is Fast `(Speed = 1)`. In it, the next player instantly gets a turn, and after that the ATB bar continues to move as usual. It seems that this aspect of turn-based combat did not need to be changed.

@SamsamTS , could you fix it if your changes affects the mode with `Speed = 2`?

Or turn-based mode (2) is not affected, but it's a launcher problem, and we talking about these modes?

- 3 = Simultaneous, targets can't attack, turn-order respected
- 4 = Simultaneous, targets can't attack
- 5 = Simultaneous

**Comment by SamsamTS** [comment]
> In turn-based mode (Speed = 2), the game should always stop and not continue until the player chooses an action.
That's exactly what it does. The behavior I changed is being able to enter a new command while an action is being performed but the atb still stops when the command menu is up. Before the time would stop until a command would be selected AND performed. I removed the performed part. Order is still respected.

**Comment by Albeoris** [comment]
> That's exactly what it does. The behavior I changed is being able to enter a new command while an action is being performed but the atb still stops when the command menu is up. Before the time would stop until a command would be selected AND performed. I removed the performed part. Order is still respected.

Sound valid! Then the only one question remains: how to transfer the turn from one character to another without performing actions? (question from the beginning of this issue)

**Comment by SamsamTS** [comment]
That's why I implemented the defend behavior (unless multiple players are ready, then it switches character). Before it would switch back to the same character, essentially doing nothing since the atb is stopped. So I made it so it defends, that's what's made  the more sense to me.

**Comment by Albeoris** [comment]
> Before it would switch back to the same character, essentially doing nothing since the atb is stopped. 

Hm. Nope, this worked on two keys:

V - switches available characters (one by one, the same one if no one else is available)
F - activates the next character or monster


1.
```
▰▰▰▰▰ 100% - Zidane
▰▰▰▰▰ 100% - Garnet
▰▰▰▰▱ 80%  - Enemy
▰▰▰▱▱ 60%  - Vivi
▰▱▱▱▱ 20%  - Eiko
```
V switching Zidane -> Garnet -> Zidane -> Garnet
F will fill enemy gauge to 100%

2.
```
▰▰▰▰▰ 100% - Zidane
▰▰▰▰▰ 100% - Garnet
▱▱▱▱▱ 0%   - Enemy
▰▰▰▰▱ 80%  - Vivi
▰▰▱▱▱ 40%  - Eiko
```
V switching Zidane -> Garnet -> Zidane -> Garnet
F will fill Vivi gauge to 100%

3.
```
▰▰▰▰▰ 100% - Zidane
▰▰▰▰▰ 100% - Garnet
▰▱▱▱▱ 20%  - Enemy
▰▰▰▰▰ 100% - Vivi
▰▰▰▱▱ 60%  - Eiko
```
V switching Zidane -> Garnet -> Vivi-> Zidane -> Garnet -> Vivi
F will fill Eiko gauge to 100%

4.
```
▰▰▰▰▰ 100% - Zidane
▰▰▰▰▰ 100% - Garnet
▰▰▰▱▱ 60%  - Enemy
▰▰▰▰▰ 100% - Vivi
▰▰▰▰▰ 100% - Eiko
```
V switching Zidane -> Garnet -> Vivi-> Eiko -> Zidane -> Garnet -> Vivi -> Eiko
F will fill Enemy gauge to 100%

This is the reason why there are two buttons. :D

**Comment by SamsamTS** [comment]
@Albeoris That make sense. I wasn't aware of the F key when I made the change and looking back at it I indeed removed it, unknowingly. This can easily be restored.

The situation I was talking about was, when only one person was ready (full atb), hitting V would do nothing, for example:
```
▰▰▰▰▰ 100% - Zidane
▰▰▰▰▱ 80% - Garnet
▰▰▰▱▱ 60%  - Enemy
▰▰▱▱▱ 40%  - Vivi
▰▱▱▱▱ 20%  - Eiko
```
Hitting V would not advance ATB and Zidane would be selected again for entering a command. That's the situation I changed where hitting V would defend instead of doing nothing.

In the situation above where Zidane and Garnet are at 100%, V still switches between the two with my change. In practice that almost never happens in turn-based mode and I guess that's why the F key was there.

My only issue, you have to know the F key even does that, it's not taught anywhere in the game. A new player or even a player that only played the ps1 version previously wouldn't know that. Being able to advance the ATB at will like that feels against the spirit of turn-based to me, but at the same time the game wasn't made with turn-based in mind so I'm not against it.

Maybe we want V to advance the ATB like F does in the condition I described where only one player is ready, instead of defend like I implemented or worse doing nothing like it used to. Does that sounds reasonable? Thoughts?

**Comment by SamsamTS** [comment]
Yes I agree, the F key feature should absolutely come back. The game wasn't made with turn-based in mind so some situation might require it. I'll also try V doing the same thing when only one character is ready to see how it feels.

My only concern is how to convey that information to the player. Maybe a pop-up message in combat or in the Config menu the first time after atb-mode has been activated.

As for the L1+R1 trick, if I'm not mistaken, it is impossible for the flee to occur if it's held for less than a second. The game only checks for a successful flee once every seconds.

**Comment by Tywenn** [comment]
Effectively, this "F" key feature doesn't exist in the vanilla game. I knew this while reading the battle modification page of the knowledge base of this Mod.
There will necessarily be players who will not be as curious as me so... yes. We have to find where is the best spot to inform players when the turn-based mode is activating.

For the L1+R1 trick, my bad. I spoke a little too quickly... I didn't know this 1 second check with FF9 interns mecanics. ^^'
Well. At least, I found a patch in time to make this feature appear again... Haha.

**Comment by Albeoris** [comment]
@SamsamTS 
> Maybe we want V to advance the ATB like F does in the condition I described where only one player is ready, instead of defend like I implemented or worse doing nothing like it used to. Does that sounds reasonable? Thoughts?

In my opinion, this is completely reasonable behavior. But the situation with the two characters brings us back to the question you raised.

`F`-key, `Shift+V` or something else, we need to explain to the player how to use it.

Maybe so:
1. Show a hint when player presses V in turn-based mode in first time.
2. Optionally (as a reminder), show the hint again if the player switches to the same character for the 3rd time in a row without performing any actions.

I think this will solve the problem of knowledge sharing.

By the way, it is not only in this place. For example, only few people know that by holding Shift in the equipment menu, you can equip not the best equipment, but equipment with unlearned skills, and pressing it again will fill unused slots. :)

**Comment by SamsamTS** [comment]
I was thinking maybe we can add context tips during battle. Possibly on by default with an option to turn it off (It's relatively trivial now to add new options in the in-game config). This would help new player on things that are easy to miss like Group-cast.
![Untitled](https://github.com/Albeoris/Memoria/assets/2388532/cb6195f7-294a-42b6-b43b-9f193ea761b3)
![Untitled2](https://github.com/Albeoris/Memoria/assets/2388532/a00671a7-d440-4d39-8396-cc1cca0de624)
