### ISSUE TITLE
[Task] More descriptive information on the project / engine for github main page and readme file.

### ISSUE THREAD

**Issue by Nu-Illasera** [Albeoris/Memoria#418]
Issue : Currently, the main description for this project is : "Final Fantasy IX Engine"

What does it entail, is it a full on re-write of the original engine? does it provide a rendering engine via unity?
does it have its own new audio API? bug fixes and what not? what does the patcher do?
Do you have to own a copy of the game to use the game's assets with it?

and so on (Currently, it doesn't answer the most basic questions that visitors may have when visiting this repo).
*I am not talking about the list of features and how to contribute and what not, but the main goal of this project and how does it work needs to be summed up.

Requesting to add better description to the project's information page as well as a more detailed readme file.
Providing more basic information on the engine, how does it work in general, what is the purpose of the patcher and what unique features does it have (from a technical aspect) over the original and steam version.

@Albeoris  - redirecting it to you since you are the project's leader / creator.

Thanks in advance.

**Comment by snouz** [comment]
Hi, maybe it wouldn't be a bad thing to expand a bit from the title, but my idea was that the list of feature, more or less organized by perceived importance, is already most informations that user need, but maybe there are some aspects that people might not be familiar with. I'm curious how you'd phrase it?

But yes, documentation is the last thing developers think to do, as there are still a lot of features that could be missing, so they prefer to do that instead.

**Comment by Albeoris** [comment]
Hi, @Nu-Illasera, thanks for the feedback!

## Project Overview

This project, dubbed "Final Fantasy IX Engine", is a complete rewrite of the game's engine in C#. It maintains binary compatibility with the native parts of the game and the serialized data within the game archives, allowing the compiled version to be used in place of the original DLLs. 

The primary goal of this project is to provide mod makers with a convenient framework for developing gameplay mods, replacing game assets, expand original content, localizing the game into native languages, and fixing bugs of the original.

Memoria addresses numerous bugs in the existing game port across various aspects like rendering, audio, and abilities. It includes built-in mods (turn-based battles, gameplay mechanics changes, a new card game system, cheat disablers, etc.) and provides a framework for integrating third-party mods, supporting import/export and modification of game resources.

The engine integrates seamlessly with Unity, allowing the use of features ranging from loading external AssetBundles to manual manipulation of GameObjects and Components. However, many game elements like the event interpreter or animation pipelines emulate the PSX assembler, meaning significant modifications such as importing custom models, shaders, sounds, etc., require creating workarounds to either transform external data into the game's native format or completely alter the approach by transforming game resources into compatible formats and implementing custom rendering mechanisms.

The engine introduces a new audio API, extending the native engine with the dynamic library `soloud.dll`, enhancing audio capabilities.

Memoria includes multiple components:
- **Assembly-CSharp**, **Memoria.Prime**, and **Memoria.Scripts**: These handle the core game code and battle script assembly.
- **Memoria.Compiler**: Allows users to modify **Memoria.Scripts** without an IDE.
- **Memoria.XInputDotNetPure** and **UnityEngine.UI**: Extend original assemblies by providing new APIs.
- **Memoria.MSBuild**: Aids in build process automation, including patcher packaging and dependency deployment.
- **Memoria.Debugger** and **Memoria.Injection**: Enable debugging by injecting into the game process and establishing a debugging server.
- **Memoria.Client**: Facilitates game object manipulation via a GUI similar to UnityExplorer (Alt+Ctrl+Shift+F12 to start in-game server).
- **Memoria.Patcher**: A custom self-extracting archive used for Memoria installation.
- **Memoria.Launcher** and **Memoria.SteamFix**: Components of an alternative launcher that allows use it without disabling the Steam Overlay.

### Game Ownership Requirement
To use this engine, owning a licensed copy of the game is necessary as it requires several native DLLs and a set of original assets to function properly. This ensures compatibility with all APIs and serialized data, essential for correct operation with the game's scenes and other assets.
