### ISSUE TITLE
Localization: Add support for changing place names

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#422]
When people make a translation for the game, they have to limit themselves to text (we still need a full tutorial for that), as adding place names is too complicated. It means exporting, converting, and re-importing the full background, which overwrites the content of graphics mods.

It would be great to change the code to look for tiles in specific pngs (unmixed, unlike vanilla) in a specific folder in a mod, which would take priority over vanilla ones.

**Comment by Tirlititi** [comment]
👍 That should be feasible although my experience with unmixed pngs is that they produce the same kind of visual bug as in #407 for some reason.
