### ISSUE TITLE
Request: smooth hardcoded layer movements

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#423]
On some backgrounds, Some layers are currently controlled by the original script, where the script sets a specific position every few frames. The problem is that the original position are in 320x224, so on the modern game, the movement is really blocky. I think they stand out compared to the newly smooth movements of the game.

![2024-04-15 13_20_35-FINAL FANTASY IX - Map_ 2906 (Memoria_Oblivion) _ Index_Counter_ 157_11740 _ Loc](https://github.com/Albeoris/Memoria/assets/9964576/0a813e20-6b40-457d-ab08-5bcb35c0b509)

There are several approaches to this. Either we could remove the current movement of these, and set a new function that smoothly reproduce the same movement, and manually apply it to the specific layers in specific maps in the code.

Or, and I have no idea if that's even possible @Tirlititi, we could make the script send/memoria accept decimal numbers, so instead of:

```
setTile y=1
wait 4
setTile y=2
```

we could have

```
setTile y=1
wait 1
setTile y=1.25
wait 1
setTile y=1.5
wait 1
setTile y=1.75
wait 1
setTile y=2
```

And just save the script. This might be cleaner and easier in a way.

EDIT: another possibility: set that "set layer position" in the code is divided by 4, then we have 4x the granularity in the script. But that's not very clean, if someone replaces the script in a mod, it fucks up the movement (movement will be 4x bigger)

**Comment by Tirlititi** [comment]
I see two solutions:
(1) Create a function ``MoveTileOverTime y=1..2, time=4`` and have a custom script for that field that uses that function instead.
(2) Add a hotfix in ``EventEngine`` that specifically handles these layers.

I think that for this issue, I'd prefer solution (2). I'll check how to do it unless you have a preference for (1) or another solution.

**Comment by SamsamTS** [comment]
Something useful that could be used is exponential smoothing.

Here is the basic formula :
`position += (target - position) * (1 - exp(- speed * dt))`

More info here: https://lisyarus.github.io/blog/posts/exponential-smoothing.html

**Comment by Tirlititi** [comment]
In some of the examples that Snouz showed me, the movement is not back and forth but always in the same direction, so it's better to keep linear smoothing.
