### ISSUE TITLE
Idea : Better Auto Battle feature 

### ISSUE THREAD

**Issue by faospark** [Albeoris/Memoria#431]
The game does feature and auto battle function, but its main pit fall is that it only defaults to attack.
Will it be possible for the game to use the last command/ user input is used albeit if MP, Item or Gil 0 or no command issued defaults to attack, and it persists to the next battle? 
This is similar how auto battle works ON Old Ver and Pixel Remaster releases.

**Comment by Albeoris** [comment]
In fact, I once already took the first timid steps in this direction.

Vivi has a very simple logic when auto-attacking with magic:
```csharp
        BattleAbilityId[] abilityIds = { BattleAbilityId.Fire, BattleAbilityId.Blizzard, BattleAbilityId.Thunder };
        abilityIds.Shuffle();

        foreach (BattleAbilityId abilityId in abilityIds)
        {
            if (GetAbilityState(ff9abil.GetAbilityIdFromActiveAbility(abilityId)) != AbilityStatus.Enable)
                continue;

            testCommand.sub_no = (Int32)abilityId;
            testCommand.SetAAData(FF9StateSystem.Battle.FF9Battle.aa_data[abilityId]);
            testCommand.ScriptId = btl_util.GetCommandScriptId(testCommand);

            BattleScriptFactory factory = SBattleCalculator.FindScriptFactory(testCommand.ScriptId);
            if (factory == null)
                continue;

            BattleCalculator v = new BattleCalculator(caster.Data, target.Data, new BattleCommand(testCommand));
            IEstimateBattleScript script = factory(v) as IEstimateBattleScript;
            if (script == null)
                continue;

            Single rating = script.RateTarget();
            if (rating > bestRating)
            {
                bestRating = rating;
                bestAbility = abilityId;
            }
        }

        if (bestRating > 0)
        {
            commandDetail.CommandId = BattleCommandId.BlackMagic;
            commandDetail.SubId = (Int32)bestAbility;
            caster.Data.cmd[0].info.IsZeroMP = true;
        }
```

And to detect the best target of healing magic and items:

```csharp
            BattleScriptFactory factory = SBattleCalculator.FindScriptFactory(testCommand.ScriptId);
            if (factory == null)
                return;

            BTL_DATA caster = testCommand.regist;
            foreach (KnownUnit knownTarget in EnumerateKnownUnits())
            {
                BattleUnit target = knownTarget.Unit;
                if (!allowAllies && target.IsPlayer)
                    continue;
                if (!allowEnemies && !target.IsPlayer)
                    continue;
                if (!_targetDead && target.IsUnderAnyStatus(BattleStatus.Death))
                    continue;

                testCommand.tar_id = target.Id;

                BattleCalculator v = new BattleCalculator(caster, target.Data, new BattleCommand(testCommand));
                IEstimateBattleScript script = factory(v) as IEstimateBattleScript;
                if (script == null)
                    break;

                Single rating = script.RateTarget();
                if (rating > bestRating)
                {
                    bestRating = rating;
                    _bestTargetIndex = knownTarget.Index;
                }
            }
```

There is nothing difficult here if you don’t set yourself the task of doing it perfectly.
(Oh, we spent so much time programming AI bots for Ragnarok Online! :D)

But before going down this rabbit hole, or another rabbit hole (Enemy AI), it makes sense to do a second round of BattleHUD refactoring, since the command queue still looks atrocious.

By the way, when developing EnemyAI, it is important to take into account that most battles are not difficult precisely because opponents act randomly. But if we take as an example a fight with 4 wolves in an evil forest, they can easily devour a party of a comparable level, simply by focusing their attacks on one target; and anyone who is revived by Phoenix Down will instantly be killed again. Reworking enemy AI will require rebalancing all abilities.

**Comment by faospark** [comment]
Im not asking for a very complicated  solution / logic  the way you try portray it. 
I need no AI simulation instead just take of the last command of the user input then loop. if resources for command is depleted default to attack . attack priority is simply the ordinal of the array of the enemies.  the moment you enter a town or aiships it resets. No predictions, simulations and what not. 

this is present on the OLD ver games ...ie the android relase of V and VI and all of the Pixel remaster form 1-6  . Im just looking if it can be feature . :)

**Comment by shinra358** [comment]
Firstly, I think one needs to edit the ability for the MEMORY feature in the game to persist between battles. Then it'll probably become alot more easier by telling the game to just press [confirm] rapidly on the down low when auto battle is initiated.
