### ISSUE TITLE
[Dev] Debuggable mode - instructions unclear and/or bugged

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#437]
Trying to make debuggable mode work.

I have installed unity tools on VS.

If I launch the game with debuggable ticked, I get this and it crashes.
![image](https://github.com/Albeoris/Memoria/assets/9964576/490499c0-fc49-4670-bc12-fde5f17563f6)

\x64\FF9.exe was correctly copied as Unity.exe next to it. As described in the code
![image](https://github.com/Albeoris/Memoria/assets/9964576/a4a66f4d-a6ea-4608-9dc5-1675f65f3b66)

Adding an empty Unity_Data won't work. I have to copy FF9_Data as a folder named Unity_Data for things to change: if I do that, the error disappears but it just launches the game and gives me this message
![image](https://github.com/Albeoris/Memoria/assets/9964576/f0445846-fd83-47f1-bc8a-cba25fe3799f)
But I don't have any opportunity to use VS to debug.
If then try to remove that folder, a shortcut gets created to FF9_Data when I launch again, and it launches the game normally again, I can't remove that link, but I still can't attach a process to it either.
![image](https://github.com/Albeoris/Memoria/assets/9964576/29d9494c-6855-4d8c-9875-a3c35dce232c)

Martin told me to just run his powershell script, but it did not change anything.

This ticket is to
* simply/fix the process
* add instructions on how to do it (I still can't manage)

**Comment by barkermn01** [comment]
That PowerShell set's up the environment you are correctly starting the debugger as per your second image the directory should not be empty it should be a link to the FF9_Data directory that is being correctly setup, 

it then looks like all you have to do is attach the unity debugger in VS.
![image](https://github.com/Albeoris/Memoria/assets/37368/1c50e1d2-f9bd-4e10-b198-a34f21e86bd3)

Full Guide to how to attach debugger
https://www.youtube.com/watch?v=OLWWNvabjMY

**Comment by barkermn01** [comment]
I have also updated the Wiki to explain this with Step by Step Instructions.

https://github.com/Albeoris/Memoria/wiki/Developer-instructions

**Comment by SamsamTS** [comment]
Hey I finally got it to work. I think something not mentioned, you have to compile the Memoria.Debugger project and copy the Debugger folder in Ouput into the FF9 folder.

**Comment by barkermn01** [comment]
> Hey I finally got it to work. I think something not mentioned, you have to compile the Memoria.Debugger project and copy the Debugger folder in Ouput into the FF9 folder.

i did not have to do that, i have just clean set everything up to record video's of it all and did not have to do this. 

First Vid showing a completely clean setup: https://www.youtube.com/watch?v=aaGW-ZOctiE
Second video (waiting for YT to finish processing): https://youtu.be/g7YXPuWBo-M

**Comment by snouz** [comment]
> > Hey I finally got it to work. I think something not mentioned, you have to compile the Memoria.Debugger project and copy the Debugger folder in Ouput into the FF9 folder.
> 
> i did not have to do that, i have just clean set everything up to record video's of it all and did not have to do this.
> 
> First Vid showing a completely clean setup: https://www.youtube.com/watch?v=aaGW-ZOctiE Second video (waiting for YT to finish processing): https://youtu.be/g7YXPuWBo-M

Though I confirm that when I copy that as SamSam describes, it works. I got a request to allow the debugger from windows, and the debugger works.

**Comment by snouz** [comment]
I added the necessary info in the wiki, closing this issue, thanks for the help!
