### ISSUE TITLE
title_logo previous directory doesn't work anymore

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#439]
Hello, after the latest update, replacing the game logo does not work. 
I tried two ways "StreamingAssets\UI\Sprites\US\logo.png", and "FF9_Data\EmbeddedAsset\ui\sprites\title_logo.png" and they both don't work.
![FINAL FANTASY IX Screenshot 2024 05 06 - 19 28 50 20](https://github.com/Albeoris/Memoria/assets/169078896/6a255106-0432-46c2-8b21-64c4e6dd3aee)

_Originally posted by @DragonOfTheEastUA in https://github.com/Albeoris/Memoria/discussions/402#discussioncomment-9331882_

**Comment by Tirlititi** [comment]
That's ``embeddedasset/ui/materials/title_logo``, not ``sprites``

**Comment by DragonOfTheEastUA** [comment]
@Tirlititi No, it doesn’t work from this location either.
![001409](https://github.com/Albeoris/Memoria/assets/169078896/543bdc29-4f44-4e42-93eb-47a2eeb0ea29)

**Comment by faospark** [comment]
even on english there seem to be another layer on top of title_logo
![image](https://github.com/Albeoris/Memoria/assets/11664809/87974ff2-7dd7-4624-9c02-83d695f3a45c)

**Comment by Tirlititi** [comment]
There are two yes:
```
embeddedasset/ui/materials/title_logo
embeddedasset/ui/sprites/title_bg
```
I just tested and you can replace both of them with no problem. The only thing is that ``title_logo`` must be named exactly like that, without the ``.png`` extension (like most textures) while ``title_bg`` accepts both with and without the ``.png`` extension.

**Comment by faospark** [comment]
gotcha . thanks tir 
Pro tip to modders . 
You can simply set embeddedasset/ui/materials/title_logo to a transparent object in order as this texture is mainly used for an overlay of the text of the title logo. in the manner you can further harness embeddedasset/ui/sprites/title_bg at its full capacity 
here is sample of what i did 
![title_bg](https://github.com/Albeoris/Memoria/assets/11664809/25bd3d97-0eb3-4f27-8b65-cb0e90f6e849)

**Comment by DragonOfTheEastUA** [comment]
> The only thing is that `title_logo` must be named exactly like that, without the `.png` extension (like most textures) while `title_bg` accepts both with and without the `.png` extension.

Thanks, it works.
![FINAL FANTASY IX Screenshot 2024 05 07 - 05 40 35 15](https://github.com/Albeoris/Memoria/assets/169078896/a8e81160-8006-4296-a6e9-900040f5a0aa)

@faospark That's exactly what I did before. But in the first versions of Memoria this could be done at "StreamingAssets\UI\Sprites\US\logo.png", in the latest versions the ability to do this was added at "FF9_Data\EmbeddedAsset\ui\sprites\title_logo.png". But in the latest update, both of these methods stopped working.

**Comment by snouz** [comment]
I'm changing it in the code, you'll be able to have it as title_logo, title_logo.png, and even put it in the same directory as the background, /UI/Sprites/.

![image](https://github.com/Albeoris/Memoria/assets/9964576/b75cb626-f0c8-426b-a977-56931a1d1955)

**Comment by snouz** [comment]
Now, all UI atlases are replaceable using .png.
