### ISSUE TITLE
Add option that makes a card dropped by its specific monster

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#446]
Still with a specific drop chance of course.

It would make you grind for cards in each specific zone.

**Comment by DV666** [comment]
Technically, it's already possible to do by using the BattlePatch.txt, just need to make a separate little mod with this.

**Comment by snouz** [comment]
> Technically, it's already possible to do by using the BattlePatch.txt, just need to make a separate little mod with this.
> 
> With different drop rate versions (normal, x2, x4, x8 and 100%, something like that). If you want @snouz, I can take care of it, it should be quick to do (I just need to understand how the different possible versions of a mod work).

I think that'd make a great addition IMO! if you feel like doing it of course

**Comment by faospark** [comment]
> This would be a great addition. 👍
> 
> Would be possible too to add an option to avoid grinding? It would make sense for those who played the game already several times and dont want to grind again.

kinda late response but you can do it now if you want as specific card on any battle. 
by editing or adding lines on you AbilityFeatures.txt on 
FINAL FANTASY IX\StreamingAssets\Data\Characters\Abilities


This is the formula i did for mog-addons 
```
>SA GlobalLast+
BattleResult WhenRewardAll
[code=BonusCard] GetRandom(0, 100) [/code]

```
if you want a specific card to drop on any battle you can simply specify the index of the card 
```
>SA GlobalLast+
BattleResult WhenRewardAll
[code=BonusCard] 1 [/code]

```
 youll get the fang card , replcae it with 2  and you'll get skeleton card and so on 
 0 is index 1 ,
