### ISSUE TITLE
Add cheat to obtain all in-game items

### ISSUE THREAD

**Issue by RuslanMikhlevskiy** [Albeoris/Memoria#451]
I'm working on developing a mod, and I really need this feature for testing in-game items. So, I request to include this cheat in the next update.

**Comment by barkermn01** [comment]
How should this work you enable it press a button and it automatically give you 99 of each item?

**Comment by RuslanMikhlevskiy** [comment]
> How should this work you enable it press a button and it automatically give you 99 of each item?

Yes, that's exactly right.

**Comment by snouz** [comment]
You can now install a gil multiplier and use Black Cat - Endgame Shop to shop for all obtainable items.
