### ISSUE TITLE
{Fraya} tag not working

### ISSUE THREAD

**Issue by DragonOfTheEastUA** [Albeoris/Memoria#468]
The character name is no longer displayed when using the {Fraya} tag.
(The {Freya} variant works, but all localizations and older versions of the Memoria use the {Fraya} variant.)

![20240516222428_1](https://github.com/Albeoris/Memoria/assets/169078896/9d6f6d61-c6b6-4416-b59c-05f4751a429d)

**Comment by snouz** [comment]
Isn't it Freya?

**Comment by snouz** [comment]
I'm searching for what it could be, but I can't find a single difference in the code between last release (june 2023) and current code.
![image](https://github.com/Albeoris/Memoria/assets/9964576/a46e367b-458f-4afa-bbee-09e2f917d4a7)
If someone knows, it's probably @Albeoris or @Tirlititi

**Comment by DragonOfTheEastUA** [comment]
@snouz  
At first I thought that I had an error in the save file after updating the version. But after I experimented with changing "Fraya" to "Freya" the character's name began to be displayed correctly.
![FINAL FANTASY IX Screenshot 2024 05 17 - 13 25 37 33](https://github.com/Albeoris/Memoria/assets/169078896/6030b5b2-713d-4070-9f45-a345bd1d365f)
After that I decided to check other localizations.
Brazilian Portuguese (pt_BR):
![FINAL FANTASY IX Screenshot 2024 05 17 - 13 28 36 43](https://github.com/Albeoris/Memoria/assets/169078896/440b3c02-d40d-4b3e-84bf-33b5ec139a7c)
Russian for Ffrtt (Albeoris team):
![FINAL FANTASY IX Screenshot 2024 05 17 - 13 30 09 61](https://github.com/Albeoris/Memoria/assets/169078896/117dc770-1053-492f-aa7e-4fba0941833f)
Russian for Children of Terra:
![FINAL FANTASY IX Screenshot 2024 05 17 - 13 31 25 57](https://github.com/Albeoris/Memoria/assets/169078896/5eceae32-2f44-4fc0-b6fa-fd768063cbfb)

**Comment by DragonOfTheEastUA** [comment]
> code between last release

I didn’t use the latest release before, I used the version from May 10, 2021

**Comment by snouz** [comment]
> > code between last release
> 
> I didn’t use the latest release before, I used the version from May 10, 2021

This changes everything. There were a lot more mentions of "fraya" in the code in may 2021, where it is now freya. I have 12 matches instead of 3. So that means somebody corrected it in the code and it breaks compatibility. 

I'm not about to revert an old correction that risks breaking everything. I would suggest adapting the translation (mass replace is probably not hard with something like notepad++), I'll contact dkPsyko and Albeoris about theirs. Do you agree @Tirlititi ?

**Comment by DragonOfTheEastUA** [comment]
> EDIT: I'm surprised that more recent translations like dkPsycho's are not using the more recent Memoria version.

Just checked, even the latest version uses the {Fraya} tag when exporting text.

**Comment by Tirlititi** [comment]
Yes, there was a correction of that typo at some point... I see I was responsible for that correction on this commit here: 7cf3836.
I shouldn't have done that without guaranteeing retro-compatibility issue and besides I didn't fix it everywhere it should have been if we decide to fix the typo and use Freya.

It is indeed very simple, for once, to do a mass find & replace with Notepad++ for that tag, but that requires an update of the mods and everyone is not around to make one.

**Comment by snouz** [comment]
> It is indeed very simple, for once, to do a mass find & replace with Notepad++ for that tag, but that requires an update of the mods and everyone is not around to make one. So I don't know except that we should bring back {Fraya} at least temporarily.

At least Ukrainian and Brazilian are available, Russian maybe, Polish & Chinese are unreferenced right now.

The export problem is probably because of the 3 lines where Freya is still fraya

I wouldn't a hard rollback on this, since there were several Memoria releases with the correct naming, except if you manage to make it accept both.

**Comment by Tirlititi** [comment]
Yes, I think "export as {Freya}, accept both {Freya} and {Fraya}" would be the best solution right now.
I'm working on it.

**Comment by DragonOfTheEastUA** [comment]
> Yes, I think "export as {Freya}, accept both {Freya} and {Fraya}" would be the best solution right now. I'm working on it.

Thanks, then I'll leave the {Fraya} variant for compatibility with Moguri mod.

**Comment by Tirlititi** [comment]
Done in 116e031
