### ISSUE TITLE
lvl 1 runs: remove xp from 3 last bosses

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#475]
Fix the problem with the 3 forced battles in Pandemonium are not escapable; To have the battles not give any exp or to remove the monsters immunity to any status effects, so that we can have a full lvl 1 party without having to a level 30 Zidane or 3 member having level 22, 22,23. This is for lvl 1 runs

_Originally posted by @Echokiss in https://github.com/Albeoris/Memoria/issues/390#issuecomment-2117455695_

**Comment by Trivial-Man** [comment]
If this is going to be an optional enhancement, I'd like to also request that the following enemies be potentially flagged to provide no xp for a level 1 Perfect Game:

- The unavoidable encounter with Plant Spiders after Plant Brain (with luck this encounter doesn't give enough xp to level, but no exp at all would still be nice)
- Tantarian (Running Shoes are limited and it's drop is one of the sources of them)
- Several unavoidable Bandersnatch encounters in Alexandria Castle by Beatrix (Beatrix can absorb the xp, but it would be nice to keep even temporary party members from gaining any)
- Several Mistodon encounters in Alexandria by Beatrix (some of these are avoidable, but some aren't)

**Comment by faospark** [comment]
try the no exp mod. it should block any exp you receive from enemies
