### ISSUE TITLE
[Request] Change encounter rate option

### ISSUE THREAD

**Issue by North101** [Albeoris/Memoria#48]
With the steam release, the encounter rate seems to have been greatly reduced. I'd like an option to restore the encounter rate back to the original

**Comment by Tirlititi** [comment]
It is still unclear to me how the encounter rate was lowered for the Steam version. I have no doubt that it was lowered but how?
See there for a description of the encounter rate for both PSX and Steam versions:
https://www.gamefaqs.com/boards/197338-final-fantasy-ix/55527744
https://www.gamefaqs.com/boards/197338-final-fantasy-ix/75389893

**Comment by North101** [comment]
Perhaps I'm misremembering the psx encounter rate (but I don't think I am). Oeilvert, Mount Gulug and Desert Palace just 1 had random encounters each (played through that a couple hours ago).

**Comment by Albeoris** [comment]
[Battle]
Enabled = 1
EncounterInterval = 960 ; Reduce value to increase encounter rate

https://github.com/Albeoris/Memoria/commit/2bbade4befe2a445205614c0c322216fcd6c07fe
