### ISSUE TITLE
How to modify the "G" that indicates Guil in the menu

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#483]
Hi all,

I would like to modify the highlighted "G" in the attached image. 

![image](https://github.com/Albeoris/Memoria/assets/161128234/761c54e0-da39-437b-9eb0-81a11f02a90e)

Can't find a way to do it, I'm not finding any references in the game's texts.
Anyone knows how to do it?

Thanks!

**Comment by snouz** [comment]
Mmm that should be so hard to add to the settings' ini. I'll look at it 👍

**Comment by Tirlititi** [comment]
Added an option for that in bb55ace.
It's not something you'll place in ``Memoria.ini`` but rather in the localization file.

> It is now possible to add a key ``GilSymbol`` in the ``Localization.txt`` or ``LocalizationPatch.txt`` in order to change the currency symbol. Place a ``%`` where the gil amount should be placed, so there's the possibility to have the symbol before the amount.
> 
> Example of use in a mod's ``{ModFolder}/StreamingAssets/Data/Text/LocalizationPatch.txt``:
> ```txt
> GilSymbol,[YSUB=1.3][sub]$[/sub][YSUB=-1.3]%,[YSUB=1.3][sub]£[/sub][YSUB=-1.3]%,[YSUB=1.3][sub]¥[/sub][YSUB=-1.3]%,%[YSUB=1.3][sub]€,%[YSUB=1.3][sub]€,%[YSUB=1.3][sub]€,%[YSUB=1.3][sub]€
> ```
> You may also use more characters for the currency, like ``%[YSUB=1.3][sub]mîr``, but I think it won't display so well if the gil amount is too high and thus the text width may exceed its allocated space.
