### ISSUE TITLE
Cannot uncheck "Skip battle swirl" option

### ISSUE THREAD

**Issue by lasyan3** [Albeoris/Memoria#484]
Hello there,

For some reason I cannot uncheck this option, each time I try and launch the game I can see the battle intros are still skipped, and when I quit the game the option is indeed still checked.
Also I'm a bit confused about the "swirl" and "intro". I understand "swirl" referts to the effect before the actual battle field is loaded, so this must be controlled by the "BattleSwirlFrames" setting from Memoria.ini, but the "Skip battle swirl" option from the launcher seems not to be related to that setting.

Oh I add that Moguri mod is installed, if it may have some importance.

**Comment by snouz** [comment]
Mmmh it might be bugged, it's possible.
It is indeed related to that setting, but maybe not working properly, I'll look into that. It should set 13 frame if checked, and like 100 when not, I don't remember exactly.

**Comment by lasyan3** [comment]
Ok I just realized that the setting controlling the skip of the battle intro can be controlled with the config ingame menu. And when I change it, the effect is properly changed. But still, the option in Memoria launcher keeps checked.

**Comment by SamsamTS** [comment]
The _BattleSwirlFrames_ option you can find in the _memoria.ini_, in the _Graphics_ section, controls the number of frames the swirl effect  lasts. It does not affect the battle camera intro whatsoever, this is controlled by the in-game _Skip Battle Camera_ option.

Checking the _Skip battle swirl_ on the launcher put the _BattleSwirlFrames_ value to 0 and unchecking it put it to 90.

The only think I could think of that would prevent it from being applied is if a mod is forcing its value. Each mod can have their own _memoria.ini_ which will override any settings from the main _memoria.ini_. Check if any mod have the _BattleSwirlFrames_ option in their ini file and remove the line if you want to be able to modify that option.

I am completely reworking the launcher and this is something I'd like to address. I want settings forced by mods not only be disabled (with a tooltip saying which mod forces it) but also show the value forced by the mod. The current launcher only check the main memoria.ini
