### ISSUE TITLE
Fossil roo exit path unaligned

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#486]
![2024-05-20 02_16_49-FINAL FANTASY IX - Map_ 1420 (Fossil Roo_Cavern) _ Index_Counter_ 52_5900 _ Loc_](https://github.com/Albeoris/Memoria/assets/9964576/e413ce69-65e7-4cdd-a2d2-90a8764d0542)
![image](https://github.com/Albeoris/Memoria/assets/9964576/7b2a9261-59fc-40c2-bb3c-fc38c863cc4e)

@SamsamTS I'm pretty sure this is a case of the colored text tag change

**Comment by snouz** [comment]
![image](https://github.com/Albeoris/Memoria/assets/9964576/09269723-c318-475b-bbe1-65b01654fb88)

**Comment by SamsamTS** [comment]
> @SamsamTS I'm pretty sure this is a case of the colored text tag change

Maybe? Or it could be related to layers in widescreen? I'll need to get to this point of the game.

**Comment by snouz** [comment]
Fixed both problems.
There was the offset problem that was due to a recent widescreen change, then the "xit ... E" problem was an oooold bug with the text not having enough space with this specific font (and probably some other fonts too)

![image](https://github.com/Albeoris/Memoria/assets/9964576/80337f4c-86d2-403f-8f76-e6fe0737b3a7)
