### ISSUE TITLE
Turn-based hack doesn't work when enemy is asleep

### ISSUE THREAD

**Issue by Gianluca90** [Albeoris/Memoria#49]
Hi, i have to report a bug i found while playing. I play with the turn based battle hack, and i noticed that when you put the enemy asleep, the turn based system doesn't work the way it's intended. The ATB bars begin charging normally, like in the vanilla game, and when a character gets a turn, they stop. When said character finished doing his turn, the ATB bars keep charging again, only to stop when another character gets a turn. This continue till the enemy wakes up: at that point, the battle system returns turn-based.

**Comment by Albeoris** [comment]
Hello! Unfortunately, this is the safest way to avoid freezing the game and other artifacts.
