### ISSUE TITLE
Export of text stops at "characterNameExporter"

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#498]
![image](https://github.com/Albeoris/Memoria/assets/9964576/518ec5f1-5763-4db9-a967-5b9bfad31c2e)

My guess is the recent change to Fraya/Freya

@Tirlititi

**Comment by Tirlititi** [comment]
Strange, I did tests when I made that commit and it exported correctly... provided that you don't have a mod activated that uses ``TXID`` tags (Hades Workshop uses these tags now).

**Comment by snouz** [comment]
I got it wrong I think, I'm not used to exporting. Don't bother until I figure out what is actually happening. The error message also happens on june version.

**Comment by Tirlititi** [comment]
[That line](https://github.com/Albeoris/Memoria/blob/81a15df2df34edae8e774a3c505abf8ebd374f7d/Assembly-CSharp/Memoria/Assets/Text/CharacterNamesFormatter.cs#L139)'s the culprit.
That's still my fault but from a longer time ago.
