### ISSUE TITLE
Worldmap >20fps: camera goes too far then goes back

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#499]
At 20fps (default), the camera stops when you release the button. But with more, it will not stop at the exact release but instead 1/2 frames after, then cancel the new position, which creates a sort of "stutter" that is not nice to feel.

This is the same behavior as some animations (turn), fieldmap edges, battle camera...

@Tirlititi I guess you're already aware of this behavior?

**Comment by snouz** [comment]
Here's what it looks like when I press R1 repetitively, with TPS at 10 and fps 60 (to see it better)
https://github.com/Albeoris/Memoria/assets/9964576/15214eaa-71fd-4109-8a13-5baa0f78100c

**Comment by snouz** [comment]
I guess disabling this:
![image](https://github.com/Albeoris/Memoria/assets/9964576/98de3b4e-8634-49be-ae9c-b512802b5ba1)
as soon as you release the button might work? 

OR better, the other way around, when you release the button, update the ACTUAL camera position with the one that was calculated by the smooth updater.

**Comment by snouz** [comment]
What I notice in fact, based on frame by frame footage, is that the first movement when you press the rotation button is going further by one "unit of rotation" and seem to come back by about the same amount.

**Comment by SamsamTS** [comment]
To be honest the whole 60 fps system running ahead of the tps feels pretty bad.

I played around with the movement in battle by interpolating between the previous and current tick and the jitters just disappeared (still not as smooth as I'd like but it's a start). Doing it this way means we are late by one tick at the worst, which for most things is better than having to suffer the rubber-banding.

**Comment by snouz** [comment]
One solution I was discussing with Tir is to add a percentage of delay, like for the field cam stabilizer. I'm trying to implement that as a test to see how it feels, and if I succeed, it might even make the whole problem not apparent anymore, just like the "see outside of backgrounds when you bump into borders" disappeared with it.

Tir told me the battle cam works very differently though.

**Comment by snouz** [comment]
> I played around with the movement in battle by interpolating between the previous and current tick and the jitters just disappeared (still not as smooth as I'd like but it's a start).

That's great! Do you have some footage to show already?
