### ISSUE TITLE
Phoenix Down and Life spell don't work against undead enemies (Update)

### ISSUE THREAD

**Issue by Gianluca90** [Albeoris/Memoria#50]
Me again with another bug: Phoenix Down and Life spell will always miss if used against an undead enemy. I think there's an error in some scripts, but i'm not an expert so i don't know what to modify.

UPDATE: I discover another quite serious bug related to Undead enemy/Phoenix downs/Zombie status. In the vanilla FF 9, if one tries to revive with a Phoenix Down a dead ally, and the dead ally is under the Zombie status, the Phownix Down will always miss, until a Magic Tag is used. In the patched game, the Phoenix Down will bring the Zombie character back to life, with is battle animation going on, but for all intents and purpose it will still be considered dead by the game, as he should be. That character cannot do anything, however; so, if all other 3 party member dies, and only the Zombified one remains, the game will be stuck forever on the battle screen, and even ALT+F4 won't work.  I don't know if with Life/Full Life is the same, but i think it is.

**Comment by Albeoris** [comment]
Thank you! Fixed.

**Comment by Gianluca90** [comment]
Hi, i tried the new memoria version, but i can't make your fixes work. I downloaded the new memoria version, i deleted the memoria.ini file and run the patcher again, but i have the same problem with Auto float and other support abilities. I don't know what i have did wrong, can you help me?

**Comment by Gianluca90** [comment]
I tried the new updated version, and it seems all is perfect now. I tried autofloat and phoenix down/life spell vs undead, and they work as intended, thank you very much! I will try reflectx2 as well.

PS.  when i tried fighting ozma with turn base battle it acted pretty weirdly (it gets a turn EVERY TIME an atb bar fills, making it pretty much unbeatable), could you see if you can do something for it or should i open an issue?
