### ISSUE TITLE
black screen crash just before ending (with Moguri)

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#500]
Hello! Id like to point out a problem I am having with Memoria: The final cutscene doesnt play, it just stays in black screen. It is right after Zidane takes his coat off and says "Bring my beloved dagger to me!". I posted it on reddit and it seems I am not the only one with the problem. (I tried with the latest version and the one before that, both of them dont work)

Link to my post: https://www.reddit.com/r/FinalFantasyIX/comments/1d0k2p3/black_screen_instead_of_ending_cutscene_problem/

Hopefully it can be fixed! Id love to see the entire ending sequence after the final boss fight with the Moguri video enhancement.

Thank you for your work

_Originally posted by @dennissuarezz in https://github.com/Albeoris/Memoria/discussions/479#discussioncomment-9564261_

**Comment by snouz** [comment]
Thanks for the report @dennissuarezz !

> I posted it on reddit and it seems I am not the only one with the problem

I think the people responding are confused: there was a common crash at a certain specific ending cutscene, this is fixed by last month's memoria patch.
![image](https://github.com/Albeoris/Memoria/assets/9964576/35741656-e1a5-4dce-9773-7d94d76fef3e)

But the one you're describing is entirely new.
It can happen (with or without mods) to have a random crashes. Can I ask you to try to reproduce it and share the file memoria.log? Maybe there's a resource missing or something? It looks like the penultimate FMV is just missing.

Could you check if you have this file:
![image](https://github.com/Albeoris/Memoria/assets/9964576/2dcf4fdb-2b17-4b1f-928e-5c740287efff)
there:
![image](https://github.com/Albeoris/Memoria/assets/9964576/87981ecd-80da-41ff-a6d0-8cd95537d965)

To explain in detail: in the april release, I added a function in "play" that renames that file from Moguri's folder, as it was not functioning perfectly right now.
Anyway, if you're also missing the original file from /StremingAssets/ma/, I expect indeed that the screen becomes black at that point.

**Comment by dennissuarezz** [comment]
Hello!

I have that file in the main folder, but in the Moguri folder it is named FMV059 - bugged bytes (I am guessing its on purpose). The game doesnt even really crash, it just shows a black screen. I will try unistalling everything and reinstalling again and seeing if the issue stills persists.

Thank you for your answers

**Comment by snouz** [comment]
> So for some odd reason, reinstalling everything from 0 did the trick! Sorry for bothering you guys. I wonder what the problem was...

No problem, I appreciate everyone taking the time to report something they experience! It's how we make the mods better.

For the problem itself, maybe a corruption of the original FMV? Maybe a specific set of circumstances? I have no idea
