### ISSUE TITLE
Target window didn't refresh

### ISSUE THREAD

**Issue by DV666** [Albeoris/Memoria#502]
Sometimes, when a mob "appear" on battle, the target window didn't refresh correctly.

I remember fixing this so i need to check that again.

[Video from SquallLeonHart](https://www.youtube.com/watch?v=4jlzgtBCuPY)

**Comment by Tirlititi** [comment]
Also, the behaviour in the PSX version is to keep Epitaph selected in that situation (so the cursor jumps from targeting the first enemy to targeting the second enemy when the mirror appears).

**Comment by DV666** [comment]
I think I've understood the problem, it's quite specific: basically, if the player doesn't open the target window but the enemy team changes, while still having the number of enemies, the target window is bogged (that's why the pointer didn't appear because the game is still on the first Freyja ennemy, not the second one).

It refreshes again if a player dies or if the Freyja ennemy in front of them dies but WITH the target window open.

The problem is located in UpdateTargetStates() in BattleHUD. I'm looking into improving this.
