### ISSUE TITLE
Suggestion: Dual-language support

### ISSUE THREAD

**Issue by SpicyCactuar** [Albeoris/Memoria#515]
## Dual-language support

Have the ability to toggle between two existing localisations of the game, for instance English & Japanese. Mostly interested in this for language learning purposes. This feature is more prominent among text-based genres such as Visual Novels (example: [CLANNAD on Nintendo Switch](https://www.youtube.com/watch?v=LdqcTxOdTgY)). Having said that, FFIX seems like a good target for this as not much localised content is shown simultaneously. In particular, FF games are often recommended as good resources to practice Japanese, but in the case of FFIX there are no full scripts available. External tools can be used to extract text from screenshots, though the process is quite unwieldy and slow. I believe this would vastly improve the experience for language learners.

I imagine that the following could be a good MVP:

* Change game's locale on toggle change
    * Showing an overlay text at the top-right corner with the current locale is sufficient
* Reload active text boxes (ie: contents/size/whatever additional properties are needed)
    * Examples of this are [dialogues](http://bandofgeeks.fr/wp-content/uploads/2015/08/Final-Fantasy-IX-dialogue-389x300.jpg), [menus](https://www.trueachievements.com/customimages/114639.jpg) and such
    * Notable edge cases that could be problematic are auto-advance dialogues or temporary text boxes, such as [in-battle skill usage](https://i.ytimg.com/vi/OAnYDD0PRRs/maxresdefault.jpg)
* Other locale-dependent assets are not guaranteed to be reloaded
    * Most notably FMVs, music and images
    * There could be more cases, for example the [text that appears on first arrival to a location](https://shrines.rpgclassics.com/psx/ffix/Pics/trenocity.jpg)
* Limit to 2 languages - Configurable on the Memoria launcher/Mod UI
    * Running under the assumption that the cost of toggling between any 2 locales is the same, could not be the case

I am unfamiliar with the engine's internals so it could turn out that some of the points described range from trivial to complex. For instance, loading 2 text localisations simultaneously. There are existing mods that add more translations to the game, which could be a good starting point. I would appreciate feedback on this, as well as any pointers you might have as I could look into it myself.

**Comment by Tirlititi** [comment]
Sorry, the ticket is also in the idea megathread. That's why it's closed even if it's not implemented yet.
