### ISSUE TITLE
Trance Spear sound bugged with Playstation Sounds

### ISSUE THREAD

**Issue by DV666** [Albeoris/Memoria#517]
Issue open by Quetzal from Steam about "Playstation Sounds" mod : 

> Hello, I am having a small problem with the mod: Freyas trance spear throwing is totally bugged, the sound repeats itself 2-3 times, while the battle music stops for a short time during those repetitions as if the audio engine was overwhelmed or something. Does anyone have this? In case its not known, I could make a video showing it
> 
> Btw I love the audio fixes, great job!

I test on my side and indeed, it's an issue (i didn't remember having this problem before... maybe an issue with SoLoud or something else ?)

https://www.youtube.com/watch?v=qO9AB2cV-Dc

**Comment by snouz** [comment]
@SamsamTS Your
