### ISSUE TITLE
Some support abilities don't work properly

### ISSUE THREAD

**Issue by Gianluca90** [Albeoris/Memoria#52]
Auto-Float and Reflectx2 don't work. 

With Auto-Float, characters appear above ground, but if an earth-based attack is used, the still take damage; the Float spell, on the other hand, works properly.

With Reflectx2, damage isn't doubled: i tried casting Flare on a reflected character, and the damage was the same as the non-reflected spell.

**Comment by Albeoris** [comment]
Thank you! Found it. Will fix soon!

**Comment by Albeoris** [comment]
Fixed.

https://github.com/Albeoris/Memoria/commit/0a5345069bf7b481a0cd2d50b512e93e305ab2e9
