### ISSUE TITLE
Slightly more detailed developer instructions

### ISSUE THREAD

**Issue by Tom-III** [Albeoris/Memoria#54]
Would there be any slightly more detailed dev instructions?  Like how to open in Unity?

**Comment by Albeoris** [comment]
Hi. You can't.
You can change the engine vis Visual Studio or Rider but not Unity.
Theoretically, we can restore the Unity project. But most of the objects will not be displayed in the editor. Interface only. Therefore, I do not want to spend time for this yet.

**Comment by Albeoris** [comment]
At the moment, the biggest problem is shaders. There are hundreds of them. The modern version of Unity does not allow downloading them from external files. Each shader needs to be converted to source code. The only solution I know is still far from complete.
https://github.com/spacehamster/DXDecompiler
