### ISSUE TITLE
Is there any way to convert ogg files to akb.bytes without playing the sound in the game?

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#542]
Hi,

I'm working on a mod where most of the dialogues are replaced by random words/locations/characters/insults/whatever.
Having to reach the location and/or activate the condition for certain dialogues is a pain.

It would be great for me to be able to convert the ogg files to akb.bytes without having to play the game, perhaps with an external program. 
I can try generating the .ogg files directly with the AKB header, but I don't know how difficult that would be.

Thanks!

**Comment by SamsamTS** [comment]
Please use the Discussions section for those type of questions.
