### ISSUE TITLE
Ambiant dialogue based on HP%

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#543]
Hi,

I am trying to create a condition that triggers when a character receives heals when under a specific health percentage, let's say 50%.

I am using:
`CheckAnyStatus(CurrentStatus, BattleStatus_LowHP)`
but this triggers when health goes yellow (15%?).

It should be possible wiwth NCalc flag TargetHP, but I cannot manage it to work. Any suggestions?

Thanks!

**Comment by SamsamTS** [comment]
This isn't the place to ask for help, this is to report bugs. Please use the Discussions section.

**Comment by Algarad** [comment]
Sorry, will do.
