### ISSUE TITLE
letterbox textures not replaceable by mods

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#547]
\FF9_Data\EmbeddedAsset\ui\sprites\overlay canvas\letterbox_horizontal
\FF9_Data\EmbeddedAsset\ui\sprites\overlay canvas\letterbox_verticle
are note replaceable by mods.

Old moguri replaced these directly in .assets in vanilla, which we're trying to avoid.

These files control the textures of the empty space around screens. Meaning it's non-widescreen users who are impacted.

**Comment by Tirlititi** [comment]
The changes I made could be improved further: for now, there's the possibility to use black bars instead of the grey texture, but there's currently no way to use any other texture for these parts "out of the screen".
