### ISSUE TITLE
Mod Manager: assign automatic priority index to mods (in ModCatalog) & automatically sort them

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#555]
If we do that, we can also remove the "move up"/"move down" buttons

**Comment by snouz** [comment]
If we do this, we have to make sure it won't cause a problem for mod makers, or mods not in the catalog

**Comment by faospark** [comment]
> If we do that, we can also remove the "move up"/"move down" buttons

just a suggestion , the move up and down arrows can still serve as manual override. vortex mod manager (though not all games) and 7th heaven while has auto priority still has those arrows in the event emergencies or  new has a dependency to another mod

**Comment by snouz** [comment]
Done
