### ISSUE TITLE
4:3 mode does not work

### ISSUE THREAD

**Issue by DragonOfTheEastUA** [Albeoris/Memoria#557]
The game no longer works in 4:3(5:4) mode

1280x1024(5:4)
![20240618234934_1](https://github.com/Albeoris/Memoria/assets/169078896/95c77164-6286-49a1-82af-15f00d98237a)

**Comment by snouz** [comment]
You can just disable the widescreen option in the launcher, it will look like this in 5:4

![image](https://github.com/Albeoris/Memoria/assets/9964576/05e94090-db4e-470e-9528-9dfb2845aa98)

What changed is just that there used to be a check on widescreen to see if the screen is exactly 16:9, then when I expanded widescreen to every possible resolution above 4:3, I removed the check entirely.

**Comment by DragonOfTheEastUA** [comment]
I usually use the original launcher for the achievements and overlay to work, but I just checked it doesn't work the same when launched through the "Memoria launcher".

![Знімок екрана 2024-06-19 082300](https://github.com/Albeoris/Memoria/assets/169078896/56d84a93-caa2-4a1e-9112-76ae4d11c83f)

**Comment by DragonOfTheEastUA** [comment]
@snouz Maybe this is due to the fact that you are using 4:3 windowed mode on a monitor that is physically 16:9, but I actually have a 4:3 (5:4) monitor?

**Comment by snouz** [comment]
> Maybe this is due to the fact that you are using 4:3 windowed mode on a monitor that is physically 16:9, but I actually have a 4:3 (5:4) monitor?

This should not change anything, I tested fullscreen too, and the game is framed correctly (with grey bars above and under). If you're not using the launcher, you can simply change WidescreenSupport to 0 in Memoria.ini.
But I'll re-add the check for resolution "squarer" than 4:3. I confess I did not have this resolution in mind when I removed the check (despite the fact I used to have one)
