### ISSUE TITLE
Do not replace the original launcher

### ISSUE THREAD

**Issue by DragonOfTheEastUA** [Albeoris/Memoria#559]
From the very first acquaintance with the Memoria, I didn’t understand what the point was in replacing the original launcher, because most ordinary players use it once or twice after installing the Memoria, and replacing it causes problems with the Steam overlay and achievements.
Yes, I know about the existence of Memoria.SteamFix.exe, but it does not work for everyone, and when uninstalled incorrectly, people often receive an "Executable Missing" error.
In addition, for some reason, memoria launcher adds entries to Settings.ini that are incompatible with the original launcher.

Actually, the question is this: is it possible to rename the Memoria launcher, for example, to “Memoria configure” and not replace the original launcher?

**Comment by snouz** [comment]
TODO: remove the " | 16:9" in settings.ini
