### ISSUE TITLE
No pitching sound effects~speed boost

### ISSUE THREAD

**Issue by dclem2** [Albeoris/Memoria#56]
If it's possible, to not have the sfxs pitch while using speed booster; currently breaks vanilla sounds fix mod.

**Comment by Albeoris** [comment]
Please explain in more detail.

**Comment by dclem2** [comment]
Some sfxs including spell Holy, Doomsday, Bahamut, Madeen, Phoenix, Carbuncle and many other summon sfxs and various fixed environmental sfxs don't match match (firstly) due to the 15 fps battle frame rate (easily solved with Memoria set to 30 fps); yet, speed booster pitching the sfxs makes it play too fast for the animation frame.

**Comment by Albeoris** [comment]
Hm... I will see. Thank you.
