### ISSUE TITLE
Very frequent freeze when confirming quitting

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#561]
This has been an annoyance of mine for years.

**Comment by SamsamTS** [comment]
I might have found a solution.
By not broadcasting the "OnQuit" event the game closes significantly faster, near instantaneous (on my end at least).

I don't know if there are drawbacks from doing that but we are quitting, windows clears up everything already anyway so why bother do some useless cleanup?

**Comment by Tirlititi** [comment]
It looks like broadcasting the "OnQuit" even only concerns the sound API (a call of ``SdSoundSystem_Release``). If there's a drawback to not call it, that's what it would concern, most likely.

**Comment by SamsamTS** [comment]
Okay I'm not sure not broadcasting the "OnQuit" event did anything.

However I opted for the nuclear option: DestroyWindow (user32.dll). This closes the application instantly, even in battle.
