### ISSUE TITLE
Gambits~Conditional Command Triggers

### ISSUE THREAD

**Issue by dclem2** [Albeoris/Memoria#57]
Since Memoria is the epitome of what's possible now :); would it be possible to add an additional Menu option titled: 'Gambits'? Players can set character gambits; condition based as:

Ally: HP < 100% | Target ally with less than 100% HP.
-- | --

Ally: HP < 90% | Target ally with less than 90% HP.
-- | --

Ally: status = Stop | Target any ally with Stop status.
-- | --

Foe: party leader’s target | Target any foe targeting the party leader.
-- | --

and the like. New menu, suitable for Gambits; and a section where one could put artwork of each character too. Artwork files (preferably .png) stored within the archives (sharedassets.assets files), Could it be possible, wherein?

**Comment by Albeoris** [comment]
Yes, this is possible, but for this we need a new UI engine.
Something similar has already been done for healer characters (with the Healer ability/Rod), now they choose zombie targets and characters with reduced health, rather than ordinary enemies.

**Comment by dclem2** [comment]
Excellent; I could aid in a new UI engine, no less, if needed. I noticed too with the healer characters, it was very similar. Gambits would aid greatly in situations such as level grinding, and the like.
