### ISSUE TITLE
Flame missaligned in Palace/Fire Chamber

### ISSUE THREAD

**Issue by SamsamTS** [Albeoris/Memoria#574]
![image](https://github.com/Albeoris/Memoria/assets/2388532/235956c5-ab02-4a10-bea3-8a014bf1f511)

**Comment by snouz** [comment]
About alignment: some candle lights are slightly misaligned, but you can't currently be more precise than 1 PSX pixel. But I'm planning to make their position a float in DoEventCode, so that we can adjust them on the fly there.
