### ISSUE TITLE
Ultrawide: first scene bugged

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#582]
![image](https://github.com/Albeoris/Memoria/assets/9964576/5307a601-534f-48b2-b8ed-0b6569570ac1)

**Comment by knghtbrd** [comment]
To clarify, just deselecting widescreen at the memoria launcher should do all that needs doing? Or, now that I'm past this, there aren't other known problems?

**Comment by snouz** [comment]
> To clarify, just deselecting widescreen at the memoria launcher should do all that needs doing? Or, now that I'm past this, there aren't other known problems?

I suggest keeping widescreen, but selecting a 16:9 resolution. That way you keep the benefits of widescreen with a resolution/ratio that has been duly tested.
