### ISSUE TITLE
Steam overlay dosen't work

### ISSUE THREAD

**Issue by Marlle** [Albeoris/Memoria#59]
Both big picture and standard overlay dosen't seem to work

**Comment by Albeoris** [comment]
Remove a new "FF9_Launcher.exe" and rename "FF9_Launcher.bak" to "FF9_Launcher.exe".
Idk why it's going on.

**Comment by polt13** [comment]
I tried this and it still doesn't work, actually Memoria is replaced if I do this for some reason.

**Comment by Albeoris** [comment]
Fixed https://github.com/Albeoris/Memoria/commit/4a66268eb0db9be99e873126b5b5dd346af8d825

**Comment by Albeoris** [comment]
Nope, it didn’t help.

**Comment by LoveIsDarkness** [comment]
My Steam Overlay started working in the game.

**Comment by Skyyblaze** [comment]
I have the same issue.

I recently got FFIX in the Steam Summer Sale and installed Moguri 8.0.1 which apparently features an older Memoria version. The overlay and my DS4 work fine with it however as soon as I add Scaled Battle UI to the mix the newer Memoria version of it causes the overlay and thus my controller to not work anymore. I'll try the fix above and report back if it works for me.

**Comment by Skyyblaze** [comment]
Yeah I can confirm this works for me too! :D Out of curiosity since this seems like a weird workaround, why does this work?

**Comment by AndrewLoughran** [comment]
Regedit fix worked great for fixing the Steam overlay which in turn allowed my Steam Controller to function normally. Thanks!

**Comment by Albeoris** [comment]
> 
> 
> Yeah I can confirm this works for me too! :D Out of curiosity since this seems like a weird workaround, why does this work?

There is some kind of binding to the original launcher. If the launcher is changed, the overlay stops working from time to time. This is probably some kind of integrity check.

This method leaves the original file in place, and the check returns no error.
I still don't fully understand the problem, but I'm glad the workaround works. :)

**Comment by Albeoris** [comment]
Done. Now you can click "Fix Steam Overlay" in the launcher to make the hook automatically.
https://github.com/Albeoris/Memoria/commit/0d5c3e89957352bba59894e3dc9dadcbda417d12
