### ISSUE TITLE
Improve character display in shops

### ISSUE THREAD

**Issue by DV666** [Albeoris/Memoria#593]
I think it would be a good idea to make all the characters appear in the `Shop/Synthesis` menu.

Maybe something that automatically switches between several character lines, or that displays only the characters concerned... or a mix of both.

Will see !

![image](https://github.com/Albeoris/Memoria/assets/17729817/6ae59ce7-d44c-480f-98af-a2e83984c1a6)

**Comment by Tirlititi** [comment]
You can already see the other characters using L1 / R1 buttons (left / right bumpers), although there's no visual clue that you can do that yet. It would be nice to add something like an arrow + the button's icon when that can be done.

**Comment by snouz** [comment]
Note that it also doesn't display character already unlocked but not currently in the party.

![image](https://github.com/Albeoris/Memoria/assets/9964576/344b4bb4-5d61-4153-a530-5790220127d0)
