### ISSUE TITLE
Background extracting and reimporting

### ISSUE THREAD

**Issue by Aureliaar** [Albeoris/Memoria#6]
Hi;
I'm also attempting to reconstruct & reimport the atlas resources for the backgrounds.

Would you happen to know if it's standard unity megatextures, and have you made any progress on full reconstruction? I've managed to break it into fragments, but no trivial recompositing effort was successful.

**Comment by Albeoris** [comment]
When I have some free time, I will try to reorganize tiles.

**Comment by Albeoris** [comment]
Resolved in https://github.com/Albeoris/Memoria/commit/a7c0fc1744ae1dd19631ba0c77789b42e45cc783
