### ISSUE TITLE
Hide Minimap

### ISSUE THREAD

**Issue by yariefw** [Albeoris/Memoria#608]
Is there an option to hide the minimap by default when you load up the game? I know I can toggle it in-game by pressing Select multiple times and hide it that way, but it comes back when loading from a save and it gets kinda annoying having to do it every time.

I searched [Memoria.ini sections](https://github.com/Albeoris/Memoria/wiki/Memoria.ini-sections) and Issues but found nothing.

**Comment by snouz** [comment]
The best would be to have it in the save data maybe. Or as you say, a setting in memoria.ini, but maybe that's a bit overkill for something (no offence) pretty minor

I think the first priority would be to at least fix the position of it, which is not adapted to widescreen at all.

**Comment by Tirlititi** [comment]
Fixed in the commit db422ea
