### ISSUE TITLE
Change font from CIL code directly 2

### ISSUE THREAD

**Issue by dclem2** [Albeoris/Memoria#63]
(**I don't know if I can comment on a closed issue; if can tell me, no have keep posting new (not) issue**).

**Albeoris**, please show me _**exactly**_ how to change the font from the CIL code **please**; I want to learn & do it on my own. Please, give more details.

**Comment by Albeoris** [comment]
Yes, you can comment on a closed issue.

Sorry man, but your question doesn't apply to this project.
You can easily find the answer in Google.

**Editor:** https://github.com/0xd4d/dnSpy

**Comment by dclem2** [comment]
yes it does Albeoris. It's all related ff9; you're the only one who managed to change the font, yet you want to hide how you did it. Why? I want to know how you changed the font through the code. I thought of you as kind generous to help all questions, was I wrong?
And no, I cannot simply find the answer with google; this is related to Memoria~ff9 specifically, I need to ask one who's familiarized himself with ff9's line of code, which is very different from any other code.
Please tell me how you changed the font through the code, Albeoris; I love using Memoria to the end, but I also want to learn the code myself too.

**Comment by dclem2** [comment]
Alright then! You're in C# not C++ I'll keep 'wall' trying solo here then. If I can't get it; then i hope for more compatibility with Memoria.
