### ISSUE TITLE
Accessibility: Easier sword play minigame.

### ISSUE THREAD

**Issue by dfmodius** [Albeoris/Memoria#630]
Please add some way to manipulate the number of nobles impressed, and whether Queen Brahne is impressed in the sword play minigame. This could either just focus directly on the result or simply relax the constraints on mistakes or reaction time. Either is perfect IMO.

**Comment by snouz** [comment]
Why not, I never found it particularly difficult, compared to the button mashing of Hippo or the jump rope, but some people might struggle with reflexes.

**Comment by dfmodius** [comment]
Thank you, really appreciate it.

**Comment by barkermn01** [comment]
Would be good if this was a cheat slider for number of impressed, some people i know aim for specific items from it.

**Comment by snouz** [comment]
> Would be good if this was a cheat slider for number of impressed, some people i know aim for specific items from it.

For info, Tir told us he added that feature in his next PR. Added an option to remove the time limit, and another to make the calculation like the PSX version.

**Comment by dfmodius** [comment]
You rock, @Tirlititi! Thank you so much!
