### ISSUE TITLE
How to update Memoria on Linux/Steam Deck?

### ISSUE THREAD

**Issue by Kaomojis** [Albeoris/Memoria#631]
Unfortunately when I try to run the .exe files through Bottles, nothing happens. Is there any way to update Memoria on Steam Deck, which uses Linux?

**Comment by snouz** [comment]
Hi Kaomojis, thanks for the report, does it work if you tick "check for updates in the launcher?
I/someone should really make a battery of tests in a virtual machine one day.
Also, does it work if memoria patcher is in the FFIX directory?

**Comment by Kaomojis** [comment]
Sorry for the late response, I just hadn't had time to load up my Deck until now.

However, I don't see a option to check for updates in the launcher - I downloaded Memoria with Moguri Mod, so I'm pretty sure it's a older version. 

I haven't had the chance yet to try it with the patcher in the directory, I will give that a try and see if that fixes it when I can.

**Comment by snouz** [comment]
> Sorry for the late response, I just hadn't had time to load up my Deck until now.
> 
> However, I don't see a option to check for updates in the launcher - I downloaded Memoria with Moguri Mod, so I'm pretty sure it's a older version.
> 
> I haven't had the chance yet to try it with the patcher in the directory, I will give that a try and see if that fixes it when I can.

Hi, did you manage to patch the game?

**Comment by Kaomojis** [comment]
Unfortunately not. :( I'd placed the memoria patcher in the directory, but that doesn't seem to work.

**Comment by snouz** [comment]
@Kaomojis Did you try following this guide?

https://steamcommunity.com/sharedfiles/filedetails/?id=3068861646

Also, we recently noticed that the patcher can't find the path if you haven't launched the game once from steam.
