### ISSUE TITLE
Multiplayer support?

### ISSUE THREAD

**Issue by thecabbage86** [Albeoris/Memoria#64]
Hello,

The original PS version of FFIX had some limited multiplayer support where you can split control of your party members during battle between the two controllers. I was wondering if it would be possible to mod the PC version to include this feature and what level of effort might be required?

I may be interested in lending a hand for such an effort, although I don't have any modding experience yet.

**Comment by Albeoris** [comment]
Yes, it can be done, but these changes are comparable to the full implementation of multiplayer. I would like to start with a multiplayer card game.

**Comment by Albeoris** [comment]
Now it becomes clear that without additional community support and a complete change of the engine, this is impossible to implement.
