### ISSUE TITLE
Faster menu browsing speed

### ISSUE THREAD

**Issue by TailsGuy** [Albeoris/Memoria#649]
Scrolling the menu is sluggish, it would be nice to be able to go fast like you can in the PSX version and not have a delay before long to the next option, it really slows things down. Even in the battle menu it's like this.

**Comment by snouz** [comment]
Do you have the latest version? This was introduced in this version

https://github.com/Albeoris/Memoria/releases/tag/v2024.05.19

Delay configurable, and by default reduced from 300ms to 40. But maybe you're talking about something more specific?

**Comment by TailsGuy** [comment]
Really? I'll go check now I wasn't aware. I'll see if this is what I was talking about.

**Comment by TailsGuy** [comment]
Yeah I don't see anything actually. I'm on the latest version, there's no settings in the Memoria.ini that refers to any menu delay being configurable.

**Comment by TailsGuy** [comment]
Here's a comparison between PSX and Memoria right now with what I've been trying to convey.

https://github.com/user-attachments/assets/ef910560-4a8e-42c9-a269-90a66370c44b

https://github.com/user-attachments/assets/28cc5d83-0de3-482d-b732-10ca808f3b5b

**Comment by snouz** [comment]
> Yeah I don't see anything actually. I'm on the latest version, there's no settings in the Memoria.ini that refers to any menu delay being configurable.

It's actually in [Interface], FadeDuration.

**Comment by TailsGuy** [comment]
Thanks, but I was actually talking about the cursor itself being delayed between other options in menus.
That's a really good feature though and I just made use of it.

**Comment by snouz** [comment]
> Thanks, but I was actually talking about the cursor itself being delayed between other options in menus. That's a really good feature though and I just made use of it.

I'm still not following. I tried with a mouse and with a controller, menu browsing is instant. Selecting items, etc. You'll have to be more specific, I don't notice any delay anywhere.

**Comment by TailsGuy** [comment]
> > Thanks, but I was actually talking about the cursor itself being delayed between other options in menus. That's a really good feature though and I just made use of it.
> 
> I'm still not following. I tried with a mouse and with a controller, menu browsing is instant. Selecting items, etc. You'll have to be more specific, I don't notice any delay anywhere.

I'll try and record it, give me a moment.

**Comment by TailsGuy** [comment]
https://github.com/user-attach

https://github.com/user-attachments/assets/133dedc1-4820-42e4-a150-2415cc0abf5a

ments/assets/9bba0b02-2573-42e4-b810-01f9625e2d37

**Comment by snouz** [comment]
If I understand correctly, this is about the browsing speed of the menu, as well as the speed of the first "acceleration" when pressing up or down.

**Comment by TailsGuy** [comment]
> If I understand correctly, this is about the browsing speed of the menu, as well as the speed of the first "acceleration" when pressing up or down.

Yup, that's what I mean. Apologies for not being able to explain properly.

**Comment by JazzDemon** [comment]
> If I understand correctly, this is about the browsing speed of the menu, as well as the speed of the first "acceleration" when pressing up or down.

Also if I may add to this we should look to remove the slight period of 'no input allowed' just after every tap on the dpad. So for example you could tap 5 times down but, find only 3 of those inputs have registered if done too quickly. It's maybe a few milliseconds between each tap that one needs to wait but enough to notice (which the PSX version did not have).

**Comment by TailsGuy** [comment]
> > If I understand correctly, this is about the browsing speed of the menu, as well as the speed of the first "acceleration" when pressing up or down.
> 
> Also if I may add to this we should look to remove the slight period of 'no input allowed' just after every tap on the dpad. So for example you could tap 5 times down but find only 3 of those inputs have registered if done too quickly. It's maybe a few milliseconds between each tap that one needs to wait but enough to notice (which the PSX version did not have).

Exactly what I was thinking.
