### ISSUE TITLE
EntryPointNotFoundException Gray screen, game won't load. No error but no memoria.ini

### ISSUE THREAD

**Issue by mcabel** [Albeoris/Memoria#66]
Like somebody in the messageboards, the Memoria.patcher.exe did not work anywhere but the actual ff launcher directory.

I checked the log, and might be a windows 10/8 thing, because I ran the patcher in CMD and it truncated the directory to/Final/ rather than /Final fantasy IX/. As a workaround, I renamed the directory Final and it seemed to patch successfully, but no memoria.ini and no errors on memoria.log. Also the memoria launcher did not start.

I checked the output_log and possibly the directory was hardcoded for /final fantasy IX/, so I renamed again the directory to /Final Fantasy IX/. Now the Memoria launcher runs, but when I put x64 it shows a grey screen. When I put x86 it shows a black screen.

The error on the output log seems to be:

>  EntryPointNotFoundException: SteamAPIRestartAppIfNecessary
> at (wrapper managed-to-native) SteamSdkWrapper:SteamAPIRestartAppIfNecessary ()

I tried reinstalling and did not work.

Maybe I could try using someone else's memoria.ini, if someone can upload it, to test.

**Comment by Albeoris** [comment]
You're using the old version of the game. Install the latest updates. ;)
