### ISSUE TITLE
field 1207 - garnet teleporting (just after clayra loses tornado)

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#666]
https://github.com/user-attachments/assets/e2bfe956-9b06-4aca-9596-c314a781a2b2

https://github.com/user-attachments/assets/a04716ad-09ed-4402-b9c4-29e0930bc46b

**Comment by Tirlititi** [comment]
I'll take that one.
The movement is actually coded in the animation itself and Garnet is moved instantatly between each animation loop (4 times when she walks toward us and 2 times when she walks on the right).
