### ISSUE TITLE
Sword Magic casting names

### ISSUE THREAD

**Issue by Tirlititi** [Albeoris/Memoria#67]
Hello,
In French, Italian and Spanish, the names of the Sword Magic spells, as they are displayed upon casting, are messed up (it is a bug of the Steam version). This is because they used the English/Japanese formatting that appends the "BattleCommandTitleText(0)" while it should be prepended in those three languages.

Instead of having "Epée Brasier", we have "Brasier Epée " in French, for instance.

Here is a suggestion for fixing that bug. It's for the method "BattleHUD::SetBattleCommandTitle" or, for Memoria, ["BattleHUD::FormatMagicSwordAbility"](https://github.com/Albeoris/Memoria/blob/master/Memoria/Engine/Battle/BattleHUD.cs#L680) (only replace the "return" line).

```
if ((Localization.GetSymbol() == "FR") || (Localization.GetSymbol() == "IT") || (Localization.GetSymbol() == "ES")) {
    return FF9TextTool.BattleCommandTitleText(0) + abilityName;
}
return abilityName + str2 + FF9TextTool.BattleCommandTitleText(0);
```

**Comment by Albeoris** [comment]
Hmm... You missed the space. :)

**Comment by Tirlititi** [comment]
Not really, the space is already in the "FF9TextTool.BattleCommandTitleText(0)" in those languages. Adding another one would make it weird.

Nice to see you're back btw.

**Comment by Albeoris** [comment]
Got it! Thanks! :)
I'll fix it as soon as Visual Studio is installed.

**Comment by Albeoris** [comment]
```
    private static String FormatMagicSwordAbility(CMD_DATA pCmd)
    {
        // TODO: Move it to an external file
        String abilityName = FF9TextTool.ActionAbilityName(pCmd.sub_no);
        
        String result;
        if (TryFormatRussianMagicSwordAbility(abilityName, out result))
            return result;

        String commandTitle = FF9TextTool.BattleCommandTitleText(0);

        switch (Localization.GetSymbol())
        {
            case "JP":
                return $"{abilityName}{commandTitle}";
            case "FR":
            case "IT":
            case "ES":
                return $"{commandTitle}{abilityName}";
            default:
                return $"{abilityName} {commandTitle}";
        }
    }
```
