### ISSUE TITLE
Worldmap: when on route to Oeilvert, minimap displayed, bugged

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#670]
When you're dropped off by the ship to the forgotten continent by Zorn&T, the minimap is displayed, but with default position (not corrected one in corner) and with wrongly positioned unmoving cursors.

![image](https://github.com/user-attachments/assets/10546bee-f964-4c39-a67a-7f66ba1f3713)

Press select and you get into the functioning one.

![image](https://github.com/user-attachments/assets/e1e54f60-eee3-4953-8dce-1aa43ac75194)

**Comment by Tirlititi** [comment]
I'll take that one
