### ISSUE TITLE
"SoundLib mbg119 not found" error

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#679]
07.08.2024 06:08:48 |M| Map: 2931 | Scenario counter: 11770
07.08.2024 06:08:57 |E| [SoundLib] mbg119 not found!
07.08.2024 06:09:02 |M| Map: 2930 | Scenario counter: 11770

**Comment by Tirlititi** [comment]
That's not a problem. The mbg119 doesn't have an associated sound/music [like many others do](https://github.com/Albeoris/Memoria/wiki/List-of-cinematics). The sound of the Hilda Guard III landing is handled by the field script; I just compared with the PSX version and there's no missing sound effect during that cinematic.
We could suppress the "Error" statement for that MBG and the few others with no associated audio but that's a minor issue.
