### ISSUE TITLE
Some errors on disc change

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#687]
07.08.2024 07:45:59 |M| Map: 768 | Scenario counter: 3900
07.08.2024 07:46:00 |M| [AssetManager] Memoria asset not found: FieldMaps/invalidFieldMapID/atlas
07.08.2024 07:46:00 |M| [AssetManager] Memoria asset not found: FieldMaps/invalidFieldMapID/0000.tim
07.08.2024 07:46:00 |M| [AssetManager] Memoria asset not found: FieldMaps/invalidFieldMapID/invalidFieldMapID.bgs
07.08.2024 07:46:00 |W| Could not find the Music with Id 136
07.08.2024 07:46:02 |M| Changing to disc_id: 1
07.08.2024 07:46:09 |M| Map: 800 | Scenario counter: 3900

**Comment by Tirlititi** [comment]
That's not a problem. That's the infamous [field 70](https://github.com/Albeoris/Memoria/wiki/List-of-fields) (Opening) that is the only field without any background (I think there's a walkmesh but I'm not even sure of that). It's used to launch the opening cinematic and the cinematic that closes the disc 1. The game is adjusted to take that into account and there is no consequences.
