### ISSUE TITLE
Some people can't render battle realistic shader (might be AMD related)

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#688]
2 people with AMD GPU confirmed the same problem, while Nvidia players don't seem to encounter that problem

![image](https://github.com/user-attachments/assets/143fc4a2-2e00-4cce-baa7-669453732c6f)
![image](https://github.com/user-attachments/assets/780b3eee-a895-4c69-a30b-dd35afcaf8cd)
![image](https://github.com/user-attachments/assets/bd1bc9e7-36b7-4387-87ad-24c01f292921)

with outlines
![image](https://github.com/user-attachments/assets/471d0a0e-83e3-4677-b27a-f2d5fd1dcc4a)

**Comment by snouz** [comment]
New info

![image](https://github.com/user-attachments/assets/586ce1bb-307b-4e3d-84b5-a9751c3a3f92)

Faospark has an AMD GPU and it works

![image](https://github.com/user-attachments/assets/b2d3232c-11da-4452-95b9-de0292d48750)

**Comment by EricHu33** [comment]
I have a PR for the fix
https://github.com/Albeoris/Memoria/pull/689
