### ISSUE TITLE
Issue with battlegrounds axe's from Armodullahan fight.

### ISSUE THREAD

**Issue by DV666** [Albeoris/Memoria#695]
![image](https://github.com/user-attachments/assets/fcc05468-5139-4ff9-ace5-fa26e08c1a29)

**Comment by snouz** [comment]
Comes from this commit, I guess the battlebg part, so it narrows it down

https://github.com/Albeoris/Memoria/commit/9ae4f350319c0d15dae956b32e692748b9862220

**Comment by snouz** [comment]
EDIT it's this commit
https://github.com/Albeoris/Memoria/commit/32b7abacceadccbcfd1aa631029db3120815ebe6

**Comment by snouz** [comment]
@Tirlititi reverting "nf_BattleBG()" from before this commit fixed it. https://github.com/Albeoris/Memoria/commit/32b7abacceadccbcfd1aa631029db3120815ebe6
I'm pushing as is for the hotfix, and let you remake your changes at your leisure knowing the above bug (also happening in memoria 3rd fields btw)
