### ISSUE TITLE
[Alternate Fantasy] locked in giz grotto, both exits black screen

### ISSUE THREAD

**Issue by babelnaut** [Albeoris/Memoria#697]
trapped in gizamluke's grotto on disc3. have airship but have only sidequested so far, not progressed story since getting it
been working this all day, think my save might be bricked
I can transition around any screen inside just fine, into and out of battle fine, but black screen leaving either end of the grotto after delivering a nut

similar to other peoples' bug, can use menu during this black screen. can call world map moogle and use his menu, save, tent and cancel during black screen. ofc if you save during black screen, you load straight to the black screen. nothing I do between grotto exits, no sequence of battles or de-equipping or selling ♥♥♥♥ or any nonsense I could imagine lets me out with a view.
autosaves turned off

I had this happen once before this playthrough with a chocobo forest/battle sequence, but was able to use a slightly older save. this one is literally zero-chocobo palace since I was on a different file, so </3

have tried full folders wipe reinstall, all kinds of hybrid variations, and everything every thread I can find says try, how it goes

would absolutely adore an unbrick
god help me if I ever save to the same file before entering or exiting anywhere ever again

**Comment by snouz** [comment]
Hi, do you use any mod? Is this the latest Memoria from a few days ago? 
Do you have any log in memoria.log when you get the black screen?

**Comment by babelnaut** [comment]
i'm using AF, mog addons, and moguri
have tried every combination of them since bricking, including fresh none, but whatever is happening has already happened in/to my save

the last thing I did in the story was leave lindblum in the airship

this is my memoria log

09.08.2024 03:44:32 |M| [SteamSdkWrapper] Initialized: True
09.08.2024 03:44:32 |M| [Initialization] Memoria version: 2024-08-05
09.08.2024 03:44:32 |M| [Initialization] OS version: Microsoft Windows NT 10.0.22631.0
09.08.2024 03:44:32 |M| [FontInterceptor] Dynamic font initialization.
09.08.2024 03:44:32 |M| [FontInterceptor] Pass through {Configuration.Font.Enabled = 0}.
09.08.2024 03:44:32 |M| [FontInterceptor] Loading font [Original: TBUDGoStd-Bold (UnityEngine.Font)]
09.08.2024 03:44:32 |M| [UIRoot] Changing a clip region of the UI root.
09.08.2024 03:44:32 |M| [GameLoopManager] RaiseStartEvent
09.08.2024 03:44:33 |M| InitializeItemText
09.08.2024 03:44:33 |M| InitializeImportantItemText
09.08.2024 03:44:33 |M| InitializeAbilityText
09.08.2024 03:44:33 |M| InitializeCommandText
09.08.2024 03:44:33 |M| InitializeBattleText
09.08.2024 03:44:33 |M| InitializeLocationText
09.08.2024 03:44:33 |M| InitializeEtcText
09.08.2024 03:44:33 |M| InitializeEtcText
09.08.2024 03:44:34 |M| [ResourceExporter] Pass through {Configuration.Export.Enabled = 0}.
09.08.2024 03:44:34 |M| [ResourceImporter] Pass through {Configuration.Import.Enabled = 0}.
09.08.2024 03:44:34 |M| InitializeItemText
09.08.2024 03:44:34 |M| InitializeImportantItemText
09.08.2024 03:44:34 |M| InitializeAbilityText
09.08.2024 03:44:34 |M| InitializeCommandText
09.08.2024 03:44:34 |M| InitializeBattleText
09.08.2024 03:44:34 |M| InitializeLocationText
09.08.2024 03:44:34 |M| InitializeEtcText
09.08.2024 03:44:34 |M| InitializeEtcText
09.08.2024 03:44:34 |M| [AudioResourceExporter] Pass through {Configuration.Export.Audio = 0}.
09.08.2024 03:44:34 |E| [SoundLib] System.NullReferenceException: Object reference not set to an instance of an object
09.08.2024 03:44:34 |E|   at SoundLib.LoadAllResidentSfxSoundData () [0x00000] in <filename unknown>:0 
09.08.2024 03:44:34 |E| [SoundLib] System.NullReferenceException: Object reference not set to an instance of an object
09.08.2024 03:44:34 |E|   at SoundLib.StopAllSoundEffects () [0x00000] in <filename unknown>:0 
09.08.2024 03:44:34 |W| [SoundLib] System.NullReferenceException: Object reference not set to an instance of an object
09.08.2024 03:44:34 |W|   at SoundLib.StopAllSounds (Boolean isAll) [0x00000] in <filename unknown>:0 
09.08.2024 03:45:02 |M| [GameLoopManager] RaiseQuitEvent
09.08.2024 03:45:02 |E| [SoundLib] System.NullReferenceException: Object reference not set to an instance of an object
09.08.2024 03:45:02 |E|   at SoundLib.UnloadAllSoundEffect () [0x00000] in <filename unknown>:0 
09.08.2024 03:45:02 |E| [SoundLib] System.NullReferenceException: Object reference not set to an instance of an object
09.08.2024 03:45:02 |E|   at SoundLib.UnloadMusic () [0x00000] in <filename unknown>:0 
09.08.2024 03:45:02 |E| [SoundLib] System.NullReferenceException: Object reference not set to an instance of an object
09.08.2024 03:45:02 |E|   at SoundLib.UnloadAllResidentSfxSoundData () [0x00000] in <filename unknown>:0

**Comment by snouz** [comment]
Have you updated Alternate Fantasy to 6.5? Tirlititi released an update the day after the latest Memoria version (available by redownloading AF from the catalog), and I know it fixes a very similar compatibility issue.
In any way, your save should be safe, it should only be a visual problem.

**Comment by babelnaut** [comment]
updated, ya
went through the closed threads here and saw that, too

fair enough, but i can't play the save so let's say it's in stasis, lol
airship is close outside somewhere but I can't luck into it in the dark or i'd try to transition to a different screen there

**Comment by babelnaut** [comment]
interestingly, I don't seem to be able to transition *back* into the grotto while in black screen
should be easy enough, but there's never an exit sound effect or music switch

**Comment by Tirlititi** [comment]
Can you share me your save?

**Comment by babelnaut** [comment]
Oh, I didn't see the reply.
Sure, of course.

[EncryptedSavedData.zip](https://github.com/user-attachments/files/16581131/EncryptedSavedData.zip)

**Comment by Tirlititi** [comment]
Ok, so, prepare to be struck by hilarity.

The game somehow thinks that you entered the Gizamaluke's Grotto with the full map opened.
When you get back to the world map, it thus starts in a state that is somehow midway from "Full map opened" and "Minimap hidden". You can open the menu as if the minimap was hidden but the screen is frozen as if the full map was opened.

You can actually leave that state by **pressing the button Select a couple of times** (or ``1`` on a keyboard if you haven't remapped that button). Then everything will be fine again.

I'll fix it in Memoria so that the game never thinks that the full map was opened in that situation.
I _guess_ that's some kind of mismatch between two systems that are concurrent in the PC version: the minimap / full map display is both handled by the World Map's scripted events but also hard-coded using Unity's API. If I am right, that isn't a problem of any mod except Memoria but rather a bad luck at some kind of input management.

**Comment by babelnaut** [comment]
holy shit
this _is_ actually hilarious
I spent a solid 16 hours trying everything in the world, pressing and reading and reconfiguring and
everything except mash select which worked immediately, lmao

mad love and respect, goat
thanks so much <3
