### ISSUE TITLE
Get Excalibur II without 12h time limit

### ISSUE THREAD

**Issue by oxydoreduction** [Albeoris/Memoria#7]
Hi,
Would it be possible to "remove" the time limit of 12 hours, to be able to get Excalibur II in any playthrough?

By the way your mod is really great, thanks.
oxydoreduction

**Comment by Albeoris** [comment]
Yes, this is possible, but you need to think about an alternative challenge.

**Comment by oxydoreduction** [comment]
1st thing I thought was getting the "mini" collection (Branet, Cid, Burmecia, Prima Vista) but it's too easy.

Lvl 1 challenge could be interesting but it would be hard to check because EXP from the "you're not alone" part is mandatory (except if you mod something to stop getting EXP from these 3 mid-boss fights).

I'll keep thinking of other challenges.

**Comment by oxydoreduction** [comment]
Would "getting one of each Tetra Master card" be a fair enough challenge to be able to get Excalibur II without the time limit?

**Comment by oxydoreduction** [comment]
NB: I just checked my game file. I'm at the end of the game, I completed many sidequests, I got all the chocographs, and I onyl still have 55 different types of cards.
I guess it would be an interesting challenge.

**Comment by arcanis** [comment]
Have one of each other weapons ? It would make sense, since Gilgamesh is the ultimate weapon collector.

**Comment by oxydoreduction** [comment]
ooh I like that idea.

**Comment by oxydoreduction** [comment]
Hi Albeoris. Great job on this mod.
Any update about this "no time limit for Excalibur II"? Arcanis' idea's pretty interesting imo. All the weapons seem to be obtainable once without sacrificing one for another; Save The Queen and Hammer excepted for obvious reasons. My "all the cards" idea would be a much tougher challenge but hey, if it's for Excalibur II, why not.
Has any of these two ideas caught your interest? Would it be difficult to implement?

**Comment by Albeoris** [comment]
At present it is really difficult to implement. But we will definitely do it.

**Comment by oxydoreduction** [comment]
Awesome! Thanks for the update.

2017-09-03 0:36 GMT+02:00 Albeoris <notifications@github.com>:

**Comment by GuyInDogSuit** [comment]
How about an optional boss? Not as hard as Ozma, but definitely challenging.

**Comment by Caledor** [comment]
For anyone who might end up here while looking for methods to get E2 outside of the time limit.

This has little to do with the game engine, conditions are checked within the Script of specific field, where you get the Item.

Hades Workshop can edit fields scripts and its author Tirilitti describes how alter E2 conditions here: http://forums.qhimm.com/index.php?topic=14315.msg248637#msg248637

Also, for what it's worth, in my own modded game i set the alternate condition for getting the E2 to having the Rank S Medal. So Either reach that spot within 12h OR reach it at any time with Rank S Medal. Mostly for flavor, since the E2 shows a message from "Enkidu" to "Gil" and the only way to know who "Gil" is by getting Rank S Medal.

**Comment by oxydoreduction** [comment]
Hi,
I see this thread is still alive! Great to see updates. Thanks for the info Caledor. You're right, Rank S would be a pretty logical condition for getting Excalibur 2 without the time limit.

**Comment by martin-braun** [comment]
> Hi, I see this thread is still alive! Great to see updates. Thanks for the info Caledor. You're right, Rank S would be a pretty logical condition for getting Excalibur 2 without the time limit.

Alternate Fantasy does it this way. Otherwise you can remove the time restriction with this mod: [PC_ExcaliburII.zip](https://github.com/Albeoris/Memoria/files/7533762/PC_ExcaliburII.zip)

You probably need to go for the HadesWorkshop route, because of other mods, etc.
