### ISSUE TITLE
Bypass the Launcher

### ISSUE THREAD

**Issue by Herfa** [Albeoris/Memoria#70]
Can you please add an option to bypass the launcher in order to launch the game directly from Steam Big Picture Mode with a controller, thanks!

**Comment by Albeoris** [comment]
Edit **Settings.ini** like this:

```
[Memoria]
AutoRunGame=True
```

**Comment by Arquivista** [comment]
Is there any command so I can go straight to the game without going through launch?.

I'm using a front-end to play and I'd like to have the option to play directly and also open the launcher to make settings when necessary.

Thanks a lot for the excellent work.

**Comment by faospark** [comment]
as suggested by albeoris . you can edit the settings.ini  in the game root and add the line
