### ISSUE TITLE
Lond dash character not supported by Alexandria font

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#708]
It could be this character:
https://www.compart.com/fr/unicode/U+2E3B
or this one
https://www.compart.com/fr/unicode/U+2E3A

I propose replacing it on the fly in the code by something like a double/triple normal dash

![image](https://github.com/user-attachments/assets/3575f48c-d574-4426-8135-771438c56087)
![image](https://github.com/user-attachments/assets/51f74bac-aa46-4e7c-ae40-966409963d6a)
![image](https://github.com/user-attachments/assets/e22d19f4-f8c3-4268-b8fe-eae2b1ec2f70)
![image](https://github.com/user-attachments/assets/4a263a96-34da-4c63-b874-c42bbf729eaa)

**Comment by Tirlititi** [comment]
I think it would be better to add the character to the font though.
Also, there should be a system of "fallback font" that makes the game use a more standard font when specific characters miss from the main font used. I'm not sure if it works correctly but maybe it's just not setup properly when using the PSX font as the main font.

**Comment by snouz** [comment]
> I think it would be better to add the character to the font though. Also, there should be a system of "fallback font" that makes the game use a more standard font when specific characters miss from the main font used. I'm not sure if it works correctly but maybe it's just not setup properly when using the PSX font as the main font.

Changing the font is really complicated. It requires editing the font, the reimporting with unity etc. which I have no idea how zePilot managed to do.

A fallback font is the best solution, but a quick replacement might be a viable quick solution, as the code to replace strings is already there.

**Comment by faospark** [comment]
from what I remember in school an Em Dash or that lond dash is basically the longest dash on a typeface / font not unless its a monospace or a pixel type font which an EN dash and an EM Dash should be as the same width as a Hyphen . 
hope tha helps

**Comment by Tirlititi** [comment]
How comes I have that Em Dash on my end?
![AlexandriaFontEMDash](https://github.com/user-attachments/assets/bac30cbd-d95b-4475-93a6-cbc77e6914e6)

Maybe there are multiple versions of the font (Alexandria)?

**Comment by snouz** [comment]
> How comes I have that Em Dash on my end?
> Maybe there are multiple versions of the font (Alexandria)?

maybe a different character in UK and US english?

**Comment by faospark** [comment]
could be a case where they have installed system wide a version of the alexadria font?
