### ISSUE TITLE
Use/wear any item.

### ISSUE THREAD

**Issue by Yeaboy** [Albeoris/Memoria#71]
Is it possible for you to change the data folders so any character can use any armor or weapon? I was able to do it in my playstation emulator but cant figure it out for memoria. Found the data folders but unsure which row I change to 1 so anyone can use a sword or dagger. Will definitely look at editing abilities and so on but for now this would be an awesome start.

**Comment by JoshingAbout** [comment]
If you open Items.csv you'll notice that it lists every item in the game. There are a series of zeros and ones in each row for each item. Zero means that the item is NOT equipable and One means that it IS equipable to a specific character. For example, if you look at Save the Queen, the only 1 in the last 12 spaces that denote Playable Characters is attributed to Beatrix who is the last character in the list.

I find it easier to open the file in OpenOffice as it'll open up in a nice, easy to read table/grid, however, do NOT save the file in OpenOffice as it'll change the file too much and the game won't be able to read it anymore. Open up the file again in NotePad++ or whatever you use to edit the files, and use the OpenOffice version to search for the correct rows and columns to edit. Find them again in NotePad, edit the file however you wish, close the OpenOffice version without saving, then save the NotePad version.

Launch the game and see how things have worked =]

**Comment by Albeoris** [comment]
In general, you can use any spreadsheet editor that supports CSV with a delimiter " ; ", eg Microsoft Excel. OpenOffice [supports it too](https://forum.openoffice.org/en/forum/viewtopic.php?f=9&t=80576).
