### ISSUE TITLE
Small Cosmetic Problem

### ISSUE THREAD

**Issue by Felipefpl** [Albeoris/Memoria#715]
I got the latest memoria and the setting "Linhas da Interface do Usuário" where the mouse arrow is isnt being fully displayed:
![2024-08-12 18_22_07-Greenshot](https://github.com/user-attachments/assets/2ddbf7cb-007f-4bb7-b0d6-37b36cace177)

**Comment by snouz** [comment]
Hi, couldn't it be a shorter word like UI or GUI?
