### ISSUE TITLE
Widescreen bug: Start of game "sure is dark"

### ISSUE THREAD

**Issue by knghtbrd** [Albeoris/Memoria#716]
Using current memoria engine as of now (9.0) with moguri on an ultrawide, "sure is dark" is a lot darker than intended—the light's in the wrong spot, so Zidane really is stumbling around in the dark. Here icon shows the difference. (Screenshots reduced by 50% because they're natively 3840x1600). Turning off widescreen here fixes the offset of the lighting.

If you know where things are you can stumble around in the dark, grab the two (!) items in the back, and then light the candle.

![ffix-not-widescreen](https://github.com/user-attachments/assets/f66e74d3-afe3-417c-a081-9e5e738a65ed)
![ffix-widescreen](https://github.com/user-attachments/assets/29d88adf-bc8a-44ea-9503-e98b9200f655)

**Comment by snouz** [comment]
Hi, thanks for the report, but it's already an open issue

https://github.com/Albeoris/Memoria/issues/582

Ultrawide needs a rework, as there are several backgrounds that don't work right. I recommend sticking with 16:9 for now, as it has been tested through and through.
