### ISSUE TITLE
Steam deck 9.0 Version

### ISSUE THREAD

**Issue by Ryuzoji** [Albeoris/Memoria#719]
When launching the launcher on steam it gives me the following message

Memoria.patcher.exe <gamepath>
Press enter to exit...

When i copy and paste the game location to the launcher option it tells me that it 'failed to get the game location'

On videos i have seen that people just add the launcher to steam and press play after selecting a compatibility option and it launches the mod. I have tried multiple ways to get the mod to launch but no to success.

**Comment by snouz** [comment]
> When launching the launcher on steam it gives me the following message
> 
> Memoria.patcher.exe Press enter to exit...
> 
> When i copy and paste the game location to the launcher option it tells me that it 'failed to get the game location'
> 
> On videos i have seen that people just add the launcher to steam and press play after selecting a compatibility option and it launches the mod. I have tried multiple ways to get the mod to launch but no to success.

I don't own a steam deck to test myself but am in contact on discord with people who do, so we can investigate.

Have you launched the game at least once? Have you tried launching the patcher from inside the game's directory? These are the common causes for this particular problem (at least on PC)

**Comment by Dark-talon** [comment]
> When launching the launcher on steam it gives me the following message
> 
> Memoria.patcher.exe Press enter to exit...
> 
> When i copy and paste the game location to the launcher option it tells me that it 'failed to get the game location'
> 
> On videos i have seen that people just add the launcher to steam and press play after selecting a compatibility option and it launches the mod. I have tried multiple ways to get the mod to launch but no to success.

Boot to desktop mode
Download the memoria.patcher.exe and **copy it to your game directory**
Then add the .exe to Steam as a non-Steam game.
Make sure you select Proton Experimental in the compatibility settings or it won’t start
launch the exe via Steam and it will install the launcher
change the compatibility settings for FF9 to Proton Experimental or the launcher might crash
go to mod manager and download whatever you want
switch back to game mode
enjoy FF IX with Moguri Mod 9.0 at native 800p90

**Comment by snouz** [comment]
> Boot to desktop mode Download the memoria.patcher.exe and **copy it to your game directory** Then add the .exe to Steam as a non-Steam game. Make sure you select Proton Experimental in the compatibility settings or it won’t start launch the exe via Steam and it will install the launcher change the compatibility settings for FF9 to Proton Experimental or the launcher might crash go to mod manager and download whatever you want switch back to game mode enjoy FF IX with Moguri Mod 9.0 at native 800p90

Do you think there's something we can do on our end to facilitate the installation and updating of Memoria on SteamDeck?

**Comment by Ryuzoji** [comment]
This worked like a charm.. Can't believe i didn't figure this out myself.
