### ISSUE TITLE
Stuck save game

### ISSUE THREAD

**Issue by alxtraxxx** [Albeoris/Memoria#72]
Hello,

I saved at Kuja´s place while Zidane was in the desert and just start to run around with Cid and try to save the others.
Now everytime I load this savegame controlled person is Steiner and cant do anything besides pause/unpause because it seems the controls are locked. Continue does load the same savegame so I am currently stuck here. Any possibility to rescue my save game / disable the locked controls? Last savegame on another slot is 9 hours behind this one :(

Thanks in advance

**Comment by Albeoris** [comment]
You included Beatrice in your band, right?
Try to change the party (Alt+F2), then save (Alt+F5) and load (Alt+F9) the game again.

**Comment by alxtraxxx** [comment]
No, I had no character hacks used and Alt+F2 didnt work too (so I tried enabling and F2 after that), only the locked action sound. Same goes for Alt+F5/F9.
I reloaded my other very old savegame and replayed from there.
Usually I use multiple saves and circle through them, this time I didnt ;)
