### ISSUE TITLE
Russian launcher translation incorrect

### ISSUE THREAD

**Issue by KainXVIII** [Albeoris/Memoria#720]
I want to change from atrocious russian translation back to english, please!

**Comment by snouz** [comment]
In the file Settings.ini in the game's folder, you can add `LauncherLanguage=en` under [memoria]

Alternatively, you can fix it in the project, with credit in the next version

https://github.com/Albeoris/Memoria/blob/main/Memoria.Launcher/Languages/ru.xml

**Comment by KainXVIII** [comment]
> In the file Settings.ini in the game's folder, you can add `LauncherLanguage=en` under [memoria]
> 
> Alternatively, you can fix it in the project, with credit in the next version
> 
> https://github.com/Albeoris/Memoria/blob/main/Memoria.Launcher/Languages/ru.xml

Thanks, its really hidden feature, i should note!
PS - well, atrocious is a strong world, translation not THAT bad, just some options are very obscure if you don't know what was in original (disable battle swirl effect setting for example), but i will try to fix it maybe with my limited skills in githubbing/translation

**Comment by snouz** [comment]
I added a request ticket for the language choice
