### ISSUE TITLE
Custom Shaders - Outlines Shader applying when not selected

### ISSUE THREAD

**Issue by Dark-talon** [Albeoris/Memoria#726]
![image](https://github.com/user-attachments/assets/368066ca-ef91-40c8-981b-3d4c73827f71)
When using this configuration, the model outlines shader is being applied all of the time, not just inside of battle.
![image](https://github.com/user-attachments/assets/e3e9be8a-d221-4a87-8442-99b942ece37e)

**Comment by snouz** [comment]
Can confirm. Just checked, and it specifically happens when battle has outlines, and that a shader is applied to non-battle. Doesn't trigger the problem the other way around.

**Comment by snouz** [comment]
@EricHu33

**Comment by barkermn01** [comment]
Could i ask what happens the other way you have have model outlines turned on for outside battle but not turned on inside battle, guessing it's going to be a configuration issue possibly checking the wrong property.

**Comment by snouz** [comment]
> Could i ask what happens the other way you have have model outlines turned on for outside battle but not turned on inside battle, guessing it's going to be a configuration issue possibly checking the wrong property.

Things work correctly then.

**Comment by barkermn01** [comment]
oh that's more difficult then...

**Comment by EricHu33** [comment]
I see, I must've missed that, I'll working on the fix soon
