### ISSUE TITLE
Steam Deck still displays Fix Steam overlay

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#728]
Despite the check for the OS being windows for displaying the setting, it still displays on Steam Deck (which runs steam OS, a Linux distro.

This bricks people's installs.

**Comment by dotaxis** [comment]
Checking for the presence of the `WINELOADER` environmental variable should work to solve this.

```
string isWine = Environment.GetEnvironmentVariable("WINELOADER");
if (!string.IsNullOrEmpty(isWine)) {
    // we are running in wine
}
```

**Comment by snouz** [comment]
Thanks Dot, I added that
