### ISSUE TITLE
Renaming abilities

### ISSUE THREAD

**Issue by JoshingAbout** [Albeoris/Memoria#73]
I'm attempting to replace Vivi's Doomsday spell with a new one called "Pen-Ultima", a mini Ultima using the Matra Magic spell effect as it's the closest thing to the actual Ultima spell effect you can use.

I've gotten the spell working perfectly fine with its damage numbers and animation FX, but because I've created a new spell using the previously unused 163 entry in Actions.csv the spell is simply called "None", as the entry had no prior name attached to it.

I tried adding the name to the correct line in CommandTitles.csv but it didn't do anything. I don't think that file titles spells and abilities, as I tried to rename Cure using the file and nothing happened. I can't think of what else to do.

How should I go about giving new abilities their own names?

**Comment by Albeoris** [comment]
No, it's just a comment.

1. Export text resources.

**Memoria.ini**
[Export]
Enabled = 1
Path = %StreamingAssets%
Languages = "US", "UK", "JP", "ES", "FR", "GR", "IT"
Text = 1

Run the game, wait for title screen, then quit and dispable export settings.

2. Redirect text resources.

**Memoria.ini**
[Import]
Enabled = 1
Path = %StreamingAssets%
Text = 1

3. Now you can change names of abilities and other text resources:

\FINAL FANTASY IX\StreamingAssets\Text\US\Abilities.strings

**Comment by JoshingAbout** [comment]
Thanks for the reply, Albeoris! I have a number of questions about how to use Memoria to its fullest capacity. Should I make one single thread for all of my questions or should I make a new thread for every question I have so it's easier for other people to navigate in case they have similar questions? I'm afraid of spamming the forum too much

**Comment by Albeoris** [comment]
If your questions are of interest to others, better create separate topics. If not, you can write to me personally (Telegram: @albeoris)
