### ISSUE TITLE
Mod downloader: error when cancelling several download

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#730]
To reproduce: download 2 mods at once

click on the arrow to cancel.

![image](https://github.com/user-attachments/assets/4bb03d06-ccb7-4a0c-a3d6-a0b9829214ae)

It then crashes

**Comment by barkermn01** [comment]
Looks like another race condition, it's trying to delete the file after the downloader has extracted and deleted the file already, or the file is locked because it's open for extraction (i can't read the exception language :D )

**Comment by snouz** [comment]
> Looks like another race condition, it's trying to delete the file after the downloader has extracted and deleted the file already, or the file is locked because it's open for extraction (i can't read the exception language :D )

Didn't notice it was French
The process can't access file ---davidbowie.zip--- because it's currently used by another process.

**Comment by barkermn01** [comment]
> Didn't notice it was French The process can't access file ---davidbowie.zip--- because it's currently used by another process.

Yeah it's a race condition, it means the Archive Extractor is active on it and has locked the file so it can't be deleted there are questions that need to be discussed then.

The options i could see for this:
1. Should we make the Archive Extractor a Cancelable Event (in the new system it's a while loop), and then it needs to clean up the files behind it's self (delete the folder and all sub files).
2. Do we just wait for it to finish with a flag and just uninstall it once extraction has completed
3. like option two but provides a dialog saying download is complete are you sure you would like to cancel and removed this mod?

**Comment by barkermn01** [comment]
This has been fixed and pushes sent to @snouz for #727
