### ISSUE TITLE
Error message: file list is missing

### ISSUE THREAD

**Issue by Tudor212** [Albeoris/Memoria#735]
Hi everyone I have installed the mod bit I get an error message file list is missing and cannot be automatically generated if anyone can help please do thank you

**Comment by Tirlititi** [comment]
That's a message that appears when checking the compatibility of different mods. That check is an experimental and informative feature; there is no consequences for it to fail to provide all the details of compatibility potential issues.

It's not an error, it's only a warning that mod compatibility cannot be scanned thoroughly.

**Comment by Tudor212** [comment]
Hi here is the screenshot
![RDT_20240816_1002494737824810839355984](https://github.com/user-attachments/assets/3c54828c-ace2-4274-bc2c-7489ba1e9a6d)

**Comment by snouz** [comment]
Ok this is not a bug, the compatibility check is searching in the list of known mods. You seem to have renamed the folder mogorimain, which doesn't correspond to anything in the list, so it shows a message that it can't check for known incompatibility.
