### ISSUE TITLE
Angel Bless wrong position in battle and model viewer

### ISSUE THREAD

**Issue by Bi-katu** [Albeoris/Memoria#739]
In battle:

![Captura de pantalla 2024-08-16 160411](https://github.com/user-attachments/assets/218108a8-8459-458e-a431-9288579ad56f)

Victory pose:

![Captura de pantalla 2024-08-16 160258](https://github.com/user-attachments/assets/bafedab9-8835-424e-881c-0607d81e31c4)

Model viewer: 

![Captura de pantalla 2024-08-16 160828](https://github.com/user-attachments/assets/70d70f7d-6a67-4543-a420-4edaed79ec6b)

Model viewer (after you scroll weapon and scroll back to angel bless):

![Captura de pantalla 2024-08-16 160914](https://github.com/user-attachments/assets/b115e03b-1643-4eef-9845-f50f71935548)

**Comment by Tirlititi** [comment]
Thanks a bunch for reporting it; I fixed it in 91d61b3
