### ISSUE TITLE
Using enemy spell animations

### ISSUE THREAD

**Issue by JoshingAbout** [Albeoris/Memoria#74]
Is it at all possible to use enemy spell animations for making new spells?

I wouldn't mind making Quina into a pseudo Geomancer character with Water/Wind/Earth damage spells like older Final Fantasy titles, as a parallel to Vivi's Black Mage spells. (I also wouldn't mind making their Trance ability be Dbl Blu Mag instead of Cook.)

If I was to make Aer/Aera/Aeraga into spells I'd need to use the animations of enemy Wind spells such as Aero and Aera, but I have no idea how to reference those animation IDs, if that's even possible.

**Comment by Albeoris** [comment]
Yes, you can do that.
\FINAL FANTASY IX\StreamingAssets\Data\Battle\Actions.csv

There is two fields: animationId1 and animationId2.

I attached a file with the abilities of enemies:
[_Actions.zip](https://github.com/Albeoris/Memoria/files/2716752/_Actions.zip)

Fields "vfx_no" and "Vfx2" are what you need.

I also attached information about enemies and battlefields. I'm not sure that you will be able to use the animation of enemies, as part of it is described directly in the battle scenes. While I do not know how to import changes, and the format of this data is not suitable for manual edits.
[BattleMap.zip](https://github.com/Albeoris/Memoria/files/2716753/BattleMap.zip)
