### ISSUE TITLE
I can't install Moguri mod (2020) or 9.0w

### ISSUE THREAD

**Issue by Albertezca** [Albeoris/Memoria#743]
"Hello! First of all, thanks for the new update. I installed the Memoria Launcher and went to the mods catalog to install, but I can't install either version of the Moguri mod. I thought I might have the previous version of the mod installed, so I uninstalled the game, cleaned it of files, and reinstalled it. I can install other mods, but when I try to install the Moguri mod in any of its versions, the launcher stops working and closes. However, the files do get downloaded onto the PC. Is there any way to fix this or figure out what I might be doing wrong? Thanks a lot for everything.

**Comment by snouz** [comment]
Hi, could you try deleting the MemoriaInstallTmp folder and try again?

Also make sure you have enough space on your disk (you probably need about 7GB to be sure with the archive + the final folder

We're already working on improving the mod manager to better handle these kind of errors.
