### ISSUE TITLE
Install on the Windows store version

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#745]
Someone on reddit told me "Game files are accessible now which was the problem with compatibility before."

Needs investigation

**Comment by barkermn01** [comment]
The Files have always been accessible that has never been a problem the problem is the Windows App Directory is protected by the Windows Kernel Systems, we're not writing into those files, not without seriously compromising windows security systems.

**Comment by snouz** [comment]
I thought they meant that Microsoft changed their way and made this ticket to investigate, but seems like the problem stays the same.
