### ISSUE TITLE
Front row physical damage dealt even when in back row, and elemental resistances in equipment seem to be ignored.

### ISSUE THREAD

**Issue by igorR666** [Albeoris/Memoria#746]
Hi.

Think I've noticed an issue with the latest release [v2024.08.05](https://github.com/Albeoris/Memoria/tree/v2024.08.05), but hoping someone could test and verify first to ensure this isn't actually just a mistake I have made.

I noticed when I was doing the Griffin battle with Steiner in Treno that it was dealing front row physical damage to me regardless of whether I was in the front row or back row, and Aero and Aera damage seemed to be ignoring the 50% wind damage reduction from the Gold Choker/Bronze Armor and doing unexpectedly high amounts of damage to me. Also, Steiner was dealing front row physical damage whether he was in the front or back row.

I tried messing around with row order against other enemies and found the same thing was happening, so it was not just this one battle that was affected.

I thought this was an issue with the mods I had enabled, but the issue persisted even after a complete uninstall of the game itself, reinstallation, running the latest Memoria Patcher .exe again and then running the game with all options unticked in Memoria and no mods downloaded, installed or enabled.

I downgraded Memoria to the June 9th 2024 release and this seemed to solve the problem.

**Comment by DV666** [comment]
What mods do you use exactly?

**Comment by Tirlititi** [comment]
That's a big issue that I failed to notice because it is fixed in AF and TS, sorry.
