### ISSUE TITLE
Long Submod Descriptions can make tick box disappear 

### ISSUE THREAD

**Issue by faospark** [Albeoris/Memoria#750]
![Screenshot_886](https://github.com/user-attachments/assets/5847a3d5-682f-41c5-a34f-a256d6619ee2)![Screenshot_885](https://github.com/user-attachments/assets/5f729bb3-3a30-4b9a-b0b5-be3f66016104)
it seems the tick box to activate a submod disappears when there is a long description of a submod.

**Comment by snouz** [comment]
Fixed in the current repo version (releasing today), the tickbox is next to the drop-down menu, regardless of the text over or below.
