### ISSUE TITLE
Cannot use custom font

### ISSUE THREAD

**Issue by gittysock** [Albeoris/Memoria#751]
Hello, I have been trying to add the following custom fonts: Enchanted Land and Kingthings Petrock. I install them and they show up as selectable in the font list, but when I select them the game only uses the default FF9 PC font, and not the custom font. Is there a way to be able to use these fonts?

Enchanted Lands: https://www.dafont.com/enchanted-land.font

Kingthings Petrock: https://www.dafont.com/kingthings-petrock.font

**Comment by barkermn01** [comment]
What type of font is it could be a type issue like TrueType vs OpenType?

**Comment by snouz** [comment]
We noticed that there's the list of fonts of the launcher (taken from the system) and Unity has its own list of fonts, which is more constrained, and it works only when the font is in the Unity list too. The best would be to make the font dynamically integrated to unity, I have no idea how we can do that, but it's definitely a problem we need to tackle.

**Comment by Tirlititi** [comment]
Usually, you need to install the font **for all users** to make it work. On Windows, right-click the font (here it's the ``.otf`` file) and select "Install for all users".

I am not sure of why you need to do that but indeed there seems to be some kind of mismatch about which fonts are usable by which programs or games.

**Comment by gittysock** [comment]
> What type of font is it using could be a type issue like TrueType vs OpenType? I'm just wondering if the font parser is having problems with specific types.

I think one of these is otf (Enchanted Land) and the other is ttf (Kingthings Petrock), and neither work. I'm thinking it is snouz's explanation

**Comment by gittysock** [comment]
> Usually, you need to install the font **for all users** to make it work. On Windows, right-click the font (here it's the `.otf` file) and select "Install for all users".
> 
> I am not sure of why you need to do that but indeed there seems to be some kind of mismatch about which fonts are usable by which programs or games.

This worked... THANK YOU! I thought I had it installed for all users by doing the normal install process, but right clicking and clicking install for all users worked!

**Comment by gittysock** [comment]
For anyone who is having a similar problem, follow Trilitliti's comment:

Usually, you need to install the font for all users to make it work. On Windows, right-click the font (here it's the .otf file) and select "Install for all users".

I am not sure of why you need to do that but indeed there seems to be some kind of mismatch about which fonts are usable by which programs or games.

**Comment by barkermn01** [comment]
Following on from this i have added this information into the Wiki, it may want moving but for now i have put it on https://github.com/Albeoris/Memoria/wiki/Project-Overview after the components section @Tirlititi you may wish to move it i could not find anywhere else to put it at the time.
