### ISSUE TITLE
How about 21:9 wide screen?

### ISSUE THREAD

**Issue by VanDeAnna** [Albeoris/Memoria#76]
Memoria brings real 16:9 feature.
Awesome!

It is possible to bring more display contents on 21:9 screen?

**Comment by Serino2009** [comment]
I uesed Memoria with Simple Runtime Window Editor (SRWE).
With your mod, SRWE's "Fake fullscreen" could make 21:9 beautiful and immersive displaying:
https://imgur.com/a/4nKezdy
Though it also has offset issue:
https://imgur.com/a/PgUJpMm

Hope one day it could be fixed.

Thanks to your great work.
