### ISSUE TITLE
End game credit after waltz#3 going through South Gate 

### ISSUE THREAD

**Issue by Urbankyleboy** [Albeoris/Memoria#762]
During the cutscene when I defeat the waltz #3 and cross the south gate, the game just shows the credits from de mod tsunade and end the game.

I have Moguri Mod 9.0, Echo S9, Mog adding and black car endgame installed. Any ideas? Thanks!

**Comment by SamsamTS** [comment]
It's the end of Echo-S 9 demo. You disable the mod and continue on or wait for the next demo (disc 1) or the full release

**Comment by snouz** [comment]
Closing this as this is not a bug, but just the end of the Echo-S demo (which is an WIP project by the tsunamods team, not really in relation with the work done on Memoria)
