### ISSUE TITLE
Cinna replaced eiko :(

### ISSUE THREAD

**Issue by Yeaboy** [Albeoris/Memoria#77]
Hi must say I really like this mod sky's the limit. Thanks for the help with the items in my last post now I can equip anyone with anything :) Just wondering if its possible to replace certain characters with other ones. Want to put blank and maybe Marcus in the party but not Cinna. When I change the party option to either 1 or 3 Eiko gets replaced with Cinna :( Dont really wanna lose her form the party. Is it possible to just replace one character at a time or do you have to replace all 3 (Amarant, Eiko and Quina?)

**Comment by Albeoris** [comment]
Fixed https://github.com/Albeoris/Memoria/commit/8f115ef3ac67b5c01c367056943a4d17fb606883
https://github.com/Albeoris/Memoria/releases/tag/v2020.05.20
