### ISSUE TITLE
Game crashes when entering battle command

### ISSUE THREAD

**Issue by JestenDS** [Albeoris/Memoria#776]
I have tried playing the memoria mod on both steam pc and deck, and the game runs perfectly until I enter a battle. The moment a command is entered and the character moves to hit the target the game crashes.

**Comment by snouz** [comment]
Hi, are you using any mods, and are they up-to-date? (there's an icon next to them if they're not up-to-date)

**Comment by JestenDS** [comment]
Hey there, yes I’m using the latest mod update. I wasn’t sure if there is a feature in the memoria mod that could trigger the error.

**Comment by snouz** [comment]
Could you share the files Memoria.ini and Memoria.log after the game's crash? Also, in either in x86 or x64's folder, you might have a folder with today's date, and if so, you'll have some crash information files in there, could you share them as well? Thanks!

**Comment by JestenDS** [comment]
[Memoria.log](https://github.com/user-attachments/files/16737370/Memoria.log)
[memoriaini.txt](https://github.com/user-attachments/files/16737381/memoriaini.txt)

Sure thing, here are the two items from last the game crashed.  
I couldn't find a folder with the date in the x86 and x64 unfortunately.

**Comment by snouz** [comment]
Hi again, I see your memoria version is old

Memoria version: 2024-06-14

Can you update it with the recent one and tell us if that fixes the issue?

**Comment by JestenDS** [comment]
That appears to have fixed this issue as of right now.  I appreciate the help.
