### ISSUE TITLE
Force target change with mouse

### ISSUE THREAD

**Issue by DV666** [Albeoris/Memoria#788]
It's possible to force the game to change the target by using the mouse.

For example, if you use a spell which can target only ennemies, you can use your mouse to force the spell to target the allies instead.

**Comment by snouz** [comment]
Maybe we could add a setting to ignore the mouse completely?

**Comment by DV666** [comment]
Seen like that, it's specific to the command `Swd Mag`, which is perhaps not intended to be in “Multi” at the base (as it's something I added on TS recently), I'll have a look at it.
