### ISSUE TITLE
[Req] add raster font support

### ISSUE THREAD

**Issue by shikulja** [Albeoris/Memoria#79]
add raster font support

И не знаю может у меня глюк.. пытался русские ttf шрифты добавлять.. из 3 ни один в игре не изменил шрифт текста. Английский (Zidane) как ни странно меняет..

**Comment by LunarWhisper** [comment]
Why do you need it?

Так, может, у них у всех было одинаковое начертание русских букв? :)

**Comment by Albeoris** [comment]
Можешь подробнее рассказать? В каком формате ты хочешь поддержку растровых шрифтов? Для чего? Подойдёт ли тебе оригинальный формат, и как ты будешь формировать эти файлы? В целом, ничто не мешает сейчас воткнуть их напрямую в игровые файлы, как это делает автор порта на Android.

**Comment by Albeoris** [comment]
Проверил на Comic Sans - русские буквы корректно меняют начертание.

**Comment by shikulja** [comment]
> Можешь подробнее рассказать? В каком формате ты хочешь поддержку растровых шрифтов? Для чего? Подойдёт ли тебе оригинальный формат, и как ты будешь формировать эти файлы? В целом, ничто не мешает сейчас воткнуть их напрямую в игровые файлы, как это делает автор порта на Android.

Трудно сказать как лучше, оригинального будет достаточно, а формировать по привязке по таблице. Очень удачно было в Parasit eve, там как и таблица символов, так и таблица ширин были в удобном текстовом виде, или как в hades workshop, возможно там отредактировать, в редакторе, и достать файл, возможно из образа, готовый к memoria.

Векторные не подходят, так как, в них невозможно воссоздать оригинальный шрифт, например тени.

`       db  3  ; dejamos el primer byte
        db  3  ; 00=0
        db  4  ; 01=1
        db  9  ; 02=2
        db  9  ; 03=3
        db  2  ; 04=4
        db  6  ; 05=5
        db  7  ; 06=6
        db  3  ; 07=7
        db  4  ; 08=8
        db  3  ; 09=9
        db  3  ; 0A=+
        db  6  ; 0B=-
        db  6  ; 0C==
        db  6  ; 0D=*
        db 6  ; 0E=%
        db 6  ; 0F=SPACE
        db  6  ; 10=A
        db  6  ; 11=B
        db  6  ; 12=C
        db  6  ; 13=D
        db  6  ; 14=E
        db  3  ; 15=F
        db  7  ; 16=G
        db  5  ; 17=H
        db  8  ; 18=I
        db  8  ; 19=J
        db  8  ; 1A=K
        db  8  ; 1B=L
        db 8  ; 1C=M
        db  7  ; 1D=N
        db  9  ; 1E=O
        db  9  ; 1F=P
        db  4  ; 20=Q
        db  6  ; 21=R
        db  9  ; 22=S
        db  7  ; 23=T
        db  10  ; 24=U
        db  9  ; 25=V
        db 9  ; 26=W
        db  7  ; 27=X
        db  9  ; 28=Y
        db  8  ; 29=Z
        db  7  ; 2A=&
        db  7  ; 2B=!
        db  8  ; 2C=?
        db  11  ; 2D="
        db  8  ; 2E='
        db  8  ; 2F=.
        db  7  ; 30=a
        db  8  ; 31=b
        db  7  ; 32=c
        db  7  ; 33=d
        db  7  ; 34=e
        db  7  ; 35=f
        db  8  ; 36=g
        db  9  ; 37=h
        db  5  ; 38=i
        db  4  ; 39=j
        db  8  ; 3A=k
        db  5  ; 3B=l
        db 11  ; 3C=m
        db  9  ; 3D=n
        db  7  ; 3E=o
        db  8  ; 3F=p
        db  8  ; 40=q
        db  7  ; 41=r
        db  6  ; 42=s
        db  5  ; 43=t
        db  9  ; 44=u
        db  9  ; 45=v
        db 11  ; 46=w
        db  7  ; 47=x
        db  9  ; 48=y
        db  6  ; 49=z
        db  4  ; 4A=:
        db  4  ; 4B=,
        db  7  ; 4C=/

        ; aquн se ponen los anchos de los caracteres aсadidos
        db  9  ; 4D=А
        db  7  ; 4E=Б
        db  7  ; 4F=В
        db  6  ; 50=Г
        db  10  ; 51=Д
        db  6  ; 52=Е
        db  6  ; 53=Ё
        db  12  ; 54=Ж
        db  7  ; 55=З
        db  8  ; 56=И
        db  8  ; 57=Й
        db  8  ; 58=К
        db  8  ; 59=Л
        db  10  ; 5A=М
        db  8  ; 5B=Н
        db  10  ; 5C=О
        db  8  ; 5D=П
        db  7  ; 5E=Р
        db  9  ; 5F=С
        db  7  ; 60=Т
        db  8  ; 61=У
        db  11  ; 62=Ф
        db  8  ; 63=Х
        db  9  ; 64=Ц
        db  7  ; 65=Ч
        db  11  ; 66=Ш
        db  12  ; 67=Щ
        db  9  ; 68=Ъ
        db  10  ; 69=Ы
        db  7  ; 6A=Ь
        db  7  ; 6B=Э
        db  11  ; 6C=Ю
        db  8  ; 6D=Я
        db  7  ; 6E=а
        db  8  ; 6F=б
        db  6  ; 70=в
        db  5  ; 71=г
        db  9  ; 72=д
        db  7  ; 73=е
        db  7  ; 74=ё
        db  11  ; 75=ж
        db  7  ; 76=з
        db  7  ; 77=и
        db  7  ; 78=й
        db  8  ; 79=к
        db  7  ; 7A=л
        db  9  ; 7B=м
        db  7  ; 7C=н
        db  8  ; 7D=о
        db  7  ; 7E=п
        db  7  ; 7F=р
        db  6  ; 80=с
        db  7  ; 81=т
        db  8  ; 82=у
        db  10  ; 83=ф
        db  7  ; 84=х
        db  7  ; 85=ц
        db  6  ; 86=ч
        db  10  ; 87=ш
        db  10  ; 88=щ
        db  9  ; 89=ъ
        db  9  ; 8A=ы
        db  7  ; 8B=ь
        db  6  ; 8C=э
        db  9  ; 8D=ю
        db  6  ; 8E=я
        db  0  ; 8F=
        db  0  ; 90=
        db  0  ; 91=
        db  0  ; 92=
        db  0  ; 93=
        db  0  ; 94=
        db  0  ; 95=
        db  0  ; 96=
        db  0  ; 97=
        db  9  ; 98=`


> Проверил на Comic Sans - русские буквы корректно меняют начертание.
Устанавливал шрифт в систему, и вписывал имя шрифта в конфиг мемории
[Font]
Enabled = 1
Names = "DS Pixel Cyr", "DS Pixel Cyr"
Size = 24
например так
из опробованных basis33, GLASSTOWN NBP, opirus opik.

**Comment by Albeoris** [comment]
Мы тут разобрались, почему шрифты не меняются. Ставить их нужно от админа для всего PC, а не для отдельного пользователя. Иначе фейловерится на Ariel. :)

В связи с этим, поддержка растровых шрифтов идёт лесом.

Если всё-таки удастся перейти на новую версию Unity когда-нибудь, там будет TextMeshPro для этих целей.
