### ISSUE TITLE
Menu glitch when saving with Alt+F5

### ISSUE THREAD

**Issue by oxydoreduction** [Albeoris/Memoria#8]
I tried to use the save with Alt+F5 when I was in Mene's menu on Chocobo Garden, and a bug happened: the options at the right of the menu had disappeared.
I think maybe it's because I tried to save while I was in a menu.
Here is a video to be clearer: https://www.twitch.tv/oxydoreduction/v/67210620

**Comment by Albeoris** [comment]
Will fix it. Thank you.
