### ISSUE TITLE
No Battle Text

### ISSUE THREAD

**Issue by Jasonthewarlord** [Albeoris/Memoria#80]
During battle  I don't get damage, healing or status information displayed. When I deal damage or heal it doesn't display it. Is there something I can do to fix this. Thank you for your help!

**Comment by Albeoris** [comment]
If you do not display this information, most likely the characters do not cause damage. This is usually due to an error in scripts. Did you change them? Share the log file \FINAL FANTASY IX\x64\FF9_Data\output_log.txt. Immediately after the occurrence of the error (do not restart the game, otherwise it will be cleared)

**Comment by Jasonthewarlord** [comment]
Initialize engine version: 5.2.3p2 (b5869bab0ca4)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 9.0c [igdumdim32.dll 10.18.10.4061]
    Renderer: Intel(R) HD Graphics 4000
    Vendor:   Intel
    VRAM:     806 MB (via DXGI)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=1 INTZ=1 NULL=1 RESZ=1 SlowINTZ=0
Begin MonoManager ReloadAssembly
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\ICSharpCode.SharpZipLib.dll (this message is harmless)
Loading C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\ICSharpCode.SharpZipLib.dll into Unity Child Domain
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\XInputDotNetPure.dll (this message is harmless)
Loading C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\XInputDotNetPure.dll into Unity Child Domain
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\System.Core.dll (this message is harmless)
- Completed reload, in  0.095 seconds
<RI> Initializing input.

<RI> Input initialized.

desktop: 1366x768 60Hz; virtual: 1366x768 at 0,0
<RI> Initialized touch support.

Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\System.dll (this message is harmless)
Platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\x86\FF9_Data\Managed\Memoria.Prime.dll (this message is harmless)
Unloading 3 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 1.071050 ms

Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 1059.
Total: 0.254112 ms (FindLiveObjects: 0.072662 ms CreateObjectMapping: 0.073893 ms MarkObjects: 0.098525 ms  DeleteObjects: 0.008210 ms)

The file 'C:/Program Files/Steam/steamapps/common/FINAL FANTASY IX/x86/FF9_Data/level1' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

Unloading 2 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.319385 ms
40 BundleScene.Awake
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

NullReferenceException: Object reference not set to an instance of an object
  at Memoria.Assets.Localization.Get (System.String key) [0x00000] in <filename unknown>:0 

  at UILocalize.OnLocalize () [0x00000] in <filename unknown>:0 
UnityEngine.Component:BroadcastMessage(String, Object, SendMessageOptions)
UnityEngine.Component:BroadcastMessage(String, SendMessageOptions)
UIRoot:Broadcast(String)
Memoria.Assets.LanguageMap:SelectLanguage(String)
Memoria.Assets.LanguageMap:.ctor()
Memoria.Assets.Localization:.cctor()
Memoria.Assets.CharacterNamesFormatter:CharacterDefaultNames()
Memoria.Assets.CharacterNamesFormatter:CharacterDefaultNames()
Assets.Sources.Scripts.UI.Common.FF9TextTool:CharacterDefaultName(Int32)
ff9play:FF9Play_New(Int32)
ff9play:FF9Play_Init()
FF9StateSystem:InitFF9GameState()
FF9StateSystem:InitStateSystem()
FF9StateSystem:Awake()
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
PersistenSingleton`1:get_Instance()
FF9StateSystem:get_Settings()
HonoInputManager:SetCustomKeys()
HonoInputManager:InitialInput()
HonoInputManager:Awake()
 
(Filename:  Line: -1)


Unloading 138 unused Assets to reduce memory usage. Loaded Objects now: 24182.
Total: 26.733971 ms (FindLiveObjects: 1.143301 ms CreateObjectMapping: 0.605518 ms MarkObjects: 24.897297 ms  DeleteObjects: 0.086209 ms)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 1398 -> priority: 1 
<RI.Hid> Failed to create device file:

 2 The system cannot find the file specified.


 
(Filename:  Line: 54)

Unloading 3 Unused Serialized files (Serialized files now loaded: 17)
Unsupported enum type 'Memoria.Data.BattleStatus' used for field 'abnormal_status' in class 'AchievementState'
 
(Filename:  Line: 190)

Unsupported enum type 'Memoria.Data.BattleStatus' used for field 'abnormal_status' in class 'AchievementState'
 
(Filename:  Line: 190)

Unsupported enum type 'Memoria.Data.BattleStatus' used for field 'abnormal_status' in class 'AchievementState'
 
(Filename:  Line: 190)

Unsupported enum type 'Memoria.Data.BattleStatus' used for field 'abnormal_status' in class 'AchievementState'
 
(Filename:  Line: 190)

Unsupported enum type 'Memoria.Data.BattleStatus' used for field 'abnormal_status' in class 'AchievementState'
 
(Filename:  Line: 190)

UnloadTime: 4.071140 ms

Unloading 21 unused Assets to reduce memory usage. Loaded Objects now: 24496.
Total: 48.207932 ms (FindLiveObjects: 2.831365 ms CreateObjectMapping: 1.512360 ms MarkObjects: 43.733658 ms  DeleteObjects: 0.128903 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 17)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 24496.
Total: 50.640270 ms (FindLiveObjects: 1.773452 ms CreateObjectMapping: 0.572266 ms MarkObjects: 48.227634 ms  DeleteObjects: 0.066093 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 0.977861 ms

Unloading 4 unused Assets to reduce memory usage. Loaded Objects now: 24501.
Total: 28.580494 ms (FindLiveObjects: 1.217195 ms CreateObjectMapping: 0.350585 ms MarkObjects: 26.972485 ms  DeleteObjects: 0.039410 ms)

Unloading 3 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.321057 ms

Unloading 63 unused Assets to reduce memory usage. Loaded Objects now: 24523.
Total: 33.023979 ms (FindLiveObjects: 1.281237 ms CreateObjectMapping: 0.365363 ms MarkObjects: 31.278852 ms  DeleteObjects: 0.097293 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 17)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 24523.
Total: 31.589617 ms (FindLiveObjects: 1.369088 ms CreateObjectMapping: 0.345248 ms MarkObjects: 29.841206 ms  DeleteObjects: 0.032431 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.048060 ms

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 24547.
Total: 29.598589 ms (FindLiveObjects: 1.235258 ms CreateObjectMapping: 0.308712 ms MarkObjects: 28.012333 ms  DeleteObjects: 0.041052 ms)

Unloading 3 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 2.956574 ms

Unloading 27 unused Assets to reduce memory usage. Loaded Objects now: 24780.
Total: 31.211937 ms (FindLiveObjects: 1.242648 ms CreateObjectMapping: 0.324722 ms MarkObjects: 29.566156 ms  DeleteObjects: 0.075946 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 17)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 24780.
Total: 32.120422 ms (FindLiveObjects: 1.253732 ms CreateObjectMapping: 0.312406 ms MarkObjects: 30.518566 ms  DeleteObjects: 0.035304 ms)

Unloading 3 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 0.977451 ms

Unloading 364 unused Assets to reduce memory usage. Loaded Objects now: 27395.
Total: 33.052303 ms (FindLiveObjects: 1.433540 ms CreateObjectMapping: 0.443363 ms MarkObjects: 31.020634 ms  DeleteObjects: 0.153945 ms)

Unloading 4 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.869514 ms

Unloading 687 unused Assets to reduce memory usage. Loaded Objects now: 25249.
Total: 35.059341 ms (FindLiveObjects: 1.410551 ms CreateObjectMapping: 0.442131 ms MarkObjects: 32.538334 ms  DeleteObjects: 0.666686 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 17)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 25249.
Total: 33.365532 ms (FindLiveObjects: 1.770578 ms CreateObjectMapping: 0.428173 ms MarkObjects: 31.121622 ms  DeleteObjects: 0.043925 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.472129 ms

Unloading 86 unused Assets to reduce memory usage. Loaded Objects now: 25244.
Total: 32.932022 ms (FindLiveObjects: 1.275079 ms CreateObjectMapping: 0.381784 ms MarkObjects: 31.202084 ms  DeleteObjects: 0.071841 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 17)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 25244.
Total: 32.773563 ms (FindLiveObjects: 1.387972 ms CreateObjectMapping: 0.360848 ms MarkObjects: 30.988201 ms  DeleteObjects: 0.035304 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.314489 ms

Unloading 1 unused Assets to reduce memory usage. Loaded Objects now: 25285.
Total: 33.269878 ms (FindLiveObjects: 1.285342 ms CreateObjectMapping: 0.357564 ms MarkObjects: 31.585510 ms  DeleteObjects: 0.040231 ms)

Non platform assembly: C:\Program Files\Steam\steamapps\common\FINAL FANTASY IX\StreamingAssets\Scripts\Memoria.Scripts.dll (this message is harmless)
