### ISSUE TITLE
Install error: Invalid magic number: 3709354366009218081

### ISSUE THREAD

**Issue by chrno1209** [Albeoris/Memoria#800]
When install Memoria patcher **v2024.08.05**, I always get this error message:

`
Unexpected error has occurred.
---------------------------
System.IO.InvalidDataException: Invalid magic number: 3709354366009218081
   at Memoria.Patcher.Program.Run(String[] args)
   at Memoria.Patcher.Program.Main(String[] args)
`

**v2024.06.09** works just fine.

**Comment by snouz** [comment]
This is the second report I got of this, but can't reproduce.

Can you try:

1. Redownload from github and install again, see if works (maybe it's corrupted)
2. Upload your latest download [to this](https://emn178.github.io/online-tools/sha1_checksum.html), give us the output, it should be this: 35d3fd5c844cfbccc06023014e085d7b1cfca11c
3. If redownloading fails and the number above is the same, could you give us more info about your system?

**Comment by chrno1209** [comment]
Hi @snouz ,
Thanks for reply, I can confirm that the Memoria.Patcher.exes MD5 is 35d3fd5c844cfbccc06023014e085d7b1cfca11c
My system info:
- Processor	Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz   2.59 GHz
- Installed RAM	64.0 GB (63.7 GB usable)
- System type	64-bit operating system, x64-based processor

The FFIX version I am playing is downloaded from https://cs.rin.ru/forum/viewtopic.php?p=3007464#p3007464

**Comment by EricHu33** [comment]
You should use Memoria with steam version FF9. This mod did not support any kind of pirating.
Therefore if the bug only occour on private version, there's no reason to solve it.

**Comment by chrno1209** [comment]
Thanks for the info, just curious on why v2024.06.09 works just fine but not the latest one

**Comment by snouz** [comment]
Because we've began signing the patcher starting with the latest one, with a legit digital signature.

**Comment by chrno1209** [comment]
I understand now, will try to build a version of Memoria that works with my pirated FFIX

**Comment by snouz** [comment]
This repo operates under the tacit understanding (but confirmed by sources in contact with SE legal department) that we cannot suggest, encourage or discuss any form of piracy. Thus I have to censor your comment.
