### ISSUE TITLE
Launcher/Patcher help

### ISSUE THREAD

**Issue by Padme92** [Albeoris/Memoria#805]
Hello!
I've bought FFIX on Steam (PC Windows 11) to play for the 100th time this marvellous game, only this time I was excited to use the new Moguri mod. I followed all the steps and tried some suggestions to make it work, but the launcher is always that of Zidane with a customizable screen size. Even if the black window saying installation successful pops up and I've run the game before, it doesn't work. I tried launching it from the folder or uninstall everything and start from scratch. Still I can't see the Launcher with the forest background. Settings.ini is the file created in the directory, but it contains only the screen size modification. I even tried the method suggested for steam deck and launched the patcher on the steam library. Before giving up and ask for a refund, I thought I would ask for some advice on here. 
I thank you and wish you a nice day!

**Comment by snouz** [comment]
Hi! This is the first such report we've received, is there any chance the game is installed in two places on your computer? Maybe you moved it from a disc to another and the registry was not updated (that's a common steam problem with their "move game from one disc to another" feature)

If it's not that, I'll try to think of what else it could be, but I don't really have any other explanation so far

**Comment by Padme92** [comment]
I removed the antivirus, deleted all the files, reinstalled the game and patcher and now it's working (:

Maybe you can help someone else next time with the same issue! Im so happyyy

**Comment by WarpedEdge** [comment]
To help. Since you just installed it, can you launch the game fully then
close it. Then run the memoriapatcher.exe then launch the game again?

**Comment by WarpedEdge** [comment]
Oof responded at same time. Glad its working for you.

**Comment by snouz** [comment]
> I removed the antivirus, deleted all the files, reinstalled the game and patcher and now it's working (:
> 
> Maybe you can help someone else next time with the same issue! Im so happyyy

Ah glad this works for you! What's your antivirus btw? (even if it's probably resinstalling that solved the issue in this case)

**Comment by Padme92** [comment]
It was Comodo! It put some downloads in a hidden folder called VTroot, probably the mod was catalogued as dangerous, dunno. I had uninstalled before but unsuccessfully.

**Comment by EricHu33** [comment]
Glad you fixed it, enjoy the game :)
