### ISSUE TITLE
Change scale of Debug Wireframe view?

### ISSUE THREAD

**Issue by Squall789** [Albeoris/Memoria#81]
Sorry to bother you, I noticed that the debug wireframe view appears to have a set draw size regardless of the games resolution, I was wondering if it might be possible to rescale it.

Ideally I'm interested in exporting the camera, however I don't see this being possible so I'm more than happy with a high resolution wireframe that can help me recreate the camera angles.

Sorry if you're no longer active on this project.

**Comment by Albeoris** [comment]
@Squall789 , hi!

Unfortunately, I really do a little of this project now.
Anyway, I am infinitely far from three-dimensional graphics. :(

**Comment by Albeoris** [comment]
It seems no longer relevant.
