### ISSUE TITLE
First game battle.

### ISSUE THREAD

**Issue by Andyvastu** [Albeoris/Memoria#813]
I'm stuck. In the first fight of the play, every time I attack or get attacked, a message appears (DLL Error, CHECK memoria.log), and I can't get past it. Does anyone know how to fix this? Thank you very much!.

**Comment by Tirlititi** [comment]
It looks like you have a mod that is not compatible with the version of Memoria that you have installed. It's either:
- You didn't get the latest version of Memoria (most likely, you downloaded it from "Echo-S9" or you installed Memoria a while ago).
- Or you use a mod that is not compatible with the latest version. I think "Freya Game+" and "AF Fairer Bosses" are the only ones that are currently in that situation.

**Comment by snouz** [comment]
Closing since this is likely we won't get the info and the problem doesn't lie in Memoria.
