### ISSUE TITLE
How to export text

### ISSUE THREAD

**Issue by weirdalsuperfan** [Albeoris/Memoria#82]
Can you explain how to export the full game script (maybe adding that to the readme)? It doesn't matter what order the lines are in for me.

Has it been exported before? Is it already available somewhere?

**Comment by Zer0Ph34r** [comment]
I don't know if it's built into the Mod, but this guy did a pretty comprehensive game script: https://gamefaqs.gamespot.com/ps/197338-final-fantasy-ix/faqs/42207
It's incomplete, and it has upfront the areas that it is lacking, but all the missing pieces are very minor

**Comment by weirdalsuperfan** [comment]
Thanks. I was actually looking to export the Japanese script (^_^)ゞ

**Comment by Albeoris** [comment]
@weirdalsuperfan in the Memoria.ini:

[Export]
Enabled = 1
Text = 1

[Import]
Enabled = 1
Text = 1

**Comment by patman023** [comment]
@Albeoris Can you clarify your 21-09-2019 comment please? Do BOTH Import and Export need to be enabled at the same time?
