### ISSUE TITLE
Install instructions for Batocera

### ISSUE THREAD

**Issue by capwatkins** [Albeoris/Memoria#821]
I tried running the Steam Deck script in Batocera's xterm, but (unsurprisingly, maybe) it got hung up at the "press Return to continue" step and wouldn't move forward. I poked around the Internet and couldn't find instructions for using this mod with Steam on Batocera, and would love to figure that out!

**Comment by dotaxis** [comment]
Can you post the full output of the command here?

**Comment by capwatkins** [comment]
![image](https://github.com/user-attachments/assets/fea2b548-dc8b-45eb-88b4-06a23bc25cd3)

Sorry it's not the text straight-up, but I'm running Bato on a separate drive on my PC so can't easily screenshot across to Windows! Luckily there's not much there.

When I do press Enter to continue, it just creates a new line and nothing happens. Pressing enter again, does the same thing. Etc.

**Comment by dotaxis** [comment]
This looks like a TTY instead of a regular terminal inside a session. 

I know basically nothing about batocera, but if you are getting stuck this early in the process, it is likely missing some basic commands and features and we'll be unable to support it.

**Comment by capwatkins** [comment]
No worries! I figured it might not be possible, but thought I'd ask! Appreciate it!
