### ISSUE TITLE
There are four options in "config" and I don't know how to localize them.

### ISSUE THREAD

**Issue by imcloud** [Albeoris/Memoria#822]
![2](https://github.com/user-attachments/assets/998dba4c-2226-49b2-9ec8-8866f3e984e8)

There are four options in "config" that I don't know how to localize. 
These were added in version 9.0. 
Now I can't find the file location of the text. Please tell me the exact path to complete my localization mod.
Please help me, thanks

**Comment by Tirlititi** [comment]
They are there: [LocalizationPatch.txt](https://github.com/Albeoris/Memoria/blob/main/Memoria.Patcher/StreamingAssets/Data/Text/LocalizationPatch.txt)

Most likely, you have a complete ``Localization.txt`` file instead somewhere in your translation mod. Possibly it's in a sub-folder ``EmbeddedAsset/Manifest/Text/Localization.txt``. If that's the case, you just need to add a couple of lines with these entries.

**Comment by imcloud** [comment]
> They are there: [LocalizationPatch.txt](https://github.com/Albeoris/Memoria/blob/main/Memoria.Patcher/StreamingAssets/Data/Text/LocalizationPatch.txt)
> 
> Most likely, you have a complete `Localization.txt` file instead somewhere in your translation mod. Possibly it's in a sub-folder `EmbeddedAsset/Manifest/Text/Localization.txt`. If that's the case, you just need to add a couple of lines with these entries.

Yes, I modified the Localization.txt file and placed it in the mod folder. 

Copying it into the Localization.txt file does not work, looks like the game doesn't read this text from this file

**Comment by imcloud** [comment]
![3](https://github.com/user-attachments/assets/67126aff-bf39-4787-b69e-520ff0faaf9e)
![4](https://github.com/user-attachments/assets/bf48aac6-cde6-48af-9d46-865ee59f7a0e)

**Comment by Tirlititi** [comment]
Ah, I know, you cannot override ``LocalizationPatch.txt`` entries with ``Localization.txt``.
So you need to create another file instead, ``StreamingAssets/Data/Text/LocalizationPatch.txt``, and write the modified entries there.

**Comment by imcloud** [comment]
![5](https://github.com/user-attachments/assets/0e3e99c3-2774-4a09-ab1f-82c49e50f833)

cool, I did it!

thank you @Tirlititi
