### ISSUE TITLE
Mod manager doesn't support resume of the downloaded mods

### ISSUE THREAD

**Issue by VolkovChitzkoi** [Albeoris/Memoria#828]
This issue is a problem especially for who has slow internet connection. If you start download Moguri videos 30fps or Memoria mod, after a while the download hangs and you cannot resume the download. The result is that you're unable to download the mods.

**Comment by snouz** [comment]
I hope someone can improve the downloader, in the meantime you can use the direct link to download them. Put the content of the zips in a folder and activate it in the mod manager, this will achieve the same result.

https://www.dropbox.com/scl/fi/qcgo2bafhdwvqftfrik67/MoguriMain.zip?rlkey=jmnyty7p2ug6zgm1y4kvortel&st=av2r07eh&dl=0

https://www.dropbox.com/scl/fi/fec2gpdosunaqmqd4rxlp/MoguriVideo.zip?rlkey=jpbhon1g34a3ywctgybkvsef9&st=iiy9v116&dl=0

**Comment by Darkjoe065** [comment]
Hi, i have the same issue like this. Moguri mod is not downloading using memoria mod manager although I already patch my ff9 steam version using the latest memoria patcher. Tried also the dropbox link but its error 400. Thanks in advance
