### ISSUE TITLE
Soft-reset in battle: makes the next battle display a black screen

### ISSUE THREAD

**Issue by Red86** [Albeoris/Memoria#830]
Hi,
as per the title, I am having this issue and after disabling all the mods but moguri I've narrowed it down to it.
If you soft reset during a fight (L1+L2+R1+R2+select+start) after you load/continue the next time a battle occurs it will display a black screen. The music plays as usual but, you cannot pause or do anything else but soft reset again.
When you soft reset this time, for a brief moment the image of the battle field will display before returning you down to the main menu. Choosing to load/continue this time will be fine and the next time a battle occurs won't result in a black screen.

I am using moguri 9.0.

**Comment by SamsamTS** [comment]
I found the problem. This would occur only when the start button is pressed last or on the same frame has the other buttons.
