### ISSUE TITLE
Battle animation - sfx freya spear stutter

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#844]
https://github.com/user-attachments/assets/7ef8e1c5-ae96-4920-a841-93f7dbcbc13a

![Bug animation - sfx freya spear stutter](https://github.com/user-attachments/assets/f6bb609d-910a-494a-9648-bbbe9050849c)

**Comment by SamsamTS** [comment]
Started happening with https://github.com/Albeoris/Memoria/commit/93a80b52798d66b532fc6e43798a617ba4bf4734
@Tirlititi
