### ISSUE TITLE
Memoria.ini interface Row/column overridden by Launcher

### ISSUE THREAD

**Issue by resinate** [Albeoris/Memoria#848]

**Comment by snouz** [comment]
Could you provide more information? What setting isn't applied?

**Comment by resinate** [comment]
MenuItemRowCount = 10 (retains 8 rows, it worked for a bit then reverted back to 8)
SpiritStatFormula = Min(99, SpiritBase + (SpiritBonus / 16)) (forced locked to 50 even tho other option let me uncap it to 99/250)

**Comment by resinate** [comment]
the max stat values is actually under ff9PLAY in the csharp. i fixed this issue on my own. with that
now all of sudden item rows is working again. i dont know what i did to fix it
