### ISSUE TITLE
Area Text - Chocobo's Dream World stutter

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#854]
![Area Text - Chocobo's Dream World stutter](https://github.com/user-attachments/assets/36203081-7414-4460-817a-3b2fb0b1ef2d)

Sorry, I can't provide the video, because it's need high framerate to catch this stutter which mean raw recorded video (no compression) with filesize bigger than 10 MB.

**Comment by snouz** [comment]
For me later:

https://youtu.be/3dRMRRI0OF4?si=wvpBpcpwwUSScLs-&t=1973

**Comment by psxlover** [comment]
@snouz in the video you posted, does the dead soldier in Gizamaluke's Grotto at 35:42 blink?
