### ISSUE TITLE
Some music tracks skip half a second of the beginning.

### ISSUE THREAD

**Issue by Snub5472** [Albeoris/Memoria#856]
The victory theme, the track in the South Gate, and the overworld music are affected by this. The battle themes are not, however.

https://github.com/user-attachments/assets/eae9ebc9-c64e-44c6-b6ff-0e13e62a713d
What happened to the drums at the beginning?!

**Comment by snouz** [comment]
@SamsamTS

**Comment by SamsamTS** [comment]
Good catch, I didn't even noticed that. That was entirely my bad.

**Comment by Snub5472** [comment]
Awesome!
I'm new to GitHub so I don't know how to get this fix? Do I just wait for it to be in the next release?

**Comment by SamsamTS** [comment]
@Snub5472 Yes, next release will contain the fix. We tend to wait for on-going work to be completed before doing a release (unless there is a game breaking bug, in which case we may do a hotfix). You can sort of see the progress in the current pull requests although it doesn't really inform how long it's gonna take.
