### ISSUE TITLE
Widescreen battle animation - Leviathan Summon limited by 4:3 area estimation

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#859]
https://github.com/user-attachments/assets/e3740396-6a8e-4926-b1e4-20103c72b30f

![Widescreen battle animation - Leviathan Summon 1](https://github.com/user-attachments/assets/b99cae8e-d830-4a65-a675-15fd3f9cd8bc)
![Widescreen battle animation - Leviathan Summon 2](https://github.com/user-attachments/assets/5ed9781a-a2f5-4d54-8cd6-d87e0b5b7057)

**Comment by snouz** [comment]
@Tirlititi
