### ISSUE TITLE
Kuja must not show up early for more realistic Zidane surprise

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#860]
https://github.com/user-attachments/assets/e4d58597-fa83-4884-aa9d-5ac273356d76

![Kuja must not show up early for more realistic Zidane surprise](https://github.com/user-attachments/assets/b4db788e-d576-46b8-b38c-09b29d8d5704)

Maybe you can try to use 4:3 frame, then going to widescreen when Zidane move closer to Kuja (greeting Zidane).

**Comment by snouz** [comment]
I thought about this one, don't really know how to go about it. Either I limit to 4:3 but that's for the whole scene, or I can move kuja slightly to the right when widescreen exists (something I've done for other scenes already)

**Comment by yisandind** [comment]
I think it would be easier to expand the graphic (background) to the left a bit. but it still requires hard work and creativity. sorry.

**Comment by snouz** [comment]
There's currently no way to expand backgrounds past their original size.

**Comment by sunglaedr** [comment]
I think your suggestion of moving a bit Kuja to the right out of the first screen so that we don't see him when he first teleports into his room is a great simple fix.
