### ISSUE TITLE
Battle animation - Amaranth No Mercy does not charge from his hand

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#861]
https://github.com/user-attachments/assets/260fca0f-5c9d-4475-bdb5-baa674483a15

![Battle animation - Amaranth No Mercy does not charge from his hand](https://github.com/user-attachments/assets/e02b1b79-73a2-4375-ab18-8e5728b57a21)

**Comment by snouz** [comment]
Is this a difference compared to the PS1 version? I can't find a clip on youtube
