### ISSUE TITLE
Blackscreen when first entering Treno on Disc 2

### ISSUE THREAD

**Issue by vulpesd** [Albeoris/Memoria#867]
As the title states, as soon as I try to enter Treno for the first time in disc2 the screen just goes black. I can still pause and hear the music playing, but unsure of how to progress, even after disabling mods

**Comment by snouz** [comment]
Hi, thanks for reporting, could you give us the content of Memoria.log after entering it?

**Comment by vulpesd** [comment]
After trying to grab the log, it started working... ^^;

**Comment by vulpesd** [comment]
[Memoria.log](https://github.com/user-attachments/files/17088412/Memoria.log)

But here is the log regardless, as it just happened again when entering different areas in disk 2

**Comment by snouz** [comment]
> [Memoria.log](https://github.com/user-attachments/files/17088412/Memoria.log)
> 
> But here is the log regardless, as it just happened again when entering different areas in disk 2

Just noticed you're using the version I shared with a few people when I was trying to [fix an important bug](https://github.com/Albeoris/Memoria/issues/757) but this is not the latest. You need to install the latest version:
https://github.com/Albeoris/Memoria/releases

This is almost certainly the culprit, as I was working on a problem related to fading to/from black at the time. I had only shared this temp version to see if my changes had an impact on a specific crash.
