### ISSUE TITLE
Battle animation - Aerial Slash sfx too soon

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#868]
https://github.com/user-attachments/assets/960d4e17-9414-4a7c-a1e9-1d03b1d7f187

![Battle animation - Aerial Slash sfx too soon](https://github.com/user-attachments/assets/28f0e77b-7c07-4f1d-96b5-d1943a832886)

https://github.com/user-attachments/assets/633942a4-9551-4c60-92eb-92522d523758

![Battle animation - Aerial Slash sfx too soon 2](https://github.com/user-attachments/assets/fb1bd7c4-8fe5-4237-8018-2dd5b070107a)

**Comment by snouz** [comment]
Monsters who have it: Gargoyle, Garuda, Nova Dragon, Red Dragon, Silver Dragon

Found the original anim
https://youtu.be/nuCw4j5EMZQ?si=hC_6GcOFGdFkW9HK&t=310

**Comment by yisandind** [comment]
looks like some of my old recordings are useful. hehe.
