### ISSUE TITLE
Battle animation - Racket weapon attack looks pixelated

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#869]
https://github.com/user-attachments/assets/bc03a54f-376f-4359-9196-7937412830bf

![Battle animation - Racket weapon attack looks pixelated](https://github.com/user-attachments/assets/d39ce394-a3b0-405c-83e2-6ef28ca64f3d)

It looks weird for a full hd screen.

**Comment by snouz** [comment]
SFX were recently made moddable, and it's my plan to work on upscaling them, that haven't do it yet.
