### ISSUE TITLE
Field Foreground - Daguerreo middle floor does not overlap character

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#874]
https://github.com/user-attachments/assets/ff945d15-0c84-434c-8c51-141dea55dfa7

![Field Foreground - Daguerreo middle floor does not overlap characters](https://github.com/user-attachments/assets/1cc1ca10-3f5a-4350-8512-724a3f67729a)

**Comment by snouz** [comment]
I'll confess something. I wasn't aware you could go on the first floor.

How do you go to the first floor?

**Comment by sunglaedr** [comment]
Me neither lol
But here is how to get to the middle floor: https://youtu.be/hcRjv9RpEzo?t=815

**Comment by yisandind** [comment]
15 years ago, I was one of the players who reached the green clock. so it's impossible for me not to realize this. hehe.

**Comment by snouz** [comment]
> 15 years ago, I was one of the players who reached the green clock. so it's impossible for me not to realize this. hehe.

The green clock?

**Comment by yisandind** [comment]
After 99 hours of play, the color of the clock changes. The final color change is green. As I remember in order white - red - yellow - blue - purple - green.
