### ISSUE TITLE
NPC: Village of Dali background overlap chocobo

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#875]
https://github.com/user-attachments/assets/91393b92-9e77-49b3-9caa-75c1bf9b9d69

![Field Background - Village of Dali background overlap chocobo](https://github.com/user-attachments/assets/f3b723e6-c739-4d29-a4e2-84d847a620b9)

**Comment by snouz** [comment]
In which situation is the chocobo there? What CD is this?

**Comment by yisandind** [comment]
CD 3, after getting Hilda Garde 3.
