### ISSUE TITLE
Field Foreground - Alexandria's candle fire animation does not overlap character

### ISSUE THREAD

**Issue by yisandind** [Albeoris/Memoria#883]
https://github.com/user-attachments/assets/d5aa692c-fc01-4474-9b32-3db7c618920e

![Field Foreground - Candle fire animation does not overlap character 1](https://github.com/user-attachments/assets/b802a427-ece3-49ab-8739-cb5f71ce5d83)
![Field Foreground - Candle fire animation does not overlap character 2](https://github.com/user-attachments/assets/734152fd-2fb7-4925-bc15-6eb750f04b87)

**Comment by snouz** [comment]
fixed
![image](https://github.com/user-attachments/assets/7193730c-1925-4fee-a1f6-0f026b4b52af)
