### ISSUE TITLE
Game crash (unfixable vanilla bug)

### ISSUE THREAD

**Issue by imcloud** [Albeoris/Memoria#884]
[2024-09-25_220848.zip](https://github.com/user-attachments/files/17132872/2024-09-25_220848.zip)

![crash1](https://github.com/user-attachments/assets/3de2dfc5-97eb-43d0-9847-c84811dca554)

Should I submit it here？Do you need any other information？

**Comment by snouz** [comment]
Hi, thanks for the report, could you also share the memoria.log from the crash if you have it too?

**Comment by snouz** [comment]
FF9SpecialEffectPlugin.dll caused an Access Violation (0xc0000005)
  in module FF9SpecialEffectPlugin.dll at 0033:54e8dfc2.
  
========== OUTPUTING STACK TRACE ==================

0x00007FFD54E8DFC2 (FF9SpecialEffectPlugin) SFX_GetPrim
0x00007FFD54E8D8F3 (FF9SpecialEffectPlugin) SFX_GetPrim
0x00007FFD54EC919A (FF9SpecialEffectPlugin) SFX_GetPrim
0x00007FFD54EC8BFB (FF9SpecialEffectPlugin) SFX_GetPrim
0x00007FFD54EB1A88 (FF9SpecialEffectPlugin) SFX_GetPrim
0x00007FFD54EB0E20 (FF9SpecialEffectPlugin) SFX_GetPrim
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempted to access invalid address
' (Address: 00007FFD54E815E9)
0x00007FFD54E815E9 (FF9SpecialEffectPlugin) 
0x0000000029DF964C (Mono JIT Code) (wrapper managed-to-native) SFX/DLLMethods:SFX_Update (int&)
0x0000000029DF95A2 (Mono JIT Code) SFX:SFX_Update (int&)
0x0000000011DBB01F (Mono JIT Code) SFXDataMesh/Runtime:Load (int)
0x0000000011DBAC31 (Mono JIT Code) SFXDataMesh/Runtime:SetupRuntimeMesh (Memoria.Data.SpecialEffect,CMD_DATA,FF9.BTL_VFX_REQ,int&)
0x000000003E2B8284 (Mono JIT Code) SFXData:LoadLoop ()
0x0000000029DA5087 (Mono JIT Code) SFXData:AdvanceEventSFXFrame ()
0x0000000029DA4B1F (Mono JIT Code) UnifiedBattleSequencer:Loop ()
0x0000000029DA2FD7 (Mono JIT Code) battle:BattleSubSystem (FF9StateGlobal,FF9StateBattleSystem)
0x0000000029DC2752 (Mono JIT Code) battle:BattleMainLoop (FF9StateGlobal,FF9StateBattleSystem)
0x0000000029D795D0 (Mono JIT Code) battle:BattleMain ()
0x0000000029D77D99 (Mono JIT Code) HonoluluBattleMain:UpdateBattleFrame ()
0x0000000029D72CA2 (Mono JIT Code) HonoluluBattleMain:UpdateFrames ()
0x0000000029D723D6 (Mono JIT Code) HonoluluBattleMain:Update ()
0x000000000663725B (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFD5CD14087 (mono) mono_set_defaults
0x00007FFD5CC683DD (mono) mono_runtime_invoke
0x00007FF6252CCDE3 (FF9) ScriptingArguments::AddString
0x00007FF6252CCB27 (FF9) ScriptingArguments::AddString
0x00007FF6251F02B0 (FF9) IIMGUI::IIMGUI
0x00007FF6251F295A (FF9) GetMonoBehaviourInConstructor
0x00007FF6251CC7BF (FF9) BaseBehaviourManager::~BaseBehaviourManager
0x00007FF62528521E (FF9) RectT<int>::Contains
0x00007FF6253548F0 (FF9) PlayerMainWndProc
0x00007FF6253572EC (FF9) PlayerWinMain
0x00007FF62577171C (FF9) Unity::Component::CalculateSupportedMessages
0x00007FFDDCB97374 (KERNEL32) BaseThreadInitThunk
0x00007FFDDD71CC91 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**Comment by imcloud** [comment]
[Memoria.log](https://github.com/user-attachments/files/17134457/Memoria.log)

**Comment by Marcelo20XX** [comment]
I got the same crash on a different place but one thing I am certain is that it's only happening whenever I use the auto battle function, don't know if its a coincidence

**Comment by Tirlititi** [comment]
I'm afraid that's a bug involving a DLL that we cannot fix. It might be related to memory allocation: SFX sometimes ask for a whole chunk of memory allocation at once.
I have just seen that bug reported by someone who have not Memoria installed (and I see it from times to times since the re-release), so it's a bug present in vanilla. It's a shame that I don't see any possible fix for now though.

**Comment by Marcelo20XX** [comment]
Yes, I remember when the game just released that the only game stopping bugs reported on Steam where 3: A black screen after so many battles leading to a soft lock, the Zhorn and Thorn Mount Gulug Boss fight where it will just hang at the beginning and this one. Personally I have beat the game from start to finish many times and suffer those bugs which prevented me from finishing the game without loading the game at least twice on a playthrough...
