### ISSUE TITLE
FMV Stutter & Thin Grey Line

### ISSUE THREAD

**Issue by Maleel** [Albeoris/Memoria#885]
I was trying to launch FF9 the other day using the Moguri mod, but I just can't get it to work the way I want it to.
I'm have two key problems:

1. I get a thin grey line at the top or bottom of my screen.
2. The opening FMV is laggy and stutters. (I'm not just talking about the low framerate).

I'm playing with a 4090 and 7800x3D on Windows 10 so I know hardware shouldn't be my issue.
I've tried to isolate what's causing the issue.

When I launch the game vanilla freshly installed with no mods or patcher, everything runs properly, no problems whatsoever.
When I launch the game after running the Memoria patcher (without downloading any other mods), I get both the issue of the thin grey line, and the laggy FMV that skips and stutter.

So I can conclude It's Memoria causing these issues.
There seems to be a handful of people who are also having the same issues.
The first thread I opened on Reddit has at least a couple other people having this same exact issue, and at least one other person has also reported the issue with the grey lines on discord.
https://www.reddit.com/r/FinalFantasyIX/comments/1fmz7oj/moguri_mod_help/

**Comment by snouz** [comment]
Thanks for the report, 

The grey line is an open issue here
https://github.com/Albeoris/Memoria/issues/572

The stutter is an open issue here
https://github.com/Albeoris/Memoria/issues/766

But don't worry about it being a duplicate, it's always useful to get more information about a problem, and have some confirmation of how widespread a problem is.

**Comment by Maleel** [comment]
Ah okay, I'm glad It's a known issue then, at least.
