### ISSUE TITLE
Ice cavern: mist cut by background

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#889]
![image](https://github.com/user-attachments/assets/77853185-49b8-4e96-a608-0da06dac88b7)

**Comment by yisandind** [comment]
https://github.com/user-attachments/assets/7c79ca5c-f9e7-4f86-afbe-f120b672becd

![The mist should overlap the chest   character 1](https://github.com/user-attachments/assets/a7aeaacc-f33f-4566-97d5-cc1a25aafa9a)
![The mist should overlap the chest   character 2](https://github.com/user-attachments/assets/ad49cc61-02df-4c84-bd48-940e953a4fba)

Maybe the mist should overlap the chest & character.
