### ISSUE TITLE
final fantasy 9  clayra bug 

### ISSUE THREAD

**Issue by lucashergotte** [Albeoris/Memoria#898]
I have a black screen problem once I enter Clayra's sand spin

**Comment by SamsamTS** [comment]
Could you please provide the Memoria.log?

**Comment by lucashergotte** [comment]
how we look at the logs

**Comment by snouz** [comment]
> how we look at the logs

Memoria.log is located in the main game folder. It's usually in "C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX"

Know that if you restart the game, that file gets overwritten.

Did it only happen once, or systematically? Do you have any mods?

**Comment by lucashergotte** [comment]
finally the problem no longer appeared

**Comment by lucashergotte** [comment]
finally the problem no longer appeared
