### ISSUE TITLE
Fully customizable keyboard controls

### ISSUE THREAD

**Issue by Sefie1999AD** [Albeoris/Memoria#9]
FFIX lets you customize all the buttons on a controller, but playing on a keyboard is really hard due to some forced controls, such as WASD being always reserved for movement. I'd like to use directional keys for movement, and WASD (or WAXD) for keyboard versions of the controller's A, B, X, Y buttons. Currently, this is impossible, as you can't set any non-movement commands on WASD. Is there a way to add an ini file that lets you completely rebind all the commands (keyboard and controller alike) in the game, with a chance to set WASD buttons for something else than movement?

**Comment by Albeoris** [comment]
Yes, it's possible.
How do you see the format of the key binding section?
Can you share an your sample config?

**Comment by Sefie1999AD** [comment]
I was thinking of something like this, for example:

[Controls_Keyboard]
Left=LeftArrow
Right=RightArrow
Up=UpArrow
Down=DownArrow
Confirm=X
Confirm=Enter
Cancel=D
Menu=W
Cards=A
Pause=Backspace
CameraLeft=Z
CameraRight=C
FixCamera=Q
Perspective=E
Help=S

[Controls_Gamepad]
Left=DpadLeft
Right=DpadRight
Up=DpadUp
Down=DpadDown
Confirm=A
Cancel=B
Menu=Y
Cards=X
Pause=Start
CameraLeft=LB
CameraRight=RB
FixCamera=LT
Perspective=RT
Help=Back

**Details:** Entering the same action multiple times leads to the same action being mapped to all those controls. For example, in the above example, Confirm is mapped to keyboard's X, Enter and controller's A. All of these controls override every saved game's control settings (or you could add a required switch "OverrideSaveControls=true" to override save's controls). If some line is left empty (for example, "Pause="), the game uses the default settings. Gamepad controls could be given as the way I described them above, or if you think it's easier, as button numbers. It would be great if left analog stick automatically did the same as D-pad directions.

Feel free to change the syntax into a more professional or user-friendly style. :) Thanks!

**Comment by Albeoris** [comment]
Need to rewrite "HonoInputManager" class.

**Comment by Sefie1999AD** [comment]
I see. Do you think it will be possible to implement, or will it be too hard or time-consuming?

**Comment by Albeoris** [comment]
Will see. :)

**Comment by Albeoris** [comment]
At the moment I do not have assistants. Together you can move mountains.

**Comment by Sefie1999AD** [comment]
Alright, take your time. :) Unfortunately, I'm not really familiar with programming, and I have no idea how Unity engine works, so I'm not of much help there. :/ Perhaps you could ask Kaldaien (the maker of FFX/X-2's Untitled Project X mod) or some other modders to help you out a bit?

**Comment by GuyInDogSuit** [comment]
It is kinda awkward playing with an Xbox360-style controller, where B is the accept button when you load up the game, though I change it in the config to A.
