### ISSUE TITLE
Widescreen camera panning issue

### ISSUE THREAD

**Issue by NyxFF** [Albeoris/Memoria#914]
I noticed that some camera movements (probably because of widescreen support) do not behave properly. For example after the Sea Lion battle the camera doesn't move all the way up to show the jesters. As this affects storytelling I thought I'd point it out.

**Comment by snouz** [comment]
I can't reproduce this problem, the camera pans correctly upward to show Zorn and Thorn after the fight.

**Comment by NyxFF** [comment]
Yes! So I meddled with the settings and the cause was the camera stabilizer was set to 99 (was there by default) which is kind of broken compared to 98. The camera must've taken so long to follow that the scene ended without showing the jesters:)
