### ISSUE TITLE
Texture animation not working here

### ISSUE THREAD

**Issue by shinra358** [Albeoris/Memoria#918]
@16:26: https://www.youtube.com/watch?v=3iA2qSRUdfE the eyes are supposed to be closing but they dont.

on playstation, thats how it worked. this was a bug introduced in the pc version

**Comment by snouz** [comment]
original
https://youtu.be/Ap3Vju8Y7qw?si=SpSog8RsqiaQxwJU&t=1181

**Comment by snouz** [comment]
Adding to the sfx megathread
