### ISSUE TITLE
Alternate Fantasy & Beatrix Mod Extra Bosses Get Stuck In Battle (SFXRework issue for 2 of the fights)

### ISSUE THREAD

**Issue by Neostraw** [Albeoris/Memoria#924]
hi, I wanted to flag this issue because I came across it while I was playing with mods enabled.

in the extra boss fights that come with the Beatrix Mod & Alternate Fantasy mods (the ones that Hades gives), the battle will get stuck in 3 of the 4 bosses (i only figured out what is happening for 2 of the 4 bosses). what happens is that the game itself is still running, but it seems like the characters and enemies get stuck queuing their commands and the game gets stuck in a stuttered state (with the exception of the Tantarian fight). their in-game animations will still continue but nothing happens, and no further commands can be inputted. this occurs in slightly different ways for 3 of the 4 bosses that are affected.

i believe this is the same issue as what was happening with Valia Paria in the Desert Palace and the SFXRework setting, but wanted to confirm that my game never stuttered with the Valia Paria fight (i kept it at SFXRework = 1 throughout my entire gameplay up until the extra boss fights).

while I only use the Beatrix Mod, this occurs in Alternate Fantasy too which I discovered when I toggled it on to test the issue while I was troubleshooting one of the bosses.

it has something to do with the SFXRework setting in the Memoria.ini config. I've listed what happens under both conditions (SFXRework = 0 or 1) for each boss fight

BOSSES AFFECTED: Tantarian (The Monster Book), Meltigemini (The Jesters), Chaos Guardians (The Guardians)

Tantarian boss -- 
SFXRework 0 OR SFXRework = 1
On occasion, when one of the monsters that open in Tantarian's book is defeated, BOTH the monster and Tantarian will show its death animation, despawning both. This leaves the party unable to queue any further commands towards Tantarian (it is removed from the selection target list altogether) -- but they CAN still execute commands as long as it targets the party. The "Ouch!" window from Tantarian seems to skip entirely when the bug is triggered and the battle will never end. The game has to be closed or the party has to kill itself into a Game Over to enter a different menu.

I have absolutely no idea what could be triggering the Tantarian bug, it's not like the rest of the extra boss fights because it doesn't stutter the game itself into a stalled state (since commands can still be selected and executed, the command menu will still appear when ATB bar is filled).

whether this bug triggers or not seems to be luck dependent on whether the "Ouch!" message will go through or not.
i basically had power my way through this fight over and over again until I got lucky that I could get through every single monster without the bug triggering to move onto the rest of the boss fights.

Meltigemini --
SFXRework = 0
Berserk/Luna casted after a certain amount of HP (STUTTERS, neither party nor enemy in the field can execute commands -- the automatic Attack command does not execute under Berserk)
Bypass Berserk (killing it in one blow with Steiner's Shock after being boosted by Might), enter second stage (STUTTERS) -- actually not sure if Berserk can be bypassed or if the game is stalling before Berserk gets executed

SFXRework = 1
SOMETIMES works fine, Berserk casted and both party and enemy can still Attack, then second stage entered
SOMETIMES Still enters second stage if enemy is killed in one blow

I think with Meltigemini, the issue is the animation that triggers when the twins separate + the animation for teleporting KO allies out of the fight will stutter the fight when SFXRework = 0

Genuinely not sure why it works sometimes and not others

Chaos guardians -- 
SFXRework = 0
Lich's Death-cutter triggers (STUTTERS the game, Lich stuck in a looped animation, no further commands execute from party and enemy)
Kraken's Bubble-gun + follow up hit (WORKS as normal)

SFXRework = 1
Bubble-gun (STUTTERS the game -- Bubble-gun animation does not go through as if nothing comes out of Kraken, but Kraken will still execute follow-up hit animation. No damage appears from both. The battle then stutters)
Death-cutter (WORKS as normal, battle continues)

TROUBLESHOOTING BOTH MELTIGEMINI & CHAOS GUARDIANS:
I figured out a way of troubleshooting the SFXRework issue, this works for both Meltigemini & Chaos Guardians, but only the Chaos Guardians require you to do this because of the sequencing of the fight.

Meltigemini --
Enter the fight with SFXRework = 1 as the saved setting, this is the easiest way of doing it. But the below solution for the Chaos Guardians will also work (see below).

Chaos Guardians --
Enter the fight with SFXRework = 0 as the saved setting (to prevent Bubble-gun from ever stuttering the game since Lich will only begin attacking once the other 3 are killed off)
The MOMENT you hear the death cry or the death animation begin for the third chaos guardian killed (right before Lich enters its attacking mode), PAUSE the game, then open the Memoria.ini config file, and then change the SFXRework setting to SFXRework = 1. 
SAVE the file, close the file, and then RESUME (unpause) the game. I usually tried to give it a second for the changed settings to apply.
This should work regardless of whether you kill off Tiamat, Kraken, and Maliris individually or all together

This method ALSO applies to the Meltigemini fight, if you were to start the fight off with SFXRework = 0. The moment Meltigemini is about to cast Berserk or if you killed it off in one blow: PAUSE the game, open the Memoria.ini config file, and change SFXRework = 1. There MAY be some glitchy looking animations with the Meltigemini fight from whichever the last character executed their command, but this goes away the moment Berserk gets casted/the second phase begins.

In summary: the moment the stuttering condition/moves are about to trigger, PAUSE the game, open the Memoria.ini config file, and change the SFXRework setting to 1. Save the file, close the file, then resume the game.

--------------

I am not sure if this is a known bug, but I was unable to find any information about it anywhere for the extra boss fights. The only other known instance I saw was the Valia Paria issue that was raised in the past, which is what led me to figure out the troubleshooting method for Meltigemini and Chaos Guardians. Actually, that one webpage with the Valia Paria issue was the only thing I could find at all related to this so I had to guess my way through this.
But I have absolutely no idea what is happening with Tantarian. 

I spent basically a week figuring this all out on my own so hopefully anyone else who is having issues can find this message to help guide them through their game's issues!

Sorry this is SO LONG, I wanted to be as specific as possible to help you all out with investigating the bug!

**Comment by Neostraw** [comment]
ugh sorry I'm not sure what's happening at all with the Meltigemini fight after all. I got it working when I was writing up the issue, but now it's not working at all with SFXRework = 1 (I even tried to toggle it back and forth between 0 and 1). It's stuck after enough damage is dealt after Berserk. No idea anymore.

**Comment by snouz** [comment]
@Tirlititi

**Comment by Tirlititi** [comment]
Thank you for the very detailed report. However, I am pretty sure that these bugs (or at least most of them) don't exist in a proper, up-to-date, installation of the Alternate Fantasy mod: I have tested these fights several times and saw multiple other people doing them without any troubleshooting.

So, at a first glance, I would say:
- either updating Memoria and the mod(s) will solve the problem,
- or these bugs only happen with the Beatrix Mod (you shouldn't have both mods activated at the same time, but if you do, the mod with highest priority in the mod manager will be the one that really matters concerning these bugs, so it might be that it was the Beatrix Mod even when you tried Alternate Fantasy, depending on how you proceeded exactly),

It's also possible that some of these bugs are really there for everyone but for some reason few people ever experienced it. I think that Lich's attack could be in that case, since ``SFXRework = 0`` is a rather rare setting and that one doesn't look like anything I've seen so far. For the context, Lich's attack in the remaster is a bit glitched by default because it skips a small part of its animation. I don't remember right now how I fixed it, but now that animation is fixed (I don't even remember if I fixed it in my mods or in Memoria, I'll have to check). So maybe the fix works properly in ``SFXRework`` mode but is a complete failure when it's deactivated.
You can see the glitched animation there for example: [https://www.youtube.com/watch?v=N_77ACz6NR4&t=2m45s](https://www.youtube.com/watch?v=N_77ACz6NR4&t=2m45s)

In general, I would strongly advise against chaning the option ``SFXRework`` mid-game (it's not as game breaking as something like enabling the Model Viewer mid-game but still). Well done for finding that solution to bypass the problems though.

I'll investigate and do the updates required to solve these.

**Comment by Neostraw** [comment]
> Thank you for the very detailed report. However, I am pretty sure that these bugs (or at least most of them) don't exist in a proper, up-to-date, installation of the Alternate Fantasy mod: I have tested these fights several times and saw multiple other people doing them without any troubleshooting.
> 
> So, at a first glance, I would say:
> 
>     * either updating Memoria and the mod(s) will solve the problem,
> 
>     * or these bugs only happen with the Beatrix Mod (you shouldn't have both mods activated at the same time, but if you do, the mod with highest priority in the mod manager will be the one that really matters concerning these bugs, so it might be that it was the Beatrix Mod even when you tried Alternate Fantasy, depending on how you proceeded exactly),
> 
> 
> It's also possible that some of these bugs are really there for everyone but for some reason few people ever experienced it. I think that Lich's attack could be in that case, since `SFXRework = 0` is a rather rare setting and that one doesn't look like anything I've seen so far. For the context, Lich's attack in the remaster is a bit glitched by default because it skips a small part of its animation. I don't remember right now how I fixed it, but now that animation is fixed (I don't even remember if I fixed it in my mods or in Memoria, I'll have to check). So maybe the fix works properly in `SFXRework` mode but is a complete failure when it's deactivated. You can see the glitched animation there for example: https://www.youtube.com/watch?v=N_77ACz6NR4&t=2m45s
> 
> In general, I would strongly advise against chaning the option `SFXRework` mid-game (it's not as game breaking as something like enabling the Model Viewer mid-game but still). Well done for finding that solution to bypass the problems though.
> 
> I'll investigate and do the updates required to solve these.

hi, thank you for looking into this! there was very little info on what it could be so definitely wanted to flag the issue.
on my end, confirming that the Lich Death-Cutter animation in SFXRework mode, when working, appears how you described it as. when it's not working, it looks like the animation is stuck near the end of it and just loops continuously whereupon the game will stutter.

the issue occurs when only Beatrix mod is activated or only Alternate Fantasy is activated.

my list of installed & activated mods below (appears in the order that i have them set in my game):

Memoria Launcher 2024-08-24

Mods - 
1. Exp, AP, Gil, Rewards Tweaks 4.0.1 (active)
2. No Exp Plus 4.0.1 (active)
3. Amazing Quina 2.0 (active)
4. Black Cat - Endgame Shop 1.0 (active)
5. Support Ability Cost 4.0.1 (active)
6. Beatrix Mod 5.2 (active)
7. Moguri Mod 9.0 (active)
8. Playable Character Pack 1.2 (INACTIVE)
9. Alternate Fantasy 6.6 (INACTIVE)

-------------------
for now, i'm going to try to go through the fights again with Alternate Fantasy uninstalled entirely, running only Beatrix Mod, and leaving SFXRework = 1, by default. will report back to what happens with that change.

if it still persists, i'm going to try to record a video of the issues happening for all the affected boss fights. i will show the different SFXRework conditions for Chaos Guardians since Tantarian and Meltigemini seems to be its own separate issue. 

with that said, the Tantarian and Meltigemini fights were definitely much more annoying issues for me than the issue with Chaos Guardians since I was forced to repeatedly redo those fights over and over again until I was able to both get through the fight and not have the bug trigger.

thank you for the help!

**Comment by Neostraw** [comment]
> > Thank you for the very detailed report. However, I am pretty sure that these bugs (or at least most of them) don't exist in a proper, up-to-date, installation of the Alternate Fantasy mod: I have tested these fights several times and saw multiple other people doing them without any troubleshooting.
> > So, at a first glance, I would say:
> > ```
> > * either updating Memoria and the mod(s) will solve the problem,
> > 
> > * or these bugs only happen with the Beatrix Mod (you shouldn't have both mods activated at the same time, but if you do, the mod with highest priority in the mod manager will be the one that really matters concerning these bugs, so it might be that it was the Beatrix Mod even when you tried Alternate Fantasy, depending on how you proceeded exactly),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's also possible that some of these bugs are really there for everyone but for some reason few people ever experienced it. I think that Lich's attack could be in that case, since `SFXRework = 0` is a rather rare setting and that one doesn't look like anything I've seen so far. For the context, Lich's attack in the remaster is a bit glitched by default because it skips a small part of its animation. I don't remember right now how I fixed it, but now that animation is fixed (I don't even remember if I fixed it in my mods or in Memoria, I'll have to check). So maybe the fix works properly in `SFXRework` mode but is a complete failure when it's deactivated. You can see the glitched animation there for example: https://www.youtube.com/watch?v=N_77ACz6NR4&t=2m45s
> > In general, I would strongly advise against chaning the option `SFXRework` mid-game (it's not as game breaking as something like enabling the Model Viewer mid-game but still). Well done for finding that solution to bypass the problems though.
> > I'll investigate and do the updates required to solve these.
> 
> hi, thank you for looking into this! there was very little info on what it could be so definitely wanted to flag the issue. on my end, confirming that the Lich Death-Cutter animation in SFXRework mode, when working, appears how you described it as. when it's not working, it looks like the animation is stuck near the end of it and just loops continuously whereupon the game will stutter.
> 
> the issue occurs when only Beatrix mod is activated or only Alternate Fantasy is activated.
> 
> my list of installed & activated mods below (appears in the order that i have them set in my game):
> 
> Memoria Launcher 2024-08-24
> 
> Mods -
> 
>     1. Exp, AP, Gil, Rewards Tweaks 4.0.1 (active)
> 
>     2. No Exp Plus 4.0.1 (active)
> 
>     3. Amazing Quina 2.0 (active)
> 
>     4. Black Cat - Endgame Shop 1.0 (active)
> 
>     5. Support Ability Cost 4.0.1 (active)
> 
>     6. Beatrix Mod 5.2 (active)
> 
>     7. Moguri Mod 9.0 (active)
> 
>     8. Playable Character Pack 1.2 (INACTIVE)
> 
>     9. Alternate Fantasy 6.6 (INACTIVE)
> 
> 
> for now, i'm going to try to go through the fights again with Alternate Fantasy uninstalled entirely, running only Beatrix Mod, and leaving SFXRework = 1, by default. will report back to what happens with that change.
> 
> if it still persists, i'm going to try to record a video of the issues happening for all the affected boss fights. i will show the different SFXRework conditions for Chaos Guardians since Tantarian and Meltigemini seems to be its own separate issue.
> 
> with that said, the Tantarian and Meltigemini fights were definitely much more annoying issues for me than the issue with Chaos Guardians since I was forced to repeatedly redo those fights over and over again until I was able to both get through the fight and not have the bug trigger.
> 
> thank you for the help!

brief update after reattempting the fights (around 5 times each) with the proposed settings:

i uninstalled Alternate Fantasy altogether, leaving only Beatrix Mod active and installed (rather than only deactivating it).

some interesting things happened with the applied changes:

Tantarian --
i discovered that i'm supposed to encounter blue Tantarian as part of the monsters you fight here. 
i had NO IDEA because, prior to the changes i made above, i NEVER encountered it during successful runs of this fight.
 
before the changes, i only had to fight the three monsters (blue Nymph, Torama, Agares) in any order they appeared. 
once all three are defeated, and if the bug does not trigger, the third monster will despawn book Tantarian, and the victory cue will trigger as normal, and the rest proceeds as expected. 
Hades will accept that as a victory, heal, and unlock the next fight (or heal you and continue as normal when re-fighting).

so, i guess that is a new item i'm including as part of the issue for Tantarian.

HOWEVER, the issue with Tantarian still persists with the proposed changes under both SFXRework = 0 or 1. 
with that said, I have not encountered the bug as often so far, though I'm not sure if that's random. 

Meltigemini --
the issues with this fight seems to be resolved with the proposed changes so far, but will continue to do trials to see if it will trigger again.

the issues seem to be resolved under both SFXRework = 0 or 1

Chaos Guardians --
the issues for this fight still persists, with the proposed changes not resolving it. 
the same issues are still triggered under the same conditions (SFXRework = 0 makes Lich buggy, SFXRework = 1 makes Kraken buggy).
the previous discovered solution still seems to work to address the issue as a workaround. 

accidental discovery with Chaos Guardians:
starting on SFXRework=0 -- 
if Lich goes into attack mode before any of the other 3 guardians are killed off, and if Lich uses Death-cutter, even after the animation starts to stutter, you can still still pause and flip SFXRework = 1, and as long as the other guardians proceed with their queued attacks afterwards, the fight will continue as normal. I couldn't figure out if the party can still queue their attacks first after the switch because they weren't fast enough to get their turn in first, or perhaps the bug was stalling them. not sure.

if Lich goes into attack mode AND Kraken is still alive -- the above still works for dealing with Lich if he uses Death-cutter.
however, you have to be much faster with switching back and forth between SFXRework = 0 or 1 if Kraken uses Bubble-gun + follow-up hit.
if you're on SFXRework = 1 and Kraken starts to use Bubble-gun, even if you switch back to SFXRework = 0 before the animation goes through, while the Bubble-gun animation and damage might connect, the follow-up damage will not (as expected from the issue) and the entire fight will stutter/stall after Kraken's animation finishes. 
switching back and forth between SFXRework = 0 or 1 afterwards won't resume the fight.


------------------------------------
i'll try to record the Chaos Guardians and Tantarian issues with the current changes so it's clearer to see what's happening. if I can get Meltigemini issue to trigger, i'll try to record that too -- if not, i will assume we found the solution for the issue with that fight.

with that said, after the initial test with uninstalling Alternate Fantasy outright, i think having BOTH Alternate Fantasy AND Beatrix Mod installed, with ONLY one or the other activated, creates a ton of issues (missing Tantarian fight, Meltigemini stuttering) with the extra bosses for both mods.

it seems that, somehow for my game, it's not enough to keep one or the other deactivated, one of them has to be uninstalled altogether.

**Comment by Tirlititi** [comment]
Ok, I can confirm that these bugs, except Lich's attack, are bugs of the Beatrix Mod, because I haven't updated it since a long time. I'll fix these different things. Thanks again.

"Deactivated" and "Not installed" are the same thing: a deactivated mod cannot have an impact on the game.

**Comment by Tirlititi** [comment]
I close the ticket. I have yet to fix the problems that strictly concern the Beatrix mod but there should be nothing to do on Memoria anymore.
