### ISSUE TITLE
New Install - Input String not correct

### ISSUE THREAD

**Issue by RevTheory-Roe** [Albeoris/Memoria#932]
Im doing a fresh install after a HDD failure so im trying to get back my mods, when ever i try and load the launcher, or click mod manager. im getting an input string error. and only getting 4 mods in the whole catalog

![image](https://github.com/user-attachments/assets/96e052c3-e4e1-40e4-92e8-2eadb28806fe)

**Comment by Tirlititi** [comment]
Can you share the section ``[Mod]`` in your ``Memoria.ini`` (which is in your game's folder) and also the files ``ModDescription.xml`` that are in the mod folders of each of the 4 mods you use?

**Comment by RevTheory-Roe** [comment]
Memoria.ini
[Mod]
	; Custom configurations and/or assets are loaded from custom folders inside the "FINAL FANTASY IX" root folder
	; The "Priorities" field is only a hint for the Launcher's Mod Manager; mod priorities in-game are still defined by their order in "FolderNames"
	; UseFileList (default 1) 0 = Don't use mod file lists / 1 = Do not generate the missing file lists of Mod Folders when launching the game but use it if it exists / 2 = Generate "ModFileList.txt" of active mods
	; MergeScripts (default 0) 0 = Don't attempt to merge scripts, top most mod gets priority / 1 = [Experimental] Attempt to merge scripts, if a conflict is detected top most mod takes priority
FolderNames =   
Priorities = 
UseFileList = 1
MergeScripts = 0

the 4 descriptions isnt the issue, i have no mods downloaded atm as there is only 4 mods showing in mod catalog (ie missing a ton.)

![image](https://github.com/user-attachments/assets/ec623725-8a88-4054-9789-b37fde723fd2)

**Comment by Tirlititi** [comment]
Hmmm... That's very strange.
Try deleting the file ``ModCatalog.xml`` in your game's folder. It might be that it is wrongly formatted for some reason and in "read-only" mode, which would prevent the catalog to be updated. You should have another ``ModCatalog.xml`` popping after opening the Mod Manager, hopefully that one will be complete.

**Comment by Tirlititi** [comment]
Oh! It's not your re-installation that was the problem. It was the latest update of the catalog online that contained an error. Your problem was happening to everyone.
I should have fixed it now. It is possible that installing Trance Seek will make that warning popup until DV fixes it from his end, but now even with that warning message there should be no problem.

**Comment by RevTheory-Roe** [comment]
> Oh! It's not your re-installation that was the problem. It was the latest update of the catalog online that contained an error. Your problem was happening to everyone. I should have fixed it now. It is possible that installing Trance Seek will make that warning popup until DV fixes it from his end, but now even with that warning message there should be no problem.

dont use trance seek thankfully ukk test after this FF14 dungeon

**Comment by RevTheory-Roe** [comment]
So still getting the same inpuit string error but all the mods are there which is an improvment
