### ISSUE TITLE
Rendering problem at Iifa tree without Moguri

### ISSUE THREAD

**Issue by SamsamTS** [Albeoris/Memoria#937]
![image](https://github.com/user-attachments/assets/166cfe4c-9883-417c-b19b-48deac1f26fd)
![image](https://github.com/user-attachments/assets/12caba21-3b7a-4959-b45b-825ff3dea1c9)

**Comment by snouz** [comment]
They're shadows rendered very ugly by the horrible automated cutting by Square/Silicon. Not really a bug.
