### ISSUE TITLE
Latest build crashes on startup

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#94]
On a clean install, and no matter where I launch it, the last version (4e320b8) of the memoria patcher crashes with the attached image error.
![2020-05-09 17_53_33-E__SteamLibrary_steamapps_common_FINAL FANTASY IX_Memoria Patcher exe](https://user-images.githubusercontent.com/9964576/81482861-592b7480-923a-11ea-9ed9-579da34b3e41.jpg)

**Comment by Albeoris** [comment]
I went to do a clean install. :)

**Comment by Albeoris** [comment]
https://github.com/Albeoris/Memoria/releases/tag/v2020.05.10
Done
