### ISSUE TITLE
Can memoria push a small update for the localization modding?

### ISSUE THREAD

**Issue by yuyu-2021** [Albeoris/Memoria#940]
Hi there, We are the Chinese localization team . It's been a long time !

Been following the progress of Memoria .

We are excited to see that Memoria has added new features for the localization modding .

And It is FANTASTIC .

Is it possible that memoria push a small update for this feature , so that we can make some modification and then release our work ?

**Comment by Tirlititi** [comment]
Hopefully a new release will come very soon.

**Comment by yuyu-2021** [comment]
> Hopefully a new release will come very soon. Maybe tonight. If not, that's surely a matter of days.

That is of a very good news .

Thank you ,haha !

[FF9 2024-11-02 07-07-05](https://github.com/user-attachments/assets/08392337-4e74-4350-8bc1-9cf36f5a8a96)

**Comment by Tirlititi** [comment]
Here we are, sorry for the long wait!

**Comment by yuyu-2021** [comment]
> Here we are, sorry for the long wait!

Oh my !!  I just noticed it today!
 
Hahahhahaha！！  This is DAMN GOOD !!😁😁
 
We'll conduct the test right away and start to finish the final work!
 
You're amazing !
