### ISSUE TITLE
FFIX and launcher crash after patching

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#95]
Hi,
I've patched a virgin FFIX with Memoria-patcher, and it patched successfully. But afterwards, FF9 and FF9_launcher won't launch at all. It doesn't create any crash log in root or x64. I couldn't catch any bug with the debugger (patching or launching the game). I tried twice to the same result. Virgin game works, patched it doesn't launch.
To be precise, launcher doesn't respond at all, and FF9.exe opens the window and closes immediatly.

I'm testing on Windows 7 x64 in French.

**Comment by snouz** [comment]
Also, it does not create memoria.ini before crashing. I can test on W10 if you think it's needed.

**Comment by Albeoris** [comment]
Hi! Please, share this file:
\FINAL FANTASY IX\x64\FF9_Data\output_log.txt

**Comment by snouz** [comment]
Here it is, dated from a minute ago, after I patched a fresh game
`Initialize engine version: 5.2.3p2 (b5869bab0ca4)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 9.0c [igdumd64.dll 9.17.10.4229]
    Renderer: Intel(R) HD Graphics 3000
    Vendor:   Intel
    VRAM:     880 MB (via DXGI)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=1 INTZ=1 NULL=1 RESZ=1 SlowINTZ=0
Begin MonoManager ReloadAssembly
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\ICSharpCode.SharpZipLib.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\ICSharpCode.SharpZipLib.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\XInputDotNetPure.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\XInputDotNetPure.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\System.Core.dll (this message is harmless)
- Completed reload, in  0.580 seconds
<RI> Initializing input.

<RI> Input initialized.

desktop: 1600x900 60Hz; virtual: 1600x900 at 0,0
<RI> Initialized touch support.

Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\System.dll (this message is harmless)
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Memoria.Prime.dll (this message is harmless)
Setting up 1 worker threads for Enlighten.
  Thread -> id: 1694 -> priority: 1 
`

**Comment by snouz** [comment]
Here's the file after launching a vanilla install (it launches successfuly)

Initialize engine version: 5.2.3p2 (b5869bab0ca4)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 9.0c [igdumd64.dll 9.17.10.4229]
    Renderer: Intel(R) HD Graphics 3000
    Vendor:   Intel
    VRAM:     880 MB (via DXGI)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=1 INTZ=1 NULL=1 RESZ=1 SlowINTZ=0
Begin MonoManager ReloadAssembly
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\ICSharpCode.SharpZipLib.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\ICSharpCode.SharpZipLib.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\XInputDotNetPure.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\XInputDotNetPure.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\System.Core.dll (this message is harmless)
- Completed reload, in  0.434 seconds
<RI> Initializing input.

<RI> Input initialized.

desktop: 1600x900 60Hz; virtual: 1600x900 at 0,0
<RI> Initialized touch support.

Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX\x64\FF9_Data\Managed\System.dll (this message is harmless)
Unloading 3 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.452392 ms

Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 1059.
Total: 0.227017 ms (FindLiveObjects: 0.052546 ms CreateObjectMapping: 0.034894 ms MarkObjects: 0.129313 ms  DeleteObjects: 0.009441 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.327594 ms
40 BundleScene.Awake
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)


Unloading 6 unused Assets to reduce memory usage. Loaded Objects now: 24050.
Total: 26.785583 ms (FindLiveObjects: 1.348967 ms CreateObjectMapping: 0.337447 ms MarkObjects: 25.024456 ms  DeleteObjects: 0.074304 ms)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 16bc -> priority: 1 
Unloading 3 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.652341 ms

Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 24367.
Total: 28.485548 ms (FindLiveObjects: 1.806286 ms CreateObjectMapping: 0.473739 ms MarkObjects: 26.165701 ms  DeleteObjects: 0.038178 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 17)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 24367.
Total: 27.596361 ms (FindLiveObjects: 1.446671 ms CreateObjectMapping: 0.259858 ms MarkObjects: 25.857811 ms  DeleteObjects: 0.030378 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.418755 ms

Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 24372.
Total: 30.164984 ms (FindLiveObjects: 1.517691 ms CreateObjectMapping: 0.270942 ms MarkObjects: 28.343508 ms  DeleteObjects: 0.031199 ms)

Unloading 3 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.355946 ms

Unloading 66 unused Assets to reduce memory usage. Loaded Objects now: 24393.
Total: 29.167419 ms (FindLiveObjects: 1.527543 ms CreateObjectMapping: 0.233585 ms MarkObjects: 27.349230 ms  DeleteObjects: 0.055420 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 17)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 24393.
Total: 28.965445 ms (FindLiveObjects: 1.491007 ms CreateObjectMapping: 0.230301 ms MarkObjects: 27.215401 ms  DeleteObjects: 0.027094 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 17)
UnloadTime: 1.049288 ms

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 24418.
Total: 29.683033 ms (FindLiveObjects: 1.660551 ms CreateObjectMapping: 0.300500 ms MarkObjects: 27.680517 ms  DeleteObjects: 0.038588 ms)

**Comment by Albeoris** [comment]
Ok, we figured out that the problem is not in the game, but in Launcher.

The game should only start after it. For some reason, the launcher does not start on Windows 7 x64 FR. Need entries from EventLog.

**Workaround:**

- Run Memoria.Patcher.exe
- Delete FF9_Launcher.exe
- Rename FF9_Launcher.bak to FF9_Launcher.exe
- Run the game via Steam

After that, everything should work.

**Comment by Albeoris** [comment]
Fixed
https://github.com/Albeoris/Memoria/releases/tag/v2020.05.11
