### ISSUE TITLE
REQUEST: Namingway at moogles

### ISSUE THREAD

**Issue by WarpedEdge** [Albeoris/Memoria#952]
As the title suggests, I am not sure if this is a simple or complicated add, but historically Namingway in SQEX games was an NPC that would allow you to change the name of your party members. While yes you can adjust the main cast's names when they are first introduced, sometimes people would like to change names later or with newer playable characters starting to being added, an option to change a party member's name as an option when talking to a moogle would be a neat add.

Quick process:
1) Talk to Moogle NPC
2) Select Namingway feature
3) Select the party member in which you would like to rename
4) Profit :)

**Comment by psxlover** [comment]
@WarpedEdge there is a way to rename the players already and it requires a namingway card.

**Comment by psxlover** [comment]
If it is limited (haven't tried actually renaming anyone), perhaps a cheat could be introduced to make the NCP not use the namingway card. I don't have a save in PC that far into the game to test.

**Comment by Tirlititi** [comment]
It is unlimited: you don't lose the Namingway card for renaming a character, you only need to have one.
It is a NPC met in Daguerreo.
So the only extension would be to allow renaming characters from more places and earlier in the game. I'm not sure if a custom item could be coded to have that effect...

**Comment by WarpedEdge** [comment]
If that is the case, I can as an option make it available earlier in the
game to be bought at a vendor or something. This can be closed then.
