### ISSUE TITLE
Widescreen exclusion does not work as intended

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#96]
In the last version, some fields are supposed to be excluded from widescreen (mainly, those that are not larger than 4/3 res witdth)
Instead, this does not seem to be applied. 3D objects and effects are a still visible on the side bars.
![2020-05-11 19_50_18-FINAL FANTASY IX - Map_ 104, Loc_ 33 Name_ Alexandria_Square](https://user-images.githubusercontent.com/9964576/81613413-b95b1b80-93de-11ea-926a-64c8b327a4be.png)

2) Widescreen is disabled temporarily when I enter a marked "non-widescreen" field FROM THE WORLDMAP, and until I go back to the worldmap.
example N°1: Next to dali on the worldmap, widescreen on
I enter the mountain scene (excluded, 455), widescreen is turned off. But when I go to the top, widescreen is still off, despite screen 456 not being excluded itself. But when I exit, widescreen is on again

What I suppose is happening: widescreen is correctly suspended and unsuspended between worldmap and a field, but not at all between field (in any direction: widescreen -> narrow, narrow -> widescreen)

**Comment by snouz** [comment]
I'm working on the list of screens that need to be added to the list to avoid glitches. It'll be done today (in a few hours I'm busy)

**Comment by snouz** [comment]
Could this be a problem with pre-loading? I know that fields are preloaded in the script (when you arrive at a certain point or cross a region.

Also, in some very scripted scenes, after a fight, it switches correctly to narrow (but stays like that when continuing). An example: the fight with Garland and the dragon at the end of Pandemonium, just before kuja.

**Comment by Tirlititi** [comment]
"PreloadField" is a thing for the PSX version of the game. It is simply skipped in the PC version so the problem comes from somewhere else.

**Comment by snouz** [comment]
I've done the full list of fields to exclude. You can replace the original list with this.
https://pastebin.com/KVCErpTT
I've done the whole game in fast forward and noted all the strange ones. So this list contains all those that are 1280 width, and the larger ones that have problems in WS.

**Comment by snouz** [comment]
Removed a few duplicates.
https://pastebin.com/KWwBwCRH

**Comment by Albeoris** [comment]
Fixed!
![](https://i.imgur.com/zn0TkeQ.jpg)
