### ISSUE TITLE
After latest update (Nov 17 2024), Memoria launcher is broken on Steam Deck.

### ISSUE THREAD

**Issue by majin-mo** [Albeoris/Memoria#960]
Hello! After the latest patch, I’m unable to start the game on Steam Deck. I get to the launcher but when I press play the game returns to the Steam page. Currently I only have Moguri mod and Moguri 30fps cinematic mods activated. The same issue occurs when I deactivate the mods. Any idea on what’s going on or how to alleviate the issue? Thanks!

**Comment by SamsamTS** [comment]
A hotfix as been deployed. Thanks for the report.

**Comment by majin-mo** [comment]
> A hotfix as been deployed. Thanks for the report.

That did the trick!! Thank you so much the quick reply!
