### ISSUE TITLE
crash start bug report with claude sonnet 3.5

### ISSUE THREAD

**Issue by admin-noosphere** [Albeoris/Memoria#961]
[Bug Report] Font Initialization & Asset Loading Failures - Memoria FF9

Version: Memoria 2024-11-17
OS: Windows 10 (Build 26100.0)
Mods: MoguriMain, MoguriVideo
SteamSDK: Initialized
Audio: MiniAudio (48000Hz)

Issue: Multiple cascading errors starting from font initialization, leading to failure in loading game assets. Main errors:

1. Initial Font Error:
17.11.2024 05:21:58 |E| System.TypeInitializationException: An exception was thrown by the type initializer for AssetManager ---> System.FormatException: Input string was not in the correct format
   at System.Int32.Parse (System.String s) [0x00000]
   at Memoria.WindowManager.CenterWindow ()

2. Subsequent Failed Components:
- Status sets loading
- Battle actions loading
- Character base stats
- Items and effects
- Character equipment
- Battle parameters

Root cause appears to be in WindowManager.CenterWindow() causing a format exception during AssetManager initialization.

All errors follow same pattern with FontManager attempting to load/set default font and failing.

**Comment by SamsamTS** [comment]
A hotfix as been deployed. Thanks for the report.
