### ISSUE TITLE
Submod options not parsed by order of declaration 

### ISSUE THREAD

**Issue by faospark** [Albeoris/Memoria#967]
![Screenshot_205](https://github.com/user-attachments/assets/67c175fc-3b17-47e0-9ea3-d83751061e72)
before submods  by order of how it was declared on the ModDescription.xml file 
the mod manager seems to be taking into account the <Priority> declaration as an ordinal sorting
Tir explained this to me sometime ago that that is not the case
but rather its function is more of an override of another mod  example
![Screenshot_206](https://github.com/user-attachments/assets/69f1f705-9d3f-4fd1-955d-c910a2c83302)

alternate portrait set will override full portrait set if both are activated 
and partial portrait set will override both . 

the problem with the current mod manager if i have a mod 
![Screenshot_207](https://github.com/user-attachments/assets/9a00b25c-d7b3-4591-a498-9406efcc0e1d)
this will be parsed as 
Full portrait set
Not Related mod 
Alternate portrait set
Partial portrait set

**Comment by SamsamTS** [comment]
I don't really get how this mod options system works but I've been thinking it might need a rework.

I'd like the possibility to to have combo boxes for option that are mutually exclusive.
For example for your Title Screen option a combo box with the following entries would be nice:
- Normal
- Origin
- Old School
- etc

In fact I'd like all the options listed at once instead of everything inside a combo box
> ☑ My option1
> ☑ My option2
> My option3 [combobox]
> ☑ My option4
> ...

What do you think?

**Comment by faospark** [comment]
I agree that the UI really needs an improvement and prefer your latter suggestion as its makes it mcore  
That said if its possible to for modders to explicitly declare a modal window in the center activated via configure button on sidebar. cause scrolling to the side bar is not really a good user experience.

**Comment by SamsamTS** [comment]
Here is what I have in mind.

![ModOptions1](https://github.com/user-attachments/assets/55ec3e3b-4ef7-418f-83fa-d6cb44f6f43b)
![ModOptions2](https://github.com/user-attachments/assets/33199cd2-a8cc-4952-ae7c-351fbeb80027)

New xml tags for submods (all optional for retro-compatibility):
```
<Section>Section 1</Section>
<Group>My group</Group>
<Default/>
<PreviewFile>MyImage.jpg</PreviewFile>
```

`Section` will create a header, must be placed in-between `SubMods`:
```
<Section>Section 1</Section>
<SubMod>...</SubMod>
<SubMod>...</SubMod>
<SubMod>...</SubMod>
<Section>Section 2</Section>
<SubMod>...</SubMod>
<SubMod>...</SubMod>
<SubMod>...</SubMod>
```

`Group` is for mutually exclusive options.
`Default` determine the default option of the group and will automatically be activated by default. `InstallationPath` tag can be omitted for the default option, that means no submod is activated by defaut (removes the need to create an empty submod folder)
 Example of a group:
```
 <Section>My group</Section>
 <SubMod>
     <Name>Default</Name>
     <Group>MyGroup</Group>
     <Default/>
</SubMod>
 <SubMod>
     <Name>Option 1</Name>
     <Group>MyGroup</Group>
     <InstallationPath>...</InstallationPath>
     <Description>Option 1 description</Description>
     <PreviewFile>Previews/Option1.jpg</PreviewFile>
     <Priority>1</Priority>
</SubMod>
 <SubMod>
     <Name>Option 2</Name>
     <Group>MyGroup</Group>
     <InstallationPath>...</InstallationPath>
     <Description>Option 2 description</Description>
     <PreviewFile>Previews/Option2.jpg</PreviewFile>
     <Priority>1</Priority>
</SubMod>
```

This is not final and subject to change. Feel free to comment and suggest improvements.

**Comment by faospark** [comment]
Nice !. 
the new possible markup is literally the same as how i used  to the it in mog-addons albeit how it looks is more blended in the ui 
![Screenshot_212](https://github.com/user-attachments/assets/cb24a85e-b079-41a0-9e95-dfa33aa9256c)
My handy trick to make like you mod options you have there is to
dedicate as submod block that does nothing but serves as a good call to action that there are options inside the mod. 
Similar to your section tag 
I dedicated a submod that does nothing but its Name has text based like headings. 

looking forward for the possible future changes. 
that said please keep the original function of the Priority tag as its very handy for overrides. :)

**Comment by Scyversic** [comment]
Definitely looking forward as well for this overhaul. Currently, I'm getting possible issues with users that may have skipped activating the actual submod, hence reporting why the mod in question was not working for them. A default option will address this as a catch-all for none-the-wiser users. Additionally, if not mentioned already (or I didn't understood it clearly, could be the mutually exclusive feature), the restriction to only select one mod at a time will be great.

**Comment by SamsamTS** [comment]
> Additionally, if not mentioned already (or I didn't understood it clearly, could be the mutually exclusive feature), the restriction to only select one mod at a time will be great.
Yes, that's what the mutually exclusive is. Only one sub-mod from the same group can be active at a time. If I activate a sub-mod that belongs in a group, all other sub-mods of the same group gets deactivated.
