### ISSUE TITLE
Bring back AntiAliasing

### ISSUE THREAD

**Issue by phip3khan** [Albeoris/Memoria#968]
The updated disabled the AntiAliasing and now it looks bad, when checking the memoria.ini there's this comment:
AntiAliasing (default 0) Currently disabled. We found that this setting brings a lot of visual glitches and performance issues.

It was working fine for me

**Comment by Scyversic** [comment]
Bumping this to also request to bring back the built-in Anti-Aliasing we had pre-v.11.17.2024. Per my experience, I have never encountered any game-breaking visual bugs, nor notice anything that would break immersion. As it is removed now, it's pretty glaring and noticeable how we lost any AA we had before. 

I've assumed that it could be a new AA add-on that led to the complete removal of this setting, but then if it's just the current one, again I'd recommend as well to have it back again.

-Emeiru

**Comment by SamsamTS** [comment]
So here is the deal, I restore the option but it won't be on the launcher anymore, only accessible via the ini. Also it will be reset to 0 next update so you will be forced to go into the ini to enable it again.

**Comment by phip3khan** [comment]
Thank you @SamsamTS !
