### ISSUE TITLE
Mods automatically turning off

### ISSUE THREAD

**Issue by Emeiru** [Albeoris/Memoria#971]
Opening the topic here in case other users are experiencing mods automatically turning themselves off when booting the game. I have this player reported to me that it was indeed happening, and I noticed myself that some mods curiously went off as well (of which I clearly remember activating).

**Comment by SamsamTS** [comment]
Do you have a particular example I can try and reproduce? I don't see how main mods can possibly deactivate themselves but I noticed there are some issues with the sub-mods currently, I'll have to investigate.

**Comment by Emeiru** [comment]
> Do you have a particular example I can try and reproduce? I don't see how main mods can possibly deactivate themselves but I noticed there are some issues with the sub-mods currently, I'll have to investigate.

Should have been more specific, sorry about that, but yes, I did notice it was the sub-mods deactivating. I've noticed it in two of my mods (Amazing Steiner/Amazing Quina), I'll be able to really check and see if I can replicate it again, I didn't really took notice of it at first not until a few users reported of submods deactivating, but decided to open an issue just in case others have noticed it.

**Comment by primavistaix** [comment]
Chiming in to say I checked this and have it too partly. I have both Amazing Quina and Steiner installed with the AF submods selected, and currently the Steiner mod deactivates upon game launch if it is higher in priority than the Quina one. Putting Steiner below Quina seems to keep both working on launch, haven't tested moving them around apart from that.

**Comment by Emeiru** [comment]
> Chiming in to say I checked this and have it too partly. I have both Amazing Quina and Steiner installed with the AF submods selected, and currently the Steiner mod deactivates upon game launch if it is higher in priority than the Quina one. Putting Steiner below Quina seems to keep both working on launch, haven't tested moving them around apart from that.

This is incredibly peculiar, both my mods should be compatible regardless of order as they have obviously different installation paths, and don't even have any overlaps mod wise as well.

**Comment by SamsamTS** [comment]
I found the conditions that deactivate sub-mods: when you select the main mod in the mod list after restarting the launcher. As long as you don't click on it should not be deactivated.

I'm reworking the sub-mod system so it won't be an issue in the future but in the meantime we know how to avoid it at least.

**Comment by Emeiru** [comment]
Glad to finally know the cause! I'll keep users informed so they won't get confused and share the temporary workaround on this. I probably haven't experienced this issue at all since I diligently check my own mods (activated or not before launching, this is even before the latest updates lol).
