### ISSUE TITLE
Fat continent name

### ISSUE THREAD

**Issue by moldsax** [Albeoris/Memoria#972]
![377840_1](https://github.com/user-attachments/assets/a667195c-71d1-40e2-a963-873f17a90bad)
vanila
![377840_11](https://github.com/user-attachments/assets/5e57921e-f32b-4f5a-b59e-661a003822a2)
memoria

After the recent update, this is what it looks like when I play in Japanese.
I don't have time to check everything, but this anomaly did not occur in US.

**Comment by Tirlititi** [comment]
You should be able to change the size of these inside the file ``{ModFolder}\StreamingAssets\Data\World\Environment.txt`` (or create one if it doesn't exist):
```txt
# Resize or reposition continent titles here
# Rect has format (x, y, width, height)
# where (x, y) is the central position of the title on the screen

Title MistContinent JP [Rect=(0, 144, 1024, 128)]
Title OuterContinent JP [Rect=(0, 144, 1024, 128)]
Title ForgottenContinent JP [Rect=(0, 144, 1024, 128)]
Title LostContinent JP [Rect=(0, 144, 1024, 128)]
```

Maybe the default size for the Japanese titles are not 1024x128. I need to verify that they still appear correctly in vanilla Japanese.
But for your mod, you can just write any size you want there.

**Comment by moldsax** [comment]
I appreciate your kindness.
The numbers below seem to be close to vanilla.

```
Title MistContinent JP [Rect=(0, 144, 512, 256)]
Title OuterContinent JP [Rect=(0, 144, 512, 256)]
Title ForgottenContinent JP [Rect=(0, 144, 512, 256)]
Title LostContinent JP [Rect=(0, 144, 512, 256)]
```

![377840_14](https://github.com/user-attachments/assets/c798443c-b893-4c8a-9cd4-0ba70049279f)
Personally, this solved the problem for me, but it's an obstacle when playing in Japanese, so I would like to see Menoria fixed.

**Comment by Tirlititi** [comment]
Thanks a bunch for reporting the bug. I think we'll release another small patch soon that contains the fix for it.

**Comment by yuyu-2021** [comment]
I see that there're 4 editable titles in the text file 'Environment.txt'.

If I try to edit more, what should I do to add them into the text ?

like 'South Gate'

**Comment by yuyu-2021** [comment]
> Thanks a bunch for reporting the bug. I think we'll release another small patch soon that contains the fix for it.

I see that there're 4 editable titles by default in 'Environment.txt'.

If I try to edit more, what should I do to add them into the text ?

like the 'South Gate' title.

**Comment by yuyu-2021** [comment]
> Thanks a bunch for reporting the bug. I think we'll release another small patch soon that contains the fix for it.

Thank you for your work💖

I see that there're 4 editable titles by default in 'Environment.txt'.

If I try to edit more, what should I do to add them into the text ?

like the 'South Gate' title.

**Comment by Tirlititi** [comment]
For these, you need to use another method.
The easiest is to run ``[Export] Translation`` if you haven't done it already: amongst the files it generates for a translation mod folder, there are the files in ``ExportedTranslationJP/StreamingAssets/Assets/Resources/FieldMaps/``. They contain both the PNG images of the place titles and a file with extension ``.bgx``. That file can be edited with a text editor and can be used to resize the place title images in-game if needed.

Example (Chocobo's Paradise title):
- PNG image ``ExportedTranslation/StreamingAssets/Assets/Resources/FieldMaps/FBG_N14_CHCB_MAP300_CH_FST_0/Title_3.png``
![image](https://github.com/Albeoris/Memoria/wiki/Images/Illustrations/ChocoboParadiseTitle.png)

- BGX file ``ExportedTranslation/StreamingAssets/Assets/Resources/FieldMaps/FBG_N14_CHCB_MAP300_CH_FST_0/FBG_N14_CHCB_MAP300_CH_FST_0.bgx``
```txt
USE_BASE_SCENE
LANGUAGE: US

OVERLAY
OverlayId: 3
CameraId: 0
ViewportId: 0
Position: 64, 176, 9
Size: 208, 80
Image: Title_3.png
Shader: PSX/FieldMap_Abr_None
```

More infos [there](https://github.com/Albeoris/Memoria/wiki/Translation-mods#place-titles)

**Comment by yuyu-2021** [comment]
> For these, you need to use another method. The easiest is to run `[Export] Translation` if you haven't done it already: amongst the files it generates for a translation mod folder, there are the files in `ExportedTranslationJP/StreamingAssets/Assets/Resources/FieldMaps/`. They contain both the PNG images of the place titles and a file with extension `.bgx`. That file can be edited with a text editor and can be used to resize the place title images in-game if needed.
> 
> Example (Chocobo's Paradise title):
> 
> * PNG image `ExportedTranslation/StreamingAssets/Assets/Resources/FieldMaps/FBG_N14_CHCB_MAP300_CH_FST_0/Title_3.png`
>   ![image](https://github.com/Albeoris/Memoria/wiki/Images/Illustrations/ChocoboParadiseTitle.png)
> * BGX file `ExportedTranslation/StreamingAssets/Assets/Resources/FieldMaps/FBG_N14_CHCB_MAP300_CH_FST_0/FBG_N14_CHCB_MAP300_CH_FST_0.bgx`
> 
> ```
> USE_BASE_SCENE
> LANGUAGE: US
> 
> OVERLAY
> OverlayId: 3
> CameraId: 0
> ViewportId: 0
> Position: 64, 176, 9
> Size: 208, 80
> Image: Title_3.png
> Shader: PSX/FieldMap_Abr_None
> ```
> 
> More infos [there](https://github.com/Albeoris/Memoria/wiki/Translation-mods#place-titles)

Love u my man!💖

**Comment by yuyu-2021** [comment]
> For these, you need to use another method. The easiest is to run `[Export] Translation` if you haven't done it already: amongst the files it generates for a translation mod folder, there are the files in `ExportedTranslationJP/StreamingAssets/Assets/Resources/FieldMaps/`. They contain both the PNG images of the place titles and a file with extension `.bgx`. That file can be edited with a text editor and can be used to resize the place title images in-game if needed.
> 
> Example (Chocobo's Paradise title):
> 
> * PNG image `ExportedTranslation/StreamingAssets/Assets/Resources/FieldMaps/FBG_N14_CHCB_MAP300_CH_FST_0/Title_3.png`
>   ![image](https://github.com/Albeoris/Memoria/wiki/Images/Illustrations/ChocoboParadiseTitle.png)
> * BGX file `ExportedTranslation/StreamingAssets/Assets/Resources/FieldMaps/FBG_N14_CHCB_MAP300_CH_FST_0/FBG_N14_CHCB_MAP300_CH_FST_0.bgx`
> 
> ```
> USE_BASE_SCENE
> LANGUAGE: US
> 
> OVERLAY
> OverlayId: 3
> CameraId: 0
> ViewportId: 0
> Position: 64, 176, 9
> Size: 208, 80
> Image: Title_3.png
> Shader: PSX/FieldMap_Abr_None
> ```
> 
> More infos [there](https://github.com/Albeoris/Memoria/wiki/Translation-mods#place-titles)

I tried this method with a clean FFIX game flie . (newly downloaded , no mods , latest memoria only.)

Then I used the function 'export'--'translation' with the language "JP" selected,

However , all I can get was a 'ExportedTranslationUS'  floder but not 'ExportedTranslationJP'.

![QQ20241125-162728](https://github.com/user-attachments/assets/37a51e70-7581-491a-a0b3-b60784497dde)

Did I miss any steps .....?  And could you let me know how should I fix this ?


Here is my setting:

[Export]
	; no effect in game
	; TextFileFormat: determines in what format the text resources will be exported; possible values: .strings, .resjson
Enabled = 1
Path = %ExportedTranslationJP%
Languages = "JP"
Text = 0
Graphics = 0
Audio = 0
Field = 0
Battle = 0
TextFileFormat = .strings
Translation = 1

**Comment by Tirlititi** [comment]
``[Export] Translation`` doesn't use the fields ``Languages`` and ``Path`` there, contrary to the other export options.
In order to use the base language "Japanese" for this, you first need to launch the game normally and select "Japanese" as the in-game language. Then activate the ``[Export]`` option and re-launch.

**Comment by yuyu-2021** [comment]
> `[Export] Translation` doesn't use the fields `Languages` and `Path` there, contrary to the other export options. In order to use the base language "Japanese" for this, you first need to launch the game normally and select "Japanese" as the in-game language. Then activate the `[Export]` option and re-launch.

Actually I foud that if I change all the 'LANGUAGE: US' into 'LANGUAGE: JP' , and replace the US pictures with the JPs, then the problem will be solved.

![538D66F571DC466B8A74BCD7BC69881C](https://github.com/user-attachments/assets/fd973447-6f72-459d-8c47-2b58cbb3ba18)

**Comment by Tirlititi** [comment]
If it works, then that's great.
I am afraid that, by doing it like that, you could have problems because of layer informations mismatch (assuming you use Japanese as the base language for the translation; if your mod replaces the language "English (US)", then there won't be any problem).

**Comment by yuyu-2021** [comment]
> If it works, then that's great. I am afraid that, by doing it like that, you could have problems because of layer informations mismatch (assuming you use Japanese as the base language for the translation; if your mod replaces the language "English (US)", then there won't be any problem).

[https://www.bilibili.com/video/BV1b6z3YXELX/?vd_source=bf592495f2a83a462e30dcdd360eec4d](url)

**Comment by yuyu-2021** [comment]
> If it works, then that's great. I am afraid that, by doing it like that, you could have problems because of layer informations mismatch (assuming you use Japanese as the base language for the translation; if your mod replaces the language "English (US)", then there won't be any problem).

[https://www.bilibili.com/video/BV1b6z3YXELX/?vd_source=bf592495f2a83a462e30dcdd360eec4d](url)

**Comment by Tirlititi** [comment]
Hello. You are right, that doesn't work anymore for some reason. I may have changed something that broke the language selection there at some point.
I'll fix that, sorry.

**Comment by Tirlititi** [comment]
In the meantime, here is a pack with these place titles and files ``.bgx``: you should already be able to use and mod them.
[Dropbox download link](https://www.dropbox.com/scl/fi/3fierzqcb3uwd1vf45cue/FF9_PlaceTitles_Japanese.zip?rlkey=ats7xsb89lo1oyra4a26avftn&st=2em8h2bs&dl=1)

**Comment by yuyu-2021** [comment]
> In the meantime, here is a pack with these place titles and files `.bgx`: you should already be able to use and mod them. [Dropbox download link](https://www.dropbox.com/scl/fi/3fierzqcb3uwd1vf45cue/FF9_PlaceTitles_Japanese.zip?rlkey=ats7xsb89lo1oyra4a26avftn&st=2em8h2bs&dl=1)

Horray !!!!  Honestly I‘m so excited about this right now . hahahaha  !!

Let's get to work~

[
![538D66F571DC466B8A74BCD7BC69881C](https://github.com/user-attachments/assets/59dfe170-c26c-4639-b19a-a9a3807e6281)
![F6FE8B4F7F8DE49959EB9D964D65C951](https://github.com/user-attachments/assets/9196f944-b80a-4987-ab1f-988b5e6d21e2)
](url)
