### ISSUE TITLE
Red Rose Background glitched out.

### ISSUE THREAD

**Issue by theultimatezero** [Albeoris/Memoria#973]
![Screenshot 2024-11-23 180204](https://github.com/user-attachments/assets/335cf0ca-7dd3-4bcf-8f5d-a721a003b2fb)
![Screenshot 2024-11-23 181026](https://github.com/user-attachments/assets/5fafb805-d619-4a13-95a6-21fe5d4c358b)
The background of this area is glitched out, even when the characters are talking. I loaded my last save file and got to this area again and it's still the same. I can move around and go to other parts of the area completely fine. No other areas showed issues like this. How do I fix it?

**Comment by Tirlititi** [comment]
I can't reproduce the bug, with or without the Moguri Mod: these fields look perfectly fine.
In your screenshots, it looks like you have upscaled background settings (``TileSize = 64``) but the image itself is not upscaled.

What mod(s) are you using?
Try updating Moguri anyway, I guess.

**Comment by Silva1989** [comment]
I've seen someone on reddit complaining about it. He/she was running the game on a steam deck
https://www.reddit.com/r/FinalFantasyIX/s/Gvuh3pnfHB

**Comment by theultimaetzero** [comment]
> I've seen someone on reddit complaining about it. He/she was running the game on a steam deck https://www.reddit.com/r/FinalFantasyIX/s/Gvuh3pnfHB

That was me....

**Comment by theultimaetzero** [comment]
> I can't reproduce the bug, with or without the Moguri Mod: these fields look perfectly fine. In your screenshots, it looks like you have upscaled background settings (`TileSize = 64`) but the image itself is not upscaled.
> 
> What mod(s) are you using? Try updating Moguri anyway, I guess.

I'm only using moguri mod and I've update it, thank you anyway.

**Comment by faospark** [comment]
the only way for that to happen is if your tilesize is not set to 64 in the main memoria.ini and or 
FINAL FANTASY IX\MoguriMain\Memoria.ini

**Comment by SamsamTS** [comment]
So what was it if you don't mind? It would be nice to know, somebody might encounter the same issue in the future.
