### ISSUE TITLE
Launcher cant read and save

### ISSUE THREAD

**Issue by daffies** [Albeoris/Memoria#974]
Hello, whenever I open the new launcher, it reported several errors related to files. Clicking ok will have the launcher opens. Any changes made to the launcher will show some error and wont be saved on the next launch. 

After some testing, it seems that only those saved in memoria.ini having this problem. Those in settings.ini is fine.

Manually change the setting in memoria.ini then launch the game using the launcher despite showing error, works with all the edited settings.

And this doesn't happen with the previous launcher.

Thanks.

**Comment by SamsamTS** [comment]
Can we see those error messages?
It could be something about file access. Try deleting (or just renaming) `Memoria.ini` the launcher should create a new one.

**Comment by daffies** [comment]
When Memoria.ini file exist, I got this when I open the launcher
![1](https://github.com/user-attachments/assets/4dfafd06-59bf-4953-b96a-5c5880a1021b)

Then this if I tried to edit one of the setting
![2](https://github.com/user-attachments/assets/df920910-46ad-4d92-aaab-ce680beff33b)

After deleting the settings.ini and Memoria.ini, the launcher open without error. Editing setting through launcher also no error but reopen the launcher same error happen and setting is not saved too.

**Comment by SamsamTS** [comment]
It seems something is wrong with your files.
Can your share both your `Memoria.ini` and `Settings.ini`?

**Comment by daffies** [comment]
I have to zip the files as I couldn't upload .ini files

[Memoria and Settings.zip](https://github.com/user-attachments/files/17916488/Memoria.and.Settings.zip)

**Comment by daffies** [comment]
I redownloaded the patcher, reinstall the game. It's still the same.

I will stick to manually edit the Memoria.ini, as this way the game launch with the setting and mod applied despite the error and edited options not displayed in the new launcher.

Probably something is wrong with this pc.

Thank you for your assistance
