### ISSUE TITLE
Selection  of characters too large in widescreen

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#98]
When entering a character choice window in widescreen does this:

![2020-05-12 02_19_18-FINAL FANTASY IX - Map_ 2850, Loc_ 186 Name_ A  Castle_Tomb](https://user-images.githubusercontent.com/9964576/81658461-14b9f780-9439-11ea-9ef2-e88a373f0a68.jpg)

The selection highlight becomes twice as large as the portraits.
Entering with widescreen off, the problem is not there.

Here's a save file if needed: https://en.reddit.com/r/FinalFantasyIX/comments/ggjzr4/crazy_question/fq2w54n/ (for example slot 7, save 2 in the ship)

**Comment by Albeoris** [comment]
"UI Root" -> "Party Setting Container" -> "Character Select Outside Panel" -> "Other Character Panel" -> "Table" -> "Character Button (1)" -> "Highlight" -> [UISprite]

Anchors are set up for it. We need to either change the anchors or adjust the parents.

**Comment by Albeoris** [comment]
![](https://i.imgur.com/ki8QQkV.png)

**Comment by snouz** [comment]
bug fixed since then

![image](https://github.com/Albeoris/Memoria/assets/9964576/0e4ce203-2896-4303-9ac0-0719a2bc2454)
