### ISSUE TITLE
[UI] Widescreen pause screen overlay does not extend

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#99]
![2020-05-12 11_23_37-Steam](https://user-images.githubusercontent.com/9964576/81667742-f1e11080-9443-11ea-9f42-84d5213fe6f3.jpg)

**Comment by Albeoris** [comment]
A long time ago, I spent a lot of time on this damn overlay. Strange, it seemed to me that I fixed it.

**Comment by snouz** [comment]
:/
It happens on field and battles too

**Comment by snouz** [comment]
Extra information: in widescreen mode, on fields that have been excluded from widescreen, when you are on pause, black bars are also missing:

![2020-05-18 18_47_32-FINAL FANTASY IX - Map_ 1215, Loc_ 289 Name_ A  Castle_Hallway](https://user-images.githubusercontent.com/9964576/82238870-3aaf3280-9938-11ea-92ba-cc3e407ef7fa.jpg)
