### ISSUE TITLE
Moguri Mod download stuck

### ISSUE THREAD

**Issue by Gedoval** [Albeoris/Memoria#996]
Hi,

I'm following the installation instructios for the Moguri Mod, but the download always freezes near the end (time left ~20 minutes). I'm using Windows 10 ant the v2024.12.06 of Memoria Engine. I did a full reinstall of everything but it always gets stuck at the exact same time. I can't see any errores on Memoria.log

Thanks.

**Comment by SamsamTS** [comment]
That's probably more of a hosting issue. Try downloading the mod from moddb: https://www.moddb.com/mods/moguri-mod/downloads/moguri-mod-90
To install it just drag and drop the archive onto the launcher window (Moguri is a big mod, it might take a minute or two to decompress).

**Comment by Gedoval** [comment]
That did it. 
Thank you
